import type { ResearchAuthor, ResearchCategory, ResearchPaper } from "./types";

export const RESEARCH_SEED_CATEGORIES: ResearchCategory[] = [
  { slug: "fiqh", name_ar: "الفقه", icon: "⚙️" },
  { slug: "hadith", name_ar: "الحديث", icon: "📜" },
  { slug: "quran-sciences", name_ar: "علوم القرآن", icon: "📖" },
  { slug: "aqeedah", name_ar: "العقيدة", icon: "🕌" },
];

export const RESEARCH_SEED_PAPERS: ResearchPaper[] = [
  {
    id: "seed-001",
    slug: "fiqh-al-zakat-contemporary",
    title: "الزكاة في المعاملات المعاصرة: دراسة فقهية مقارنة",
    abstract_short: "دراسة تحليلية لأحكام الزكاة في الأدوات المالية الحديثة.",
    abstract_full:
      "تتناول هذه الرسالة أحكام الزكاة في الأسهم والعملات الرقمية والصناديق الاستثمارية، مع عرض آراء الفقهاء المعاصرين والمراجع المعتمدة، وبيان التطبيقات العملية في الأسواق العربية.",
    degree_type: "masters",
    category_slug: "fiqh",
    specialization: "الفقه المقارن",
    author_name: "فاطمة العازمي",
    supervisor_name: "د. محمد الحسين",
    university: "جامعة الكويت",
    faculty: "كلية الشريعة والدراسات الإسلامية",
    department: "الفقه وأصوله",
    country: "الكويت",
    publication_year: 2024,
    page_count: 186,
    language: "ar",
    keywords: ["زكاة", "معاملات معاصرة", "فقه مقارن"],
    cover_url: "/images/research/default-cover.svg",
    pdf_url: "#",
    copyright_type: "cite_with_attribution",
    status: "published",
    views_count: 1240,
    downloads_count: 430,
    shares_count: 89,
    saves_count: 156,
    rating_avg: 4.7,
    rating_count: 38,
    published_at: "2024-06-15T00:00:00Z",
  },
  {
    id: "seed-002",
    slug: "hadith-authentication-methods",
    title: "منهجية التحقيق في الأحاديث النبوية: دراسة منهجية",
    abstract_short: "عرض لقواعد التحقيق عند علماء الحديث مع تطبيقات عملية.",
    abstract_full:
      "رسالة علمية تستعرض منهج التحقيق عند الإمام الذهبي وابن حجر، وتطبق ذلك على مجموعة من الأحاديث المشهورة، مع بيان الفروق بين التweak والصحيح وفق ضوابط أهل السنة.",
    degree_type: "phd",
    category_slug: "hadith",
    specialization: "علوم الحديث",
    author_name: "عبدالله المطيري",
    supervisor_name: "د. سعد الشثري",
    university: "الجامعة الإسلامية بالمدينة",
    faculty: "كلية الحديث",
    department: "علوم الحديث",
    country: "السعودية",
    publication_year: 2023,
    page_count: 412,
    language: "ar",
    keywords: ["حديث", "تحقيق", "منهجية", "جرح وتعديل"],
    cover_url: "/images/research/default-cover.svg",
    pdf_url: "#",
    copyright_type: "all_rights_reserved",
    status: "published",
    views_count: 2890,
    downloads_count: 920,
    shares_count: 210,
    saves_count: 340,
    rating_avg: 4.9,
    rating_count: 72,
    published_at: "2023-11-20T00:00:00Z",
  },
  {
    id: "seed-003",
    slug: "quran-tafsir-thematic-study",
    title: "التفسير الموضوعي للقرآن الكريم: منهج ونماذج",
    abstract_short: "دراسة في منهج التفسير الموضوعي ونماذج تطبيقية من سور مختارة.",
    abstract_full:
      "بحث أكاديمي يعرّف بالتفسير الموضوعي ويُقارنه بالتفسير التحليلي، مع نماذج من سور الإخلاص والفاتحة وآيات الأحكام، مستنداً إلى كتب التفسير المعتمدة.",
    degree_type: "peer_reviewed",
    category_slug: "quran-sciences",
    specialization: "التفسير وعلوم القرآن",
    author_name: "نورة السالم",
    supervisor_name: "د. أحمد الغامدي",
    university: "جامعة أم القرى",
    faculty: "كلية الدعوة",
    department: "التفسير",
    country: "السعودية",
    publication_year: 2025,
    page_count: 98,
    language: "ar",
    keywords: ["تفسير", "موضوعي", "قرآن"],
    cover_url: "/images/research/default-cover.svg",
    pdf_url: "#",
    copyright_type: "creative_commons",
    status: "published",
    views_count: 870,
    downloads_count: 310,
    shares_count: 45,
    saves_count: 98,
    rating_avg: 4.5,
    rating_count: 21,
    published_at: "2025-01-10T00:00:00Z",
  },
];

export const RESEARCH_SEED_AUTHORS: ResearchAuthor[] = [
  {
    id: "author-001",
    slug: "fatima-al-azmi",
    full_name: "فاطمة العازمي",
    bio: "باحثة في الفقه المقارن والمعاملات المعاصرة.",
    university: "جامعة الكويت",
    specialization: "الفقه",
    degree: "ماجستير",
    country: "الكويت",
    papers_count: 1,
    views_count: 1240,
    downloads_count: 430,
  },
  {
    id: "author-002",
    slug: "abdullah-al-mutairi",
    full_name: "عبدالله المطيري",
    bio: "أخصائي في علوم الحديث والتحقيق.",
    university: "الجامعة الإسلامية بالمدينة",
    specialization: "علوم الحديث",
    degree: "دكتوراه",
    country: "السعودية",
    papers_count: 1,
    views_count: 2890,
    downloads_count: 920,
  },
];
