/** Server-side seed fallback for research API */
export const RESEARCH_SEED_PAPERS = [
  {
    id: "seed-001",
    slug: "fiqh-al-zakat-contemporary",
    title: "الزكاة في المعاملات المعاصرة: دراسة فقهية مقارنة",
    abstract_short: "دراسة تحليلية لأحكام الزكاة في الأدوات المالية الحديثة.",
    abstract_full: "تتناول هذه الرسالة أحكام الزكاة في الأسهم والعملات الرقمية والصناديق الاستثمارية.",
    degree_type: "masters",
    category_slug: "fiqh",
    author_name: "فاطمة العازمي",
    supervisor_name: "د. محمد الحسين",
    university: "جامعة الكويت",
    country: "الكويت",
    publication_year: 2024,
    page_count: 186,
    language: "ar",
    keywords: ["زكاة", "معاملات معاصرة"],
    copyright_type: "cite_with_attribution",
    status: "published",
    views_count: 1240,
    downloads_count: 430,
    saves_count: 156,
    rating_avg: 4.7,
    published_at: "2024-06-15T00:00:00Z",
  },
  {
    id: "seed-002",
    slug: "hadith-authentication-methods",
    title: "منهجية التحقيق في الأحاديث النبوية: دراسة منهجية",
    degree_type: "phd",
    category_slug: "hadith",
    author_name: "عبدالله المطيري",
    university: "الجامعة الإسلامية بالمدينة",
    country: "السعودية",
    publication_year: 2023,
    language: "ar",
    status: "published",
    views_count: 2890,
    downloads_count: 920,
    saves_count: 340,
    rating_avg: 4.9,
    published_at: "2023-11-20T00:00:00Z",
  },
  {
    id: "seed-003",
    slug: "quran-tafsir-thematic-study",
    title: "التفسير الموضوعي للقرآن الكريم: منهج ونماذج",
    degree_type: "peer_reviewed",
    category_slug: "quran-sciences",
    author_name: "نورة السالم",
    university: "جامعة أم القرى",
    country: "السعودية",
    publication_year: 2025,
    language: "ar",
    status: "published",
    views_count: 870,
    downloads_count: 310,
    saves_count: 98,
    rating_avg: 4.5,
    published_at: "2025-01-10T00:00:00Z",
  },
];
