-- universities_expand_v3.sql
-- توسيع كتالوج الجامعات الشرعية بجامعات ومؤسسات موثقة مباشرة في 2026-07-27.
-- لا يتضمن الملف رسوماً أو مواعيد قبول ثابتة؛ كل صف يستخدم الموقع الرسمي فقط.
INSERT INTO universities
  (id, slug, name_ar, name_en, country, city, logo_url, about, website_url, social_links, accreditation_status, is_verified, is_published, last_updated_at, last_reviewed_by, created_at)
VALUES
(gen_random_uuid(), 'al-qarawiyyin', 'جامعة القرويين', 'University of al-Qarawiyyin',
 'المغرب', 'فاس', '',
 'جامعة مغربية عريقة في فاس، تُذكر في مراجع مثل اليونسكو وموسوعة غينيس بوصفها من أقدم المؤسسات التعليمية المستمرة في منح الدرجات. يعرض موقعها الرسمي مسارات في الشريعة واللغة العربية والتاريخ والحضارة الإسلامية ضمن منظومة التعليم العالي المغربي.',
 'https://uaq.ma', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'usim-malaysia', 'جامعة العلوم الإسلامية الماليزية', 'Universiti Sains Islam Malaysia (USIM)',
 'ماليزيا', 'نِيلاي', '',
 'جامعة ماليزية عامة ذات توجه في دمج العلوم الإسلامية والمعرفة الحديثة. تضم كلية الشريعة والقانون FSU التي تعرض برامج في الشريعة والقانون والأنظمة القانونية، إضافة إلى كليات للقرآن والسنة والدعوة والإدارة.',
 'https://www.usim.edu.my', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'mediu-malaysia', 'جامعة المدينة العالمية', 'Al-Madinah International University (MEDIU)',
 'ماليزيا', 'شاه علم', '',
 'جامعة خاصة في ماليزيا تقدم برامج أكاديمية في العلوم الإسلامية واللغة العربية والتربية والإدارة، وتُعرف بإتاحة مسارات حضورية وعن بعد بحسب البرنامج واللوائح الرسمية.',
 'https://www.mediu.edu.my', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'uin-sunan-kalijaga', 'جامعة سونان كاليجاغا الإسلامية الحكومية', 'UIN Sunan Kalijaga Yogyakarta',
 'إندونيسيا', 'يوجياكارتا', '',
 'جامعة إسلامية حكومية في يوجياكارتا تُعد من أقدم جامعات UIN في إندونيسيا، وتضم كليات في الشريعة والقانون، وأصول الدين والفكر الإسلامي، والتربية. تُذكر بعض تغطيات SCImago 2026 للدراسات الدينية بحذر ولا تُعد بديلاً عن الاعتماد الرسمي.',
 'https://uin-suka.ac.id', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'kuwait-sharia', 'كلية الشريعة والدراسات الإسلامية — جامعة الكويت', 'College of Sharia and Islamic Studies, Kuwait University',
 'الكويت', 'مدينة الكويت', '',
 'كلية الشريعة والدراسات الإسلامية بجامعة الكويت، تأسست عام 1982، وتقدم برامج جامعية في الفقه وأصوله والتفسير والحديث والعقيدة والدعوة، ضمن الجامعة الحكومية الرئيسة في الكويت.',
 'https://shi.ku.edu.kw', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'hbku-cis', 'كلية الدراسات الإسلامية — جامعة حمد بن خليفة', 'College of Islamic Studies, HBKU',
 'قطر', 'الدوحة', '',
 'كلية الدراسات الإسلامية في جامعة حمد بن خليفة تقدم برامج دراسات عليا وبحثاً في قضايا إسلامية معاصرة، منها الفقه والمجتمع، التمويل الإسلامي، الفن والعمارة الإسلامية، والأخلاق التطبيقية.',
 'https://www.hbku.edu.qa/en/cis', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'mbzuh', 'جامعة محمد بن زايد للعلوم الإنسانية', 'Mohamed Bin Zayed University for Humanities',
 'الإمارات العربية المتحدة', 'أبوظبي', '',
 'جامعة إماراتية متخصصة في العلوم الإنسانية والدراسات الإسلامية واللغة العربية، وتعرض برامج في الفقه والفتوى، والقرآن والحديث، والخطاب الديني، بما يخدم التأهيل الشرعي والإنساني المعاصر.',
 'https://www.mbzuh.ac.ae', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'emir-abdelkader-constantine', 'جامعة الأمير عبد القادر للعلوم الإسلامية', 'Emir Abdelkader University of Islamic Sciences',
 'الجزائر', 'قسنطينة', '',
 'جامعة جزائرية متخصصة في العلوم الإسلامية بقسنطينة، تأسست في صورتها الجامعية الحديثة في ثمانينيات القرن العشرين، وتضم تكويناً في الشريعة وأصول الدين والحضارة الإسلامية واللغة العربية.',
 'https://www.univ-emir-constantine.edu.dz', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'cambridge-muslim-college', 'كلية كامبريدج للمسلمين', 'Cambridge Muslim College',
 'المملكة المتحدة', 'كامبريدج', '',
 'كلية مستقلة في كامبريدج تقدم برنامج BA (Hons) in Islamic Studies معتمد التحقق من The Open University بوصفها الجهة المانحة، وتعلن قبول دفعة 2026 عبر موقعها. تجمع الدراسة بين العلوم الإسلامية التقليدية والمعرفة المعاصرة.',
 'https://www.cambridgemuslimcollege.ac.uk', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'soas-islamic-studies', 'كلية الدراسات الشرقية والأفريقية — جامعة لندن', 'SOAS University of London',
 'المملكة المتحدة', 'لندن', '',
 'جامعة لندن SOAS مؤسسة أكاديمية متخصصة في آسيا وأفريقيا والشرق الأوسط، وتقدم دراسة أكاديمية للإسلام وأديان الشرق الأوسط ضمن سياقات التاريخ واللغة والسياسة والمجتمع.',
 'https://www.soas.ac.uk', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'edinburgh-imes', 'الدراسات الإسلامية والشرق أوسطية — جامعة إدنبرة', 'University of Edinburgh Islamic and Middle Eastern Studies',
 'المملكة المتحدة', 'إدنبرة', '',
 'قسم الدراسات الإسلامية والشرق أوسطية في جامعة إدنبرة يقدم برامج أكاديمية في الإسلام والشرق الأوسط واللغة العربية والفارسية والتركية ضمن كلية الآداب والعلوم الإنسانية والاجتماعية.',
 'https://www.ed.ac.uk', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'ankara-ilahiyat', 'كلية الإلهيات — جامعة أنقرة', 'Ankara University Faculty of Theology',
 'تركيا', 'أنقرة', '',
 'كلية الإلهيات بجامعة أنقرة من أقدم كليات الإلهيات الحديثة في تركيا، وتقدم تعليماً أكاديمياً في العلوم الإسلامية الأساسية والفلسفة والدراسات الدينية والتربية الدينية.',
 'https://www.divinity.ankara.edu.tr', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'islamic-university-niger', 'الجامعة الإسلامية بالنيجر', 'Islamic University of Niger',
 'النيجر', 'نيامي/ساي', '',
 'جامعة إسلامية في النيجر مرتبطة بمنظمة التعاون الإسلامي، وتقدم برامج في الشريعة والقانون واللغة العربية والدراسات الإسلامية لخدمة غرب أفريقيا والساحل.',
 'https://www.uin-ne.org', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'king-saud-islamic-studies', 'جامعة الملك سعود — برامج الشريعة والدراسات الإسلامية', 'King Saud University - Islamic Studies and Sharia Programmes',
 'المملكة العربية السعودية', 'الرياض', '',
 'جامعة الملك سعود جامعة حكومية سعودية في الرياض، وتضم ضمن كلياتها وأقسامها برامج في الثقافة الإسلامية والدراسات الإسلامية والشريعة ذات صلة بالتأهيل الشرعي والبحث الإنساني، دون افتراض اسم كلية غير مؤكد في هذا الكتالوج.',
 'https://www.ksu.edu.sa', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'al-bayt-university-sharia', 'جامعة آل البيت — كلية الشريعة', 'Al al-Bayt University Faculty of Sharia',
 'الأردن', 'المفرق', '',
 'جامعة آل البيت جامعة أردنية في المفرق، وهي مؤسسة مختلفة عن جامعة العلوم الإسلامية العالمية WISE. تضم كلية شريعة تقدم برامج في الفقه وأصوله وأصول الدين والدراسات الإسلامية حسب خطط الجامعة.',
 'https://www.aabu.edu.jo', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'mustansiriya-quran', 'الجامعة المستنصرية — قسم علوم القرآن والتربية الإسلامية', 'Mustansiriyah University - Department of Quran Sciences and Islamic Education',
 'العراق', 'بغداد', '',
 'الجامعة المستنصرية جامعة عراقية حكومية في بغداد. يدرج هذا الصف قسم علوم القرآن الكريم والتربية الإسلامية بوصفه مساراً أكاديمياً مرتبطاً بالقرآن والتربية الإسلامية داخل الجامعة.',
 'https://www.uomustansiriyah.edu.iq', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'amu-islamic-studies', 'جامعة عليكرة الإسلامية — قسم الدراسات الإسلامية', 'Aligarh Muslim University - Department of Islamic Studies',
 'الهند', 'عليكرة', '',
 'جامعة عليكرة الإسلامية جامعة مركزية هندية عريقة، ويقدم قسم الدراسات الإسلامية فيها برامج أكاديمية في تاريخ الفكر الإسلامي والحضارة الإسلامية والقرآن والحديث والدراسات المعاصرة.',
 'https://www.amu.ac.in', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now()),
(gen_random_uuid(), 'istanbul-ilahiyat', 'كلية الإلهيات — جامعة إسطنبول', 'Istanbul University Faculty of Theology',
 'تركيا', 'إسطنبول', '',
 'كلية الإلهيات في جامعة إسطنبول تقدم برامج أكاديمية في العلوم الإسلامية الأساسية والفلسفة والدراسات الدينية والتاريخ الإسلامي، ويُستخدم رابط الكلية الرسمي عند توفره.',
 'https://ilahiyat.istanbul.edu.tr', '{}'::jsonb, 'accredited', true, true, now(), 'تحقق مباشر — 2026-07-27', now())
ON CONFLICT (slug) DO NOTHING;
