// Writes dist/version.json with the deployed commit + build time so the live
// site always reveals exactly which build is serving. Fetch it at /version.json.
// Commit SHA comes from the CI/host env (Vercel / GitHub Actions), with a local
// git fallback for dev builds.
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(__dirname, "..", "dist");

function resolveCommit() {
  const fromEnv =
    process.env.VERCEL_GIT_COMMIT_SHA ||
    process.env.GITHUB_SHA ||
    process.env.COMMIT_SHA ||
    "";
  if (fromEnv) return fromEnv;
  try {
    return execSync("git rev-parse HEAD", { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
}

const commit = resolveCommit();
const payload = {
  commit,
  shortCommit: commit.slice(0, 8),
  builtAt: new Date().toISOString(),
  ref:
    process.env.VERCEL_GIT_COMMIT_REF ||
    process.env.GITHUB_REF_NAME ||
    "main",
};

await writeFile(resolve(distDir, "version.json"), JSON.stringify(payload, null, 2) + "\n", "utf8");
console.log(`[version] wrote dist/version.json → ${payload.shortCommit} @ ${payload.builtAt}`);

// Also emit dist/sw-version.js — a tiny classic script the Service Worker
// (public/sw.js) loads via importScripts() to derive its cache names from
// the ACTUAL deployed commit instead of a hand-maintained "v18"-style
// constant. This is the fix for a real bug: a manually-bumped cache version
// is trivial to forget when editing sw.js, silently leaving returning PWA
// users on stale cached lesson/fawaid data after a deploy. Runs after
// `vite build` (which copies public/ verbatim into dist/ first), so this
// file only ever exists in the built output — never in the public/ source
// tree — and safely lands alongside the sw.js that vite already copied.
const swVersionContent = `// AUTO-GENERATED by scripts/generate-version.mjs at build time — do not edit by hand.
// Consumed by public/sw.js via importScripts("/sw-version.js") to build
// commit-based cache names (see SHELL_CACHE / DATA_CACHE there).
self.SW_BUILD_ID = ${JSON.stringify(payload.shortCommit)};
`;
await writeFile(resolve(distDir, "sw-version.js"), swVersionContent, "utf8");
console.log(`[version] wrote dist/sw-version.js → SW_BUILD_ID=${payload.shortCommit}`);
