import { buildContentUrl } from "@/lib/content-url";

export type ContentTableConfig = {
  table: string;
  kind: CmsContentKind;
  titleField: string;
  summaryField?: string;
  bodyField?: string;
  speakerField?: string;
  categoryField?: string;
  statusField: string;
  externalKeyField?: string;
  slugField?: string;
  archivedField?: string;
  publishedField?: string;
  scheduledField?: string;
  /** Map workflow status to table-specific status values */
  statusMap: Partial<Record<CmsWorkflowStatus, string>>;
  publicRoute: (id: string) => string;
};

export const CONTENT_REGISTRY: Record<CmsContentKind, ContentTableConfig> = {
  lesson: {
    table: "lessons",
    kind: "lesson",
    titleField: "title",
    summaryField: "description",
    speakerField: "speaker_name",
    categoryField: "category",
    statusField: "status",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    publishedField: "published_at",
    scheduledField: "scheduled_at",
    statusMap: { approved: "approved", pending: "pending", rejected: "rejected", archived: "rejected" },
    publicRoute: (id) => buildContentUrl({ kind: "lesson", id }),
  },
  lecture: {
    table: "lessons",
    kind: "lecture",
    titleField: "title",
    summaryField: "description",
    speakerField: "speaker_name",
    categoryField: "category",
    statusField: "status",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    publishedField: "published_at",
    scheduledField: "scheduled_at",
    statusMap: { approved: "approved", pending: "pending", rejected: "rejected" },
    publicRoute: (id) => buildContentUrl({ kind: "lesson", id }),
  },
  course: {
    table: "lessons",
    kind: "course",
    titleField: "title",
    summaryField: "description",
    speakerField: "speaker_name",
    categoryField: "category",
    statusField: "status",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    publishedField: "published_at",
    scheduledField: "scheduled_at",
    statusMap: { approved: "approved", pending: "pending", rejected: "rejected" },
    publicRoute: (id) => buildContentUrl({ kind: "lesson", id }),
  },
  sheikh: {
    table: "sheikhs",
    kind: "sheikh",
    titleField: "name",
    summaryField: "bio",
    bodyField: "biography",
    categoryField: "city",
    statusField: "is_verified",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    statusMap: { approved: "true", published: "true", archived: "false" },
    publicRoute: (id) => `/lessons?sheikh=${id}`,
  },
  book: {
    table: "library_items",
    kind: "book",
    titleField: "title",
    summaryField: "description",
    categoryField: "category",
    statusField: "status",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    publishedField: "published_at",
    scheduledField: "scheduled_at",
    statusMap: { approved: "approved", pending: "pending", rejected: "rejected" },
    publicRoute: () => `/library`,
  },
  article: {
    table: "library_items",
    kind: "article",
    titleField: "title",
    summaryField: "description",
    categoryField: "category",
    statusField: "status",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    publishedField: "published_at",
    statusMap: { approved: "approved", pending: "pending" },
    publicRoute: () => `/library`,
  },
  fatwa: {
    table: "fatwas",
    kind: "fatwa",
    titleField: "question",
    summaryField: "summary",
    bodyField: "answer",
    categoryField: "category",
    statusField: "status",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    publishedField: "published_at",
    scheduledField: "scheduled_at",
    statusMap: { approved: "approved", pending: "pending", draft: "draft", archived: "archived", rejected: "rejected" },
    publicRoute: (id) => `/fatwa/${id}`,
  },
  news: {
    table: "platform_updates",
    kind: "news",
    titleField: "title",
    summaryField: "summary",
    bodyField: "body",
    statusField: "status",
    externalKeyField: "external_key",
    publishedField: "published_at",
    statusMap: { approved: "approved", published: "approved", pending: "pending" },
    publicRoute: () => `/updates`,
  },
  announcement: {
    table: "platform_updates",
    kind: "announcement",
    titleField: "title",
    summaryField: "summary",
    bodyField: "body",
    statusField: "status",
    externalKeyField: "external_key",
    publishedField: "published_at",
    statusMap: { approved: "approved", published: "approved" },
    publicRoute: () => `/updates`,
  },
  fawaid: {
    table: "fawaid",
    kind: "fawaid",
    titleField: "text",
    speakerField: "author_name",
    statusField: "status",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    publishedField: "published_at",
    statusMap: { approved: "approved", pending: "pending", rejected: "rejected" },
    publicRoute: () => `/fawaid`,
  },
  qa: {
    table: "qa_questions",
    kind: "qa",
    titleField: "question",
    bodyField: "answer",
    statusField: "status",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    publishedField: "published_at",
    scheduledField: "scheduled_at",
    statusMap: { approved: "published", published: "published", pending: "draft", draft: "draft" },
    publicRoute: () => `/qa`,
  },
  miracle: {
    table: "scientific_miracles",
    kind: "miracle",
    titleField: "title",
    bodyField: "body",
    categoryField: "category",
    statusField: "status",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    publishedField: "published_at",
    statusMap: { approved: "approved", pending: "pending" },
    publicRoute: () => `/miracles`,
  },
  fiqh_decision: {
    table: "fiqh_council_items",
    kind: "fiqh_decision",
    titleField: "title",
    summaryField: "summary",
    bodyField: "content",
    categoryField: "category",
    statusField: "status",
    slugField: "slug",
    externalKeyField: "external_id",
    publishedField: "published_at",
    archivedField: "archived_at",
    statusMap: {
      published: "published",
      pending: "needs_review",
      approved: "approved",
      draft: "draft",
      archived: "archived",
      rejected: "rejected",
    },
    publicRoute: (id: string) => `/fiqh-council/${id}`,
  },
  sharia_ruling: {
    table: "sharia_rulings",
    kind: "sharia_ruling",
    titleField: "title",
    summaryField: "summary",
    bodyField: "body",
    categoryField: "category",
    statusField: "status",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    publishedField: "published_at",
    statusMap: { approved: "approved", pending: "pending", archived: "archived" },
    publicRoute: (id) => `/rulings/${id}`,
  },
  annual_course: {
    table: "annual_courses",
    kind: "annual_course",
    titleField: "title",
    summaryField: "summary",
    bodyField: "body",
    categoryField: "course_type",
    statusField: "status",
    externalKeyField: "external_key",
    slugField: "slug",
    archivedField: "archived_at",
    publishedField: "published_at",
    statusMap: { approved: "approved", pending: "pending", archived: "archived" },
    publicRoute: (id) => `/annual-courses/${id}`,
  },
};

export function getContentConfig(kind: CmsContentKind): ContentTableConfig {
  return CONTENT_REGISTRY[kind];
}

export function kindFromLessonRow(row: { activity_type?: string; is_course?: boolean }): CmsContentKind {
  if (row.is_course || row.activity_type === "دورة") return "course";
  if (row.activity_type === "محاضرة") return "lecture";
  return "lesson";
}
