/**
 * قاعدة السجلات الموثّقة للأشهر والمناسبات — المصدر الوحيد المسموح لعرض
 * علاقات شهر/يوم ↔ حدث/عبادة. أي علاقة غير مسجّلة هنا تُرفض عند النشر.
 */
import type { VerifiedReligiousRecord } from "./types";

const REVIEWED = "2026-07-27";
const REVIEWER = "majlisilm-scholarly-editorial";

function rec(
  partial: Omit<VerifiedReligiousRecord, "reviewedBy" | "lastReviewedAt"> & {
    reviewedBy?: string;
    lastReviewedAt?: string;
  },
): VerifiedReligiousRecord {
  return {
    reviewedBy: REVIEWER,
    lastReviewedAt: REVIEWED,
    ...partial,
  };
}

/** الأشهر الهجرية الاثنا عشر — أوصاف دقيقة بلا اختراع روابط تاريخية */
export const VERIFIED_HIJRI_MONTH_CARDS: VerifiedReligiousRecord[] = [
  rec({
    id: "month-muharram",
    eventName: "محرّم",
    hijriMonth: 1,
    hijriDay: null,
    eventType: "sacred_month",
    contentKind: "verified_fact",
    verifiedDescription: "أول شهور السنة الهجرية، وأحد الأشهر الحرم.",
    recommendedActions: [
      "الإكثار من الصيام في شهر الله المحرّم",
      "العناية بصيام عاشوراء مع اليوم التاسع أو الحادي عشر",
    ],
    evidence:
      "«أفضل الصيام بعد رمضان شهرُ الله المحرَّم» رواه مسلم من حديث أبي هريرة رضي الله عنه. والأشهر الحرم ثابتة في الكتاب والسنة.",
    sourceName: "صحيح مسلم — كتاب الصيام",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat:
      "بداية العدّ الهجري من محرّم قرارٌ تقويمي في عهد عمر رضي الله عنه؛ وقدوم النبي ﷺ المدينة كان في ربيع الأول على المشهور، فلا تُنسب الهجرة وقوعًا إلى محرّم.",
    allowedMonthLinks: [1],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "month-safar",
    eventName: "صفر",
    hijriMonth: 2,
    hijriDay: null,
    eventType: "calendar_marker",
    contentKind: "verified_fact",
    verifiedDescription: "ثاني شهور السنة الهجرية، ولا يثبت له فضل خاص عن سائر الشهور.",
    recommendedActions: ["الاستمرار في الأوراد والصيام المشروع في أي شهر"],
    evidence: "«لا عدوى ولا طيرة ولا هامة ولا صفر» متفق عليه — نفي التشاؤم من صفر.",
    sourceName: "الصحيحان",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: "لا عبادة مخصوصة بشهر صفر.",
    allowedMonthLinks: [2],
    actionsAreRitualClaims: false,
  }),
  rec({
    id: "month-rabi-awwal",
    eventName: "ربيع الأول",
    hijriMonth: 3,
    hijriDay: null,
    eventType: "calendar_marker",
    contentKind: "historical_event",
    verifiedDescription:
      "ثالث الشهور الهجرية؛ وفيه على المشهور قدوم النبي ﷺ المدينة، وفيه وُلد ﷺ على اختلاف في تعيين اليوم.",
    recommendedActions: [
      "قراءة السيرة النبوية والشمائل",
      "الإكثار من الصلاة على النبي ﷺ في كل وقت دون تخصيص عبادة بيوم معيّن",
    ],
    evidence:
      "قدوم النبي ﷺ المدينة في ربيع الأول مشهور عند أهل السير. وصيام الاثنين لأنه يوم وُلد فيه ثابت في مسلم، دون إحداث احتفال.",
    sourceName: "كتب السيرة المحققة + صحيح مسلم",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "approximate",
    caveat: "تعيين يوم الولادة محل خلاف (اشتهر 12، ورجّح آخرون غيره).",
    allowedMonthLinks: [3],
    actionsAreRitualClaims: false,
  }),
  rec({
    id: "month-rabi-thani",
    eventName: "ربيع الآخر",
    hijriMonth: 4,
    hijriDay: null,
    eventType: "calendar_marker",
    contentKind: "verified_fact",
    verifiedDescription: "رابع الشهور الهجرية، ولا يثبت له فضل خاص عن سائر الشهور.",
    recommendedActions: ["المداومة على العمل الصالح المشروع في كل وقت"],
    evidence: "الأصل التسوية بين الشهور إلا ما خصّه الدليل.",
    sourceName: "قواعد أهل العلم في الفضائل",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: "لا عبادة مخصوصة بهذا الشهر.",
    allowedMonthLinks: [4],
    actionsAreRitualClaims: false,
  }),
  rec({
    id: "month-jumada-ula",
    eventName: "جمادى الأولى",
    hijriMonth: 5,
    hijriDay: null,
    eventType: "calendar_marker",
    contentKind: "verified_fact",
    verifiedDescription: "خامس الشهور الهجرية، ولا يثبت له فضل خاص عن سائر الشهور.",
    recommendedActions: ["المداومة على العمل الصالح المشروع في كل وقت"],
    evidence: "الأصل التسوية بين الشهور إلا ما خصّه الدليل.",
    sourceName: "قواعد أهل العلم في الفضائل",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: "لا عبادة مخصوصة بهذا الشهر.",
    allowedMonthLinks: [5],
    actionsAreRitualClaims: false,
  }),
  rec({
    id: "month-jumada-akhira",
    eventName: "جمادى الآخرة",
    hijriMonth: 6,
    hijriDay: null,
    eventType: "calendar_marker",
    contentKind: "verified_fact",
    verifiedDescription: "سادس الشهور الهجرية، ولا يثبت له فضل خاص عن سائر الشهور.",
    recommendedActions: ["المداومة على العمل الصالح المشروع في كل وقت"],
    evidence: "الأصل التسوية بين الشهور إلا ما خصّه الدليل.",
    sourceName: "قواعد أهل العلم في الفضائل",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: "لا عبادة مخصوصة بهذا الشهر.",
    allowedMonthLinks: [6],
    actionsAreRitualClaims: false,
  }),
  rec({
    id: "month-rajab",
    eventName: "رجب",
    hijriMonth: 7,
    hijriDay: null,
    eventType: "sacred_month",
    contentKind: "verified_fact",
    verifiedDescription: "أحد الأشهر الحرم الأربعة التي عظّمها الله.",
    recommendedActions: ["اجتناب المعاصي لعظم الوزر في الأشهر الحرم", "الإكثار من الاستغفار والعمل الصالح المشروع"],
    evidence: "قال تعالى: ﴿مِنْهَا أَرْبَعَةٌ حُرُمٌ﴾ — التوبة: 36، وحديث أبي بكرة في الأشهر الحرم متفق عليه.",
    sourceName: "القرآن الكريم + الصحيحان",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat:
      "تعيين ليلة الإسراء والمعراج بـ27 رجب لم يثبت بحديث صحيح؛ الحدث ثابت والليلة محل خلاف.",
    allowedMonthLinks: [7],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "month-shaban",
    eventName: "شعبان",
    hijriMonth: 8,
    hijriDay: null,
    eventType: "calendar_marker",
    contentKind: "recommended_deed",
    verifiedDescription: "شهر كان النبي ﷺ يكثر فيه من الصيام تطوعًا بين رجب ورمضان.",
    recommendedActions: ["الإكثار من صيام التطوع", "الاستعداد لرمضان بمراجعة القرآن"],
    evidence: "«كان أكثر صيامه في شعبان» في الصحيح.",
    sourceName: "صحيح البخاري",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: "تخصيص ليلة النصف من شعبان بقيام أو صيام معيّن محل خلاف ومنع عند جمع من المحققين.",
    allowedMonthLinks: [8],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "month-ramadan",
    eventName: "رمضان",
    hijriMonth: 9,
    hijriDay: null,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "شهر الصيام المفروض، وفيه نزل القرآن، وفيه تُلتمس ليلة القدر.",
    recommendedActions: ["صيام الفرض", "قيام الليل", "قراءة القرآن", "الصدقة"],
    evidence: "قال تعالى: ﴿شَهْرُ رَمَضَانَ الَّذِي أُنْزِلَ فِيهِ الْقُرْآنُ﴾ — البقرة: 185",
    sourceName: "القرآن الكريم",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [9],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "month-shawwal",
    eventName: "شوّال",
    hijriMonth: 10,
    hijriDay: null,
    eventType: "calendar_marker",
    contentKind: "recommended_deed",
    verifiedDescription: "عاشر الشهور؛ فيه عيد الفطر، ويُشرع فيه صيام ستٍ من شوّال.",
    recommendedActions: ["صيام ست من شوّال بعد يوم العيد"],
    evidence: "«من صام رمضان ثم أتبعه ستًا من شوّال كان كصيام الدهر» رواه مسلم.",
    sourceName: "صحيح مسلم",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [10],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "month-dhul-qadah",
    eventName: "ذو القعدة",
    hijriMonth: 11,
    hijriDay: null,
    eventType: "sacred_month",
    contentKind: "verified_fact",
    verifiedDescription: "أحد الأشهر الحرم، ومن أشهر الحج المعلومة.",
    recommendedActions: ["الاستعداد للحج لمن أراد", "اجتناب المعاصي لعظم الوزر في الأشهر الحرم"],
    evidence: "قال تعالى: ﴿الْحَجُّ أَشْهُرٌ مَعْلُومَاتٌ﴾ — البقرة: 197",
    sourceName: "القرآن الكريم",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [11],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "month-dhul-hijjah",
    eventName: "ذو الحجة",
    hijriMonth: 12,
    hijriDay: null,
    eventType: "sacred_month",
    contentKind: "recommended_deed",
    verifiedDescription: "أحد الأشهر الحرم؛ وأوائله العشر الأول أفضل أيام الدنيا عند الله.",
    recommendedActions: ["الإكثار من العمل الصالح في العشر", "صيام يوم عرفة لغير الحاج", "الأضحية لمن استطاع"],
    evidence: "«ما من أيام العمل الصالح فيها أحب إلى الله من هذه الأيام العشر» رواه البخاري.",
    sourceName: "صحيح البخاري",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [12],
    actionsAreRitualClaims: true,
  }),
];

/** أحداث ومناسبات موثّقة بعلاقات شهر صريحة — يمنع الاختراع اللغوي */
export const VERIFIED_OCCASION_RECORDS: VerifiedReligiousRecord[] = [
  rec({
    id: "hijra-anniversary",
    eventName: "ذكرى الهجرة النبوية",
    hijriMonth: 3,
    hijriDay: 12,
    eventType: "historical_event",
    contentKind: "historical_event",
    verifiedDescription:
      "قدِم النبي ﷺ المدينة في ربيع الأول من السنة الأولى للهجرة على المشهور. وجُعلت الهجرة مبدأً للتأريخ في عهد عمر رضي الله عنه، وبُدئ العدّ من محرّم تلك السنة لا من يوم القدوم.",
    recommendedActions: [
      "دراسة السيرة النبوية",
      "الصلاة على النبي ﷺ في كل وقت دون إحداث احتفال",
    ],
    evidence:
      "كتب السيرة المحققة في قدوم النبي ﷺ المدينة في ربيع الأول؛ وقرار التأريخ في عهد عمر رضي الله عنه.",
    sourceName: "السيرة النبوية المحققة + آثار الصحابة في التأريخ",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "approximate",
    caveat: "تعيين اليوم بالثاني عشر مشهور وليس قطعيًا عند كل أهل السير.",
    allowedMonthLinks: [3],
    actionsAreRitualClaims: false,
  }),
  rec({
    id: "hijri-new-year",
    eventName: "بداية السنة الهجرية",
    hijriMonth: 1,
    hijriDay: 1,
    eventType: "calendar_marker",
    contentKind: "verified_fact",
    verifiedDescription:
      "أول يوم من محرّم بداية العدّ السنوي في التقويم الهجري. وهو تذكير بالتوبة والعمل الصالح دون إحداث احتفال أو عبادة مخصوصة بهذا اليوم.",
    recommendedActions: ["التوبة والاستغفار المشروعان في كل وقت", "تجديد النية للعمل الصالح"],
    evidence:
      "بدء العدّ من محرّم قرار تقويمي في عهد عمر رضي الله عنه؛ وليس في الشرع عبادة مخصوصة بيوم رأس السنة الهجرية.",
    sourceName: "آثار الصحابة في التأريخ الهجري + قواعد البدع",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat:
      "لا تخلط بين «بداية التقويم الهجري» و«وقت وقوع الهجرة»؛ الهجرة قدومًا في ربيع الأول على المشهور.",
    allowedMonthLinks: [1],
    actionsAreRitualClaims: false,
  }),
  rec({
    id: "ashura",
    eventName: "يوم عاشوراء",
    hijriMonth: 1,
    hijriDay: 10,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "يوم عظيم يُستحب صيامه، ويُستحب صيام التاسع معه مخالفةً لأهل الكتاب.",
    recommendedActions: ["صيام عاشوراء", "صيام تاسوعاء معه إن تيسّر"],
    evidence:
      "«صيام يوم عاشوراء أحتسب على الله أن يكفّر السنة التي قبله» رواه مسلم، و«لئن بقيت إلى قابل لأصومنّ التاسع» رواه مسلم.",
    sourceName: "صحيح مسلم",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [1],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "muharram-fasting",
    eventName: "صيام المحرّم",
    hijriMonth: 1,
    hijriDay: 1,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "أفضل الصيام بعد رمضان صيام شهر الله المحرّم.",
    recommendedActions: ["الإكثار من صيام التطوع في محرّم"],
    evidence: "«أفضل الصيام بعد رمضان شهرُ الله المحرَّم» رواه مسلم.",
    sourceName: "صحيح مسلم",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [1],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "mawlid-annabawi",
    eventName: "المولد النبوي",
    hijriMonth: 3,
    hijriDay: 12,
    eventType: "disputed",
    contentKind: "historical_event",
    verifiedDescription:
      "وُلد النبي ﷺ في ربيع الأول عام الفيل، واختلف أهل السير في تعيين يومه. والصلاة عليه وقراءة سيرته مشروعتان في كل وقت من غير تخصيص عبادة بيوم معيّن.",
    recommendedActions: [
      "الإكثار من الصلاة على النبي ﷺ في كل وقت",
      "قراءة السيرة والاقتداء بها",
    ],
    evidence: "سُئل ﷺ عن صوم الاثنين فقال: «ذاك يومٌ وُلدت فيه» رواه مسلم — دون إحداث احتفال.",
    sourceName: "صحيح مسلم + كتب السيرة",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "disputed",
    dateCertainty: "disputed",
    caveat: "تعيين اليوم محل خلاف؛ ولا يُشرع إحداث احتفال لم يرد في السنة.",
    allowedMonthLinks: [3],
    actionsAreRitualClaims: false,
  }),
  rec({
    id: "isra-miraj",
    eventName: "الإسراء والمعراج",
    hijriMonth: 7,
    hijriDay: 27,
    eventType: "disputed",
    contentKind: "historical_event",
    verifiedDescription:
      "رحلة الإسراء والمعراج ثابتة بنص القرآن، وفيها فُرضت الصلوات. وتعيينها بليلة السابع والعشرين من رجب لم يثبت بحديث صحيح.",
    recommendedActions: [
      "قراءة خبر الإسراء من الكتاب والسنة",
      "شكر الله على نعمة الصلاة",
    ],
    evidence: "قال تعالى: ﴿سُبْحَانَ الَّذِي أَسْرَىٰ بِعَبْدِهِ لَيْلًا﴾ — الإسراء: 1",
    sourceName: "القرآن الكريم + كلام المحققين في عدم ثبوت تعيين الليلة",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "disputed",
    dateCertainty: "disputed",
    caveat: "ورد في بعض المصادر تعيين 27 رجب، وهو محل خلاف كبير؛ الحدث ثابت والليلة غير قطعية.",
    allowedMonthLinks: [7],
    actionsAreRitualClaims: false,
  }),
  rec({
    id: "laylat-alqadr",
    eventName: "ليلة القدر",
    hijriMonth: 9,
    hijriDay: 27,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription:
      "ليلة خير من ألف شهر؛ تُلتمس في العشر الأواخر من رمضان وأرجاها الأوتار، ولم تُعيَّن بيقين قاطع.",
    recommendedActions: ["الاجتهاد في العشر الأواخر كلها", "الدعاء والقيام وقراءة القرآن"],
    evidence: "سورة القدر، وحديث تحرّي ليلة القدر في وتر العشر الأواخر — متفق عليه.",
    sourceName: "القرآن الكريم + الصحيحان",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "disputed",
    caveat: "الأرجح عند كثيرين ليلة السابع والعشرين، واليقين غير قطعي.",
    allowedMonthLinks: [9],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "arafah",
    eventName: "يوم عرفة",
    hijriMonth: 12,
    hijriDay: 9,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "خير الدعاء دعاء يوم عرفة، وصيامه لغير الحاج يكفّر سنة ماضية وباقية.",
    recommendedActions: ["الدعاء", "صيام عرفة لغير الحاج"],
    evidence: "أحاديث يوم عرفة في مسلم والترمذي.",
    sourceName: "صحيح مسلم + سنن الترمذي",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [12],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "ramadan",
    eventName: "شهر رمضان",
    hijriMonth: 9,
    hijriDay: 1,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "شهر الصيام فرضًا، وفيه نزل القرآن، وفيه ليلة القدر.",
    recommendedActions: ["صيام الفرض", "قراءة القرآن", "قيام الليل", "الصدقة"],
    evidence: "قال تعالى: ﴿شَهْرُ رَمَضَانَ الَّذِي أُنْزِلَ فِيهِ الْقُرْآنُ﴾ — البقرة: 185",
    sourceName: "القرآن الكريم",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [9],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "eid-fitr",
    eventName: "عيد الفطر",
    hijriMonth: 10,
    hijriDay: 1,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "عيد الفطر بعد تمام صيام رمضان؛ تُشرع فيه صلاة العيد وزكاة الفطر.",
    recommendedActions: ["صلاة العيد", "إخراج زكاة الفطر", "صلة الأرحام"],
    evidence: "فرض رسول الله ﷺ زكاة الفطر — رواه البخاري.",
    sourceName: "صحيح البخاري",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [10],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "eid-adha",
    eventName: "عيد الأضحى",
    hijriMonth: 12,
    hijriDay: 10,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "عيد الأضحى ويوم الحج الأكبر؛ تُشرع فيه صلاة العيد والأضحية لمن استطاع.",
    recommendedActions: ["صلاة العيد", "الأضحية", "التكبير المشروع"],
    evidence: "قال تعالى: ﴿فَصَلِّ لِرَبِّكَ وَانْحَرْ﴾ — الكوثر: 2",
    sourceName: "القرآن الكريم",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [12],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "dhul-hijjah-ten",
    eventName: "عشر ذي الحجة",
    hijriMonth: 12,
    hijriDay: 1,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "أفضل أيام الدنيا؛ العمل الصالح فيها أحب إلى الله من سائر الأيام.",
    recommendedActions: ["الإكثار من التسبيح والتحميد والتهليل والتكبير", "الصيام والصدقة بقدر الاستطاعة"],
    evidence: "«ما من أيام العمل الصالح فيها أحب إلى الله من هذه الأيام العشر» رواه البخاري.",
    sourceName: "صحيح البخاري",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [12],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "white-days",
    eventName: "الأيام البيض",
    hijriMonth: 0,
    hijriDay: 13,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "يُستحب صيام ثلاثة أيام من كل شهر: الثالث عشر والرابع عشر والخامس عشر.",
    recommendedActions: ["صيام الأيام البيض"],
    evidence: "حديث أبي ذر في صيام 13 و14 و15 — حسّنه الألباني.",
    sourceName: "سنن الترمذي والنسائي",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: "أيام التشريق من ذي الحجة لا تُصام تطوعًا.",
    allowedMonthLinks: [],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "six-shawwal",
    eventName: "صيام ست شوّال",
    hijriMonth: 10,
    hijriDay: 2,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "صيام ست أيام من شوّال بعد رمضان يعدل صيام الدهر.",
    recommendedActions: ["صيام ست من شوّال بعد يوم العيد"],
    evidence: "«من صام رمضان ثم أتبعه ستًا من شوّال كان كصيام الدهر» رواه مسلم.",
    sourceName: "صحيح مسلم",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [10],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "monday-thursday-fasting",
    eventName: "صيام الاثنين والخميس",
    hijriMonth: 0,
    hijriDay: 0,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "يُستحب صيام يومي الاثنين والخميس؛ تُعرض فيهما الأعمال.",
    recommendedActions: ["صيام الاثنين", "صيام الخميس"],
    evidence: "حديث عرض الأعمال يوم الاثنين والخميس — الترمذي.",
    sourceName: "سنن الترمذي",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "friday-weekly",
    eventName: "يوم الجمعة",
    hijriMonth: 0,
    hijriDay: 0,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "أفضل أيام الأسبوع؛ فيه صلاة الجمعة وسننها الثابتة.",
    recommendedActions: ["صلاة الجمعة", "قراءة سورة الكهف", "الإكثار من الصلاة على النبي ﷺ"],
    evidence: "أحاديث فضل الجمعة في الصحيحين.",
    sourceName: "الصحيحان",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "last-ten-ramadan",
    eventName: "العشر الأواخر من رمضان",
    hijriMonth: 9,
    hijriDay: 21,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "فيها تُلتمس ليلة القدر؛ كان النبي ﷺ يحيي ليلها ويشدّ المئزر.",
    recommendedActions: ["قيام الليل", "الاعتكاف إن تيسّر", "الدعاء وقراءة القرآن"],
    evidence: "أحاديث إحياء العشر الأواخر في الصحيحين.",
    sourceName: "الصحيحان",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [9],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "days-tashriq",
    eventName: "أيام التشريق",
    hijriMonth: 12,
    hijriDay: 11,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "أيام 11 و12 و13 من ذي الحجة؛ أيام أكل وشرب وذكر لله.",
    recommendedActions: ["التكبير المشروع", "ذكر الله"],
    evidence: "«أيام التشريق أيام أكل وشرب وذكر الله» رواه مسلم.",
    sourceName: "صحيح مسلم",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [12],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "shaaban-entry",
    eventName: "دخول شهر شعبان",
    hijriMonth: 8,
    hijriDay: 1,
    eventType: "fixed_ritual",
    contentKind: "recommended_deed",
    verifiedDescription: "كان النبي ﷺ يكثر الصيام في شعبان استعدادًا لرمضان.",
    recommendedActions: ["الإكثار من صيام التطوع", "مراجعة القرآن"],
    evidence: "«كان أكثر صيامه في شعبان» في الصحيح.",
    sourceName: "صحيح البخاري",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [8],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "shaaban-fifteen",
    eventName: "ليلة النصف من شعبان",
    hijriMonth: 8,
    hijriDay: 15,
    eventType: "disputed",
    contentKind: "historical_event",
    verifiedDescription:
      "مسألة خلافية: بعضهم يصحّح أحاديث في فضلها بمجموع الطرق، وضعّفها آخرون، مع الاتفاق على عدم مشروعية تخصيصها بقيام أو صيام معيّن عند جمع من المحققين.",
    recommendedActions: ["الدعاء والاستغفار المشروعان في كل ليلة دون إحداث شعيرة خاصة"],
    evidence: "خلاف معتبر بين المصحّحين والمضعّفين؛ وفتاوى بعدم التخصيص.",
    sourceName: "كتب التخريج + فتاوى محققة",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "disputed",
    dateCertainty: "disputed",
    caveat: "محل خلاف؛ لا تُقدَّم كفضيلة قطعية ولا تُخصَّص بعبادة مخترعة.",
    allowedMonthLinks: [8],
    actionsAreRitualClaims: false,
  }),
  rec({
    id: "dhul-qadah-hajj-months",
    eventName: "شهر ذي القعدة",
    hijriMonth: 11,
    hijriDay: 1,
    eventType: "sacred_month",
    contentKind: "verified_fact",
    verifiedDescription: "أحد الأشهر الحرم، ومن أشهر الحج المعلومة.",
    recommendedActions: ["اجتناب المعاصي", "الاستعداد للحج لمن أراد"],
    evidence: "آية الأشهر الحرم وأشهر الحج.",
    sourceName: "القرآن الكريم + الصحيحان",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: null,
    allowedMonthLinks: [11],
    actionsAreRitualClaims: true,
  }),
  rec({
    id: "learning-season-muharram",
    eventName: "موسم التعلّم — محرّم",
    hijriMonth: 1,
    hijriDay: null,
    eventType: "personal_suggestion",
    contentKind: "personal_suggestion",
    verifiedDescription: "أول شهور السنة الهجرية، وأحد الأشهر الحرم.",
    recommendedActions: [
      "الإكثار من الصيام، والعناية بصيام عاشوراء مع اليوم التاسع أو الحادي عشر",
    ],
    evidence: "مستند إلى فضل صيام المحرّم وعاشوراء في صحيح مسلم — والاقتراح تنظيمي للتعلّم.",
    sourceName: "صحيح مسلم",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "certain",
    caveat: "الاقتراح تنظيمي شخصي للتعلّم. لا تُنسب الهجرة وقوعًا إلى محرّم؛ فقدوم النبي ﷺ المدينة في ربيع الأول على المشهور.",
    allowedMonthLinks: [1],
    actionsAreRitualClaims: false,
  }),
  rec({
    id: "learning-season-rabi-awwal",
    eventName: "موسم التعلّم — ربيع الأول",
    hijriMonth: 3,
    hijriDay: null,
    eventType: "personal_suggestion",
    contentKind: "personal_suggestion",
    verifiedDescription:
      "ربيع الأول؛ وفيه على المشهور قدوم النبي ﷺ المدينة، وفيه وُلد ﷺ على خلاف في اليوم.",
    recommendedActions: ["قراءة السيرة النبوية والشمائل المحمدية"],
    evidence: "كتب السيرة المحققة في قدوم المدينة في ربيع الأول.",
    sourceName: "السيرة النبوية المحققة",
    sourceUrl: null,
    reviewStatus: "approved",
    confidenceLevel: "high",
    dateCertainty: "approximate",
    caveat: "اقتراح تنظيمي للتعلّم؛ لا احتفال مخصوص بيوم.",
    allowedMonthLinks: [3],
    actionsAreRitualClaims: false,
  }),
];

/** علاقات محظورة صراحة — تُرفض مهما كان النص */
export const FORBIDDEN_TEMPORAL_LINKS: Array<{
  id: string;
  eventMarkers: RegExp;
  forbiddenMonths: number[];
  reason: string;
}> = [
  {
    id: "hijra-not-in-muharram",
    eventMarkers: /الهجرة|الهجرا|هجرة\s*النبي|قدوم.*(المدينة|يثرب)|قدِم.*(المدينة|يثرب)/,
    forbiddenMonths: [1],
    reason:
      "لا يجوز ربط وقوع الهجرة النبوية بشهر محرّم؛ القدوم على المشهور في ربيع الأول، ومحرّم بداية العدّ التقويمي فقط.",
  },
];

export const ALL_VERIFIED_RELIGIOUS_RECORDS: VerifiedReligiousRecord[] = [
  ...VERIFIED_HIJRI_MONTH_CARDS,
  ...VERIFIED_OCCASION_RECORDS,
];

export function getVerifiedRecordById(id: string): VerifiedReligiousRecord | undefined {
  return ALL_VERIFIED_RELIGIOUS_RECORDS.find((r) => r.id === id);
}

export function getVerifiedMonthCard(month: number): VerifiedReligiousRecord | undefined {
  return VERIFIED_HIJRI_MONTH_CARDS.find((r) => r.hijriMonth === month);
}
