export type AdhkarCategory = {
  id: string;
  name: string;
  slug: string;
  description: string;
};

export type AdhkarItem = {
  id: string;
  categoryId: string;
  text: string;
  count: number;
  narrator?: string;
  source?: string;
  grade?: string;
  reference?: string;
  keywords: string[];
};

export const ADHKAR_CATEGORIES: AdhkarCategory[] = [
  { id: "adh-morning", name: "أذكار الصباح", slug: "morning", description: "أذكار ما بعد الفجر إلى طلوع الشمس" },
  { id: "adh-evening", name: "أذكار المساء", slug: "evening", description: "أذكار ما بعد العصر إلى المغرب" },
  { id: "adh-sleep", name: "أذكار النوم", slug: "sleep", description: "ما يقال عند النوم" },
  { id: "adh-wakeup", name: "أذكار الاستيقاظ", slug: "wakeup", description: "ما يقال عند الاستيقاظ من النوم" },
  { id: "adh-home-in", name: "دخول المنزل", slug: "home-in", description: "دعاء دخول البيت" },
  { id: "adh-home-out", name: "الخروج من المنزل", slug: "home-out", description: "دعاء الخروج من البيت" },
  { id: "adh-mosque", name: "المسجد", slug: "mosque", description: "أذكار دخول المسجد والخروج منه" },
  { id: "adh-food", name: "الطعام", slug: "food", description: "أذكار قبل الطعام وبعده" },
  { id: "adh-travel", name: "السفر", slug: "travel", description: "أذكار السفر والركوب" },
  { id: "adh-wudu", name: "الوضوء", slug: "wudu", description: "ما يقال عند الوضوء" },
  { id: "adh-salah", name: "الصلاة", slug: "salah", description: "أذكار قبل الصلاة وبعدها" },
  { id: "adh-after-salah", name: "بعد الصلاة", slug: "after-salah", description: "أذكار ما بعد الصلوات المفروضة" },
  { id: "adh-distress", name: "الكرب", slug: "distress", description: "أدعية الكرب والهم" },
  { id: "adh-istikharah", name: "الاستخارة", slug: "istikharah", description: "دعاء الاستخارة" },
  { id: "adh-istighfar", name: "الاستغفار", slug: "istighfar", description: "أذكار الاستغفار والتوبة" },
  { id: "adh-rain", name: "المطر", slug: "rain", description: "ما يقال عند نزول المطر" },
  { id: "adh-wind", name: "الرياح", slug: "wind", description: "ما يقال عند هبوب الريح" },
  { id: "adh-market", name: "دخول السوق", slug: "market", description: "دعاء دخول السوق" },
  { id: "adh-clothing", name: "اللباس", slug: "clothing", description: "ما يقال عند لبس الثوب الجديد" },
  { id: "adh-vehicle", name: "ركوب السيارة", slug: "vehicle", description: "دعاء الركوب والسفر" },
  { id: "adh-misc", name: "أذكار متنوعة", slug: "misc", description: "أذكار نافعة متفرقة" },
];

export const ADHKAR_ITEMS: AdhkarItem[] = [
  {
    id: "adh-1",
    categoryId: "adh-morning",
    text: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    count: 1,
    narrator: "عبد الله بن مسعود",
    source: "رواه مسلم",
    grade: "صحيح",
    reference: "حصن المسلم — أذكار الصباح",
    keywords: ["صباح", "توحيد", "حمد"],
  },
  {
    id: "adh-2",
    categoryId: "adh-morning",
    text: "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ",
    count: 1,
    narrator: "أبو أيوب الأنصاري",
    source: "رواه الترمذي",
    grade: "حسن",
    reference: "حصن المسلم",
    keywords: ["صباح", "دعاء"],
  },
  {
    id: "adh-3",
    categoryId: "adh-morning",
    text: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    count: 100,
    narrator: "أبو هريرة",
    source: "رواه مسلم",
    grade: "صحيح",
    reference: "حصن المسلم",
    keywords: ["تسبيح", "صباح"],
  },
  {
    id: "adh-4",
    categoryId: "adh-evening",
    text: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
    count: 1,
    narrator: "عبد الله بن مسعود",
    source: "رواه مسلم",
    grade: "صحيح",
    reference: "حصن المسلم — أذكار المساء",
    keywords: ["مساء", "توحيد"],
  },
  {
    id: "adh-5",
    categoryId: "adh-evening",
    text: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    count: 3,
    narrator: "خولة بنت حكيم",
    source: "رواه مسلم",
    grade: "صحيح",
    reference: "حصن المسلم",
    keywords: ["مساء", "استعاذة"],
  },
  {
    id: "adh-6",
    categoryId: "adh-sleep",
    text: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    count: 1,
    narrator: "البراء بن عازب",
    source: "متفق عليه",
    grade: "صحيح",
    reference: "حصن المسلم",
    keywords: ["نوم", "دعاء"],
  },
  {
    id: "adh-7",
    categoryId: "adh-sleep",
    text: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
    count: 3,
    narrator: "شداد بن أوس",
    source: "رواه أبو داود والترمذي",
    grade: "حسن",
    reference: "حصن المسلم",
    keywords: ["نوم"],
  },
  {
    id: "adh-8",
    categoryId: "adh-wakeup",
    text: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    count: 1,
    narrator: "حديث حسن",
    source: "رواه البخاري",
    grade: "صحيح",
    reference: "حصن المسلم",
    keywords: ["استيقاظ", "حمد"],
  },
  {
    id: "adh-9",
    categoryId: "adh-home-in",
    text: "بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا",
    count: 1,
    narrator: "أنس بن مالك",
    source: "رواه أبو داود",
    grade: "حسن",
    reference: "حصن المسلم",
    keywords: ["منزل", "دخول"],
  },
  {
    id: "adh-10",
    categoryId: "adh-home-out",
    text: "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    count: 1,
    narrator: "أنس بن مالك",
    source: "رواه أبو داود والترمذي",
    grade: "حسن",
    reference: "حصن المسلم",
    keywords: ["منزل", "خروج"],
  },
  {
    id: "adh-11",
    categoryId: "adh-mosque",
    text: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    count: 1,
    narrator: "أبو هريرة",
    source: "رواه مسلم",
    grade: "صحيح",
    reference: "حصن المسلم — دخول المسجد",
    keywords: ["مسجد", "دخول"],
  },
  {
    id: "adh-12",
    categoryId: "adh-mosque",
    text: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    count: 1,
    narrator: "أبو هريرة",
    source: "رواه مسلم",
    grade: "صحيح",
    reference: "حصن المسلم — الخروج من المسجد",
    keywords: ["مسجد", "خروج"],
  },
  {
    id: "adh-13",
    categoryId: "adh-food",
    text: "بِسْمِ اللَّهِ",
    count: 1,
    narrator: "عمر بن أبي سلمة",
    source: "رواه البخاري ومسلم",
    grade: "صحيح",
    reference: "حصن المسلم",
    keywords: ["طعام", "بسم الله"],
  },
  {
    id: "adh-14",
    categoryId: "adh-food",
    text: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    count: 1,
    narrator: "معاذ بن أنس",
    source: "رواه أبو داود والترمذي",
    grade: "حسن",
    reference: "حصن المسلم",
    keywords: ["طعام", "حمد"],
  },
  {
    id: "adh-15",
    categoryId: "adh-travel",
    text: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ",
    count: 1,
    narrator: "عبد الله بن عمر",
    source: "رواه مسلم",
    grade: "صحيح",
    reference: "حصن المسلم",
    keywords: ["سفر", "ركوب"],
  },
  {
    id: "adh-16",
    categoryId: "adh-wudu",
    text: "بِسْمِ اللَّهِ",
    count: 1,
    narrator: "حديث عن النبي ﷺ",
    source: "رواه أبو داود والترمذي",
    grade: "حسن",
    reference: "حصن المسلم",
    keywords: ["وضوء"],
  },
  {
    id: "adh-17",
    categoryId: "adh-wudu",
    text: "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    count: 1,
    narrator: "عمر بن الخطاب",
    source: "رواه مسلم",
    grade: "صحيح",
    reference: "حصن المسلم — بعد الوضوء",
    keywords: ["وضوء", "شهادة"],
  },
  {
    id: "adh-18",
    categoryId: "adh-salah",
    text: "اللَّهُمَّ بَاعِدْ بَيْنِي وَبَيْنَ خَطَايَايَ كَمَا بَاعَدْتَ بَيْنَ الْمَشْرِقِ وَالْمَغْرِبِ",
    count: 1,
    narrator: "علي بن أبي طalib",
    source: "متفق عليه",
    grade: "صحيح",
    reference: "حصن المسلم — دعاء الاستفتاح",
    keywords: ["صلاة", "استفتاح"],
  },
  {
    id: "adh-19",
    categoryId: "adh-after-salah",
    text: "أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ",
    count: 3,
    narrator: "ثوبان",
    source: "رواه مسلم",
    grade: "صحيح",
    reference: "حصن المسلم",
    keywords: ["بعد الصلاة", "استغفار"],
  },
  {
    id: "adh-20",
    categoryId: "adh-after-salah",
    text: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    count: 33,
    narrator: "أبو هريرة",
    source: "متفق عليه",
    grade: "صحيح",
    reference: "حصن المسلم — التسبيح بعد الصلاة",
    keywords: ["بعد الصلاة", "تسبيح"],
  },
  {
    id: "adh-21",
    categoryId: "adh-distress",
    text: "لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
    count: 1,
    narrator: "سعد بن أبي وقاص",
    source: "رواه الترمذي",
    grade: "حسن",
    reference: "حصن المسلم — دعاء يونس",
    keywords: ["كرب", "هم"],
  },
  {
    id: "adh-22",
    categoryId: "adh-distress",
    text: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ",
    count: 1,
    narrator: "أنس بن مالك",
    source: "رواه البخاري",
    grade: "صحيح",
    reference: "حصن المسلم",
    keywords: ["كرب", "هم"],
  },
  {
    id: "adh-23",
    categoryId: "adh-istikharah",
    text: "اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ، وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ، وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ",
    count: 1,
    narrator: "جابر بن عبد الله",
    source: "رواه البخاري",
    grade: "صحيح",
    reference: "حصن المسلم — دعاء الاستخارة",
    keywords: ["استخارة"],
  },
  {
    id: "adh-24",
    categoryId: "adh-istighfar",
    text: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    count: 1,
    narrator: "أبو هريرة",
    source: "رواه أبو داود والترمذي",
    grade: "حسن",
    reference: "حصن المسلم",
    keywords: ["استغفار", "توبة"],
  },
  {
    id: "adh-25",
    categoryId: "adh-rain",
    text: "اللَّهُمَّ صَيِّبًا نَافِعًا",
    count: 1,
    narrator: "عائشة",
    source: "رواه البخاري",
    grade: "صحيح",
    reference: "حصن المسلم",
    keywords: ["مطر"],
  },
  {
    id: "adh-26",
    categoryId: "adh-wind",
    text: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا، وَخَيْرَ مَا فِيهَا، وَخَيْرَ مَا أُرْسِلَتْ بِهِ، وَأَعُوذُ بِكَ مِنْ شَرِّهَا",
    count: 1,
    narrator: "جابر بن عبد الله",
    source: "رواه مسلم",
    grade: "صحيح",
    reference: "حصن المسلم",
    keywords: ["رياح"],
  },
  {
    id: "adh-27",
    categoryId: "adh-market",
    text: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، يُحْيِي وَيُمِيتُ، وَهُوَ حَيٌّ لَا يَمُوتُ",
    count: 1,
    narrator: "عمر بن الخطاب",
    source: "رواه الترمذي",
    grade: "حسن",
    reference: "حصن المسلم",
    keywords: ["سوق"],
  },
  {
    id: "adh-28",
    categoryId: "adh-clothing",
    text: "الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    count: 1,
    narrator: "أبو سعيد الخدري",
    source: "رواه أبو داود والترمذي",
    grade: "حسن",
    reference: "حصن المسلم",
    keywords: ["لباس"],
  },
  {
    id: "adh-29",
    categoryId: "adh-vehicle",
    text: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ",
    count: 1,
    narrator: "عبد الله بن عمر",
    source: "رواه مسلم",
    grade: "صحيح",
    reference: "حصن المسلم",
    keywords: ["سيارة", "ركوب"],
  },
  {
    id: "adh-30",
    categoryId: "adh-misc",
    text: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    count: 1,
    narrator: "قرآن كريم",
    source: "سورة البقرة — 201",
    grade: "قرآن",
    reference: "القرآن الكريم",
    keywords: ["دعاء", "قرآن"],
  },
];

export function getAdhkarByCategory(categoryId: string): AdhkarItem[] {
  return ADHKAR_ITEMS.filter((a) => a.categoryId === categoryId);
}

export function filterAdhkar(search: string, categoryId?: string): AdhkarItem[] {
  const q = search.trim().toLowerCase();
  let items = ADHKAR_ITEMS;
  if (categoryId && categoryId !== "all") {
    items = items.filter((a) => a.categoryId === categoryId);
  }
  if (!q) return items;
  return items.filter(
    (a) =>
      a.text.includes(q) ||
      a.keywords.some((k) => k.includes(q)) ||
      a.source?.includes(q) ||
      a.reference?.includes(q),
  );
}
