import type { AnnualCourse } from "./platform-types";

export const ANNUAL_COURSES_SEED: AnnualCourse[] = [
  {
    id: "course-ijazah-tahrir-2026",
    external_key: "course-ijazah-tahrir-2026",
    title: "دورة الإجازة في التحرير — 1447هـ",
    summary: "دورة سنوية لإجازة طلاب العلم في متن التحرير في أصول الفقه.",
    body: `**عن الدورة:**
دورة علمية سنوية تُقام لإجازة طلاب العلم في متن «التحرير في أصول الفقه» للإمام ابن تيمية رحمه الله.

**المتون:**
- التحرير في أصول الفقه
- مختصر التحرير

**البرنامج:**
- دروس أسبوعية
- اختبارات شهرية
- مجلس إجازة في ختام الدورة`,
    course_type: "سنوية",
    season: "1447هـ",
    year: 2026,
    sheikh_names: ["د. عثمان الخميس", "د. سالم الطويل"],
    mutoon: ["التحرير في أصول الفقه", "مختصر التحرير"],
    schedule: [
      { day: "السبت", time: "بعد المغرب", topic: "شرح المتن", sheikh: "د. عثمان الخميس" },
      { day: "الثلاثاء", time: "بعد العشاء", topic: "مسائل تطبيقية", sheikh: "د. سالم الطويل" },
    ],
    venue_name: "مسجد الصحابة",
    venue_address: "الجابرية، شارع 10",
    venue_city: "الكويت",
    map_url: "https://maps.google.com/?q=مسجد+الصحابة+الكويت",
    registration_url: "/lessons?tab=courses",
    registration_open: true,
    start_date: "2026-01-15",
    end_date: "2026-12-20",
    keywords: ["إجازة", "تحرير", "أصول", "دورة"],
    status: "approved",
    view_count: 890,
    created_at: "2025-12-01T08:00:00Z",
  },
  {
    id: "course-ramadan-intensive",
    external_key: "course-ramadan-intensive",
    title: "البرنامج العلمي الرمضاني",
    summary: "برنامج موسمي يومي في رمضان — تفسير وحديث وفقه.",
    body: `**البرنامج الرمضاني:**
- تفسير جزء يومياً
- درس حديث بعد العصر
- فقه الصيام والتراويح`,
    course_type: "موسمية",
    season: "رمضان 1447",
    year: 2026,
    sheikh_names: ["د. راشد السليم", "د. منصور الخالدي"],
    mutoon: ["تفسير ابن كثير", "رياض الصالحين"],
    schedule: [
      { day: "يومياً", time: "بعد التراويح", topic: "تفسير", sheikh: "د. راشد السليم" },
      { day: "يومياً", time: "بعد العصر", topic: "حديث", sheikh: "د. منصور الخالدي" },
    ],
    venue_name: "مسجد الإمام مالك",
    venue_city: "الكويت",
    registration_open: true,
    start_date: "2026-02-28",
    end_date: "2026-03-29",
    keywords: ["رمضان", "تفسير", "برنامج"],
    status: "approved",
    view_count: 1200,
    created_at: "2025-11-15T07:00:00Z",
  },
  {
    id: "course-alfiqh-almuqaran",
    external_key: "course-alfiqh-almuqaran",
    title: "برنامج الفقه المقارن",
    summary: "برنامج علمي لمقارنة المذاهب في المسائل الفقهية المعاصرة.",
    course_type: "برنامج",
    season: "1446-1447",
    year: 2025,
    sheikh_names: ["د. حامد المسعد"],
    mutoon: ["الفقه المقارن"],
    venue_name: "مركز المجلس العلمي",
    venue_city: "الكويت",
    registration_open: false,
    keywords: ["فقه", "مقارن", "مذاهب"],
    status: "approved",
    view_count: 560,
    created_at: "2025-09-01T06:00:00Z",
  },
  {
    id: "mutoon-alfiyyah",
    external_key: "mutoon-alfiyyah",
    title: "متن الألفية في النحو",
    summary: "حلقة علمية لحفظ وشرح متن الألفية.",
    course_type: "متن",
    year: 2026,
    sheikh_names: ["د. أسامة الشاوي"],
    mutoon: ["ألفية ابن مالك"],
    schedule: [{ day: "الأحد", time: "بعد الفجر", topic: "حفظ وشرح", sheikh: "د. أسامة الشاوي" }],
    venue_city: "الكويت",
    registration_open: true,
    keywords: ["ألفية", "نحو", "متن"],
    status: "approved",
    view_count: 430,
    created_at: "2025-10-20T05:00:00Z",
  },
  {
    id: "course-aqeedah-tahawiyyah-2026",
    external_key: "course-aqeedah-tahawiyyah-2026",
    title: "شرح العقيدة الطحاوية — 1447هـ",
    summary: "دورة علمية في شرح متن الطحاوية مع بيان مسائل الأسماء والصفات.",
    body: `**عن الدورة:**
شرح تفصيلي لأهم متون العقيدة — العقيدة الطحاوية — مع الرد على الشبهات المعاصرة.

**المحاور:**
- أسماء الله وصفاته
- الإيمان وأركانه
- القضاء والقدر
- اليوم الآخر`,
    course_type: "سنوية",
    season: "1447هـ",
    year: 2026,
    sheikh_names: ["د. عبدالله الشثري"],
    mutoon: ["العقيدة الطحاوية", "شرح ابن أبي العز"],
    schedule: [
      { day: "الاثنين", time: "بعد العصر", topic: "متن الطحاوية", sheikh: "د. عبدالله الشثري" },
    ],
    venue_name: "مسجد ابن تيمية",
    venue_city: "الكويت",
    registration_open: true,
    start_date: "2026-02-01",
    end_date: "2026-11-30",
    keywords: ["عقيدة", "الطحاوية", "توحيد", "دورة"],
    status: "approved",
    view_count: 670,
    created_at: "2026-01-05T09:00:00Z",
  },
  {
    id: "course-hadith-arbain-nawawi-2026",
    external_key: "course-hadith-arbain-nawawi-2026",
    title: "شرح الأربعين النووية — 1447هـ",
    summary: "حلقة علمية في شرح أربعين حديثاً نووياً مع بيان فقهها وفوائدها.",
    course_type: "سنوية",
    season: "1447هـ",
    year: 2026,
    sheikh_names: ["د. فهد بن صالح العجلان"],
    mutoon: ["الأربعون النووية"],
    schedule: [
      { day: "الثلاثاء", time: "بعد المغرب", topic: "شرح الأربعين النووية", sheikh: "د. فهد العجلان" },
    ],
    venue_name: "مسجد الكويت الكبير",
    venue_city: "الكويت",
    registration_open: true,
    start_date: "2026-01-20",
    end_date: "2026-08-30",
    keywords: ["أربعين", "نووية", "حديث", "شرح"],
    status: "approved",
    view_count: 850,
    created_at: "2026-01-10T07:00:00Z",
  },
  {
    id: "course-tafsir-juz-amma",
    external_key: "course-tafsir-juz-amma",
    title: "تفسير جزء عمّ — الدورة الإثرائية",
    summary: "برنامج تفسيري متكامل لجزء عمّ مع ربط الآيات بالواقع المعاصر.",
    course_type: "برنامج",
    season: "صيف 1447",
    year: 2026,
    sheikh_names: ["د. ناصر بن سليمان العمر"],
    mutoon: ["تيسير الكريم الرحمن — السعدي"],
    schedule: [
      { day: "الجمعة", time: "بعد الفجر", topic: "تفسير", sheikh: "د. ناصر العمر" },
      { day: "السبت", time: "بعد العصر", topic: "تدبر وتطبيق", sheikh: "د. ناصر العمر" },
    ],
    venue_name: "مركز التعليم الإسلامي",
    venue_city: "الكويت",
    registration_open: true,
    start_date: "2026-06-15",
    end_date: "2026-08-15",
    keywords: ["تفسير", "جزء عمّ", "قرآن", "تدبر"],
    status: "approved",
    view_count: 540,
    created_at: "2026-05-01T06:00:00Z",
  },
  {
    id: "course-fiqh-ibadat",
    external_key: "course-fiqh-ibadat",
    title: "دورة الفقه في العبادات",
    summary: "دورة شاملة في أحكام الطهارة والصلاة والصيام والزكاة والحج.",
    course_type: "سنوية",
    season: "1447هـ",
    year: 2026,
    sheikh_names: ["د. يوسف الشبيلي", "د. عبدالله المطلق"],
    mutoon: ["زاد المستقنع", "الروض المربع"],
    schedule: [
      { day: "الأربعاء", time: "بعد العشاء", topic: "الفقه العملي", sheikh: "د. يوسف الشبيلي" },
    ],
    venue_name: "المجلس العلمي",
    venue_city: "الكويت",
    registration_open: true,
    start_date: "2026-01-01",
    end_date: "2026-12-31",
    keywords: ["فقه", "عبادات", "طهارة", "صلاة", "صيام"],
    status: "approved",
    view_count: 1100,
    created_at: "2025-12-25T08:00:00Z",
  },
  {
    id: "course-arabic-beginner",
    external_key: "course-arabic-beginner",
    title: "اللغة العربية للمبتدئين — النحو والصرف",
    summary: "دورة تأسيسية في علم النحو والصرف لطلاب العلم الشرعي.",
    course_type: "برنامج",
    season: "1447هـ",
    year: 2026,
    sheikh_names: ["أ. محمد الخالدي"],
    mutoon: ["متن الآجرومية", "التحفة السنية"],
    schedule: [
      { day: "الخميس", time: "بعد المغرب", topic: "النحو والصرف", sheikh: "أ. محمد الخالدي" },
    ],
    venue_name: "مركز الدراسات الإسلامية",
    venue_city: "الكويت",
    registration_open: true,
    start_date: "2026-02-10",
    end_date: "2026-06-30",
    keywords: ["نحو", "صرف", "عربية", "آجرومية", "مبتدئ"],
    status: "approved",
    view_count: 320,
    created_at: "2026-01-20T05:00:00Z",
  },
  {
    id: "course-seerah-nabawiyyah",
    external_key: "course-seerah-nabawiyyah",
    title: "السيرة النبوية المفصّلة",
    summary: "دراسة تحليلية شاملة لسيرة النبي ﷺ منذ المولد حتى الوفاة.",
    course_type: "سنوية",
    season: "1447هـ",
    year: 2026,
    sheikh_names: ["د. أكرم ضياء العمري"],
    mutoon: ["الرحيق المختوم", "السيرة النبوية — ابن هشام"],
    schedule: [
      { day: "السبت", time: "بعد الظهر", topic: "السيرة", sheikh: "د. أكرم العمري" },
    ],
    venue_name: "مركز الدراسات الإسلامية",
    venue_city: "الكويت",
    registration_open: false,
    start_date: "2026-03-01",
    end_date: "2027-02-28",
    keywords: ["سيرة", "نبوية", "تاريخ", "مولد"],
    status: "approved",
    view_count: 780,
    created_at: "2026-02-15T06:00:00Z",
  },
  {
    id: "course-uloom-hadith",
    external_key: "course-uloom-hadith",
    title: "مقدمة في علوم الحديث",
    summary: "دورة تأسيسية في مصطلح الحديث ودراسة الأسانيد والمتون.",
    course_type: "برنامج",
    season: "صيف 1447",
    year: 2026,
    sheikh_names: ["د. حاتم بن عارف العوني"],
    mutoon: ["نخبة الفكر", "نزهة النظر"],
    schedule: [
      { day: "الثلاثاء", time: "بعد العشاء", topic: "مصطلح الحديث", sheikh: "د. حاتم العوني" },
    ],
    venue_name: "مسجد الإمام أحمد",
    venue_city: "الكويت",
    registration_open: true,
    start_date: "2026-06-20",
    end_date: "2026-09-20",
    keywords: ["مصطلح الحديث", "أسانيد", "علوم الحديث"],
    status: "approved",
    view_count: 460,
    created_at: "2026-05-10T07:00:00Z",
  },
];

export function findAnnualCourseById(id: string) {
  return ANNUAL_COURSES_SEED.find((c) => c.id === id || c.external_key === id) || null;
}
