// Auto-generated by scripts/generate-content-seed.mjs — do not edit manually
import { arabicMatchAny } from "./arabic-search";

export const FAWAID_CATEGORIES = [
  "فوائد قرآنية",
  "فوائد حديثية",
  "فوائد عقدية",
  "فوائد فقهية",
  "فوائد تربوية",
  "فوائد دعوية",
  "آداب وأخلاق"
] as const;

export const SEED_FAWAID = [
  {
    "id": "seed-fawaid-1",
    "text": "فائدة: نوح عليه السلام — من أول الرسل إلى أهل الأرض بعد آدم؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-2",
    "text": "فائدة: إبراهيم عليه السلام — من النبي الذي اتخذه الله خليلاً؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-3",
    "text": "فائدة: موسى عليه السلام — من النبي الذي كلمه الله تكليماً؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-4",
    "text": "فائدة: هود عليه السلام — من النبي الذي أرسل إلى قوم عاد؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-5",
    "text": "فائدة: صالح عليه السلام — من النبي الذي أرسل إلى قوم ثمود؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-6",
    "text": "فائدة: يونس عليه السلام — من النبي الذي ابتلعه الحوت؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-7",
    "text": "فائدة: عيسى عليه السلام — من النبي الذي رفعه الله إليه؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-8",
    "text": "فائدة: إبراهيم عليه السلام — من والد إسماعيل عليه السلام؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-9",
    "text": "فائدة: سليمان عليه السلام — من النبي الذي سخر الله له الريح؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-10",
    "text": "فائدة: أيوب عليه السلام — من النبي الذي اشتهر بالصبر على البلاء؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-11",
    "text": "فائدة: أبو بكر الصديق — من أول الخلفاء الراشدين؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-12",
    "text": "فائدة: عمر بن الخطاب — من ثاني الخلفاء الراشدين؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-13",
    "text": "فائدة: عثمان بن عفان — من ثالث الخلفاء الراشدين؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-14",
    "text": "فائدة: علي بن أبي طالب — من رابع الخلفاء الراشدين؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-15",
    "text": "فائدة: عثمان بن عفان — من الصحابي الملقب بذي النورين؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-16",
    "text": "فائدة: عمر بن الخطاب — من الصحابي الملقب بالفاروق؟",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-17",
    "text": "فائدة: نوح عليه السلام — من أول الرسل إلى أهل الأرض بعد آدم؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-18",
    "text": "فائدة: إبراهيم عليه السلام — من النبي الذي اتخذه الله خليلاً؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-19",
    "text": "فائدة: موسى عليه السلام — من النبي الذي كلمه الله تكليماً؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-20",
    "text": "فائدة: هود عليه السلام — من النبي الذي أرسل إلى قوم عاد؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-21",
    "text": "فائدة: صالح عليه السلام — من النبي الذي أرسل إلى قوم ثمود؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-22",
    "text": "فائدة: يونس عليه السلام — من النبي الذي ابتلعه الحوت؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-23",
    "text": "فائدة: عيسى عليه السلام — من النبي الذي رفعه الله إليه؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-24",
    "text": "فائدة: إبراهيم عليه السلام — من والد إسماعيل عليه السلام؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-25",
    "text": "فائدة: سليمان عليه السلام — من النبي الذي سخر الله له الريح؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-26",
    "text": "فائدة: أيوب عليه السلام — من النبي الذي اشتهر بالصبر على البلاء؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-27",
    "text": "فائدة: أبو بكر الصديق — من أول الخلفاء الراشدين؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-28",
    "text": "فائدة: عمر بن الخطاب — من ثاني الخلفاء الراشدين؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-29",
    "text": "فائدة: عثمان بن عفان — من ثالث الخلفاء الراشدين؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-30",
    "text": "فائدة: علي بن أبي طالب — من رابع الخلفاء الراشدين؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-31",
    "text": "فائدة: عثمان بن عفان — من الصحابي الملقب بذي النورين؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-32",
    "text": "فائدة: عمر بن الخطاب — من الصحابي الملقب بالفاروق؟",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-33",
    "text": "فائدة: إبراهيم عليه السلام — من النبي الذي اتخذه الله خليلاً؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-34",
    "text": "فائدة: موسى عليه السلام — من النبي الذي كلمه الله تكليماً؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-35",
    "text": "فائدة: عيسى عليه السلام — من النبي الذي رفعه الله إليه؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-36",
    "text": "فائدة: سليمان عليه السلام — من النبي الذي سخر الله له الريح؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-37",
    "text": "فائدة: عائشة رضي الله عنها — من أم المؤمنين ابنة أبي بكر؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-38",
    "text": "فائدة: المدينة المنورة — إلى أي مدينة هاجر النبي صلى الله عليه وسلم؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-39",
    "text": "فائدة: أبو بكر الصديق — من صاحب النبي صلى الله عليه وسلم في الهجرة؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-40",
    "text": "فائدة: مسجد قباء — ما أول مسجد أسسه النبي صلى الله عليه وسلم بعد الهجرة؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-41",
    "text": "فائدة: صلح الحديبية — ما اسم الصلح الذي عقده النبي صلى الله عليه وسلم مع قريش؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-42",
    "text": "فائدة: فتح مكة — ما الحدث الذي دخل فيه النبي صلى الله عليه وسلم مكة فاتحاً؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-43",
    "text": "فائدة: عبد الله بن عباس — من الصحابي المشهور بتفسير القرآن؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-44",
    "text": "فائدة: نوح عليه السلام — من أول الرسل إلى أهل الأرض بعد آدم؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-45",
    "text": "فائدة: هود عليه السلام — من النبي الذي أرسل إلى قوم عاد؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-46",
    "text": "فائدة: صالح عليه السلام — من النبي الذي أرسل إلى قوم ثمود؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-47",
    "text": "فائدة: يونس عليه السلام — من النبي الذي ابتلعه الحوت؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-48",
    "text": "فائدة: إبراهيم عليه السلام — من والد إسماعيل عليه السلام؟",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-49",
    "text": "فائدة: الزكاة — ما العبادة المالية الواجبة على المال بشروطها؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-50",
    "text": "فائدة: نوح عليه السلام — من أول الرسل إلى أهل الأرض بعد آدم؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-51",
    "text": "فائدة: إبراهيم عليه السلام — من النبي الذي اتخذه الله خليلاً؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-52",
    "text": "فائدة: موسى عليه السلام — من النبي الذي كلمه الله تكليماً؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-53",
    "text": "فائدة: هود عليه السلام — من النبي الذي أرسل إلى قوم عاد؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-54",
    "text": "فائدة: صالح عليه السلام — من النبي الذي أرسل إلى قوم ثمود؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-55",
    "text": "فائدة: يونس عليه السلام — من النبي الذي ابتلعه الحوت؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-56",
    "text": "فائدة: عيسى عليه السلام — من النبي الذي رفعه الله إليه؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-57",
    "text": "فائدة: إبراهيم عليه السلام — من والد إسماعيل عليه السلام؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-58",
    "text": "فائدة: سليمان عليه السلام — من النبي الذي سخر الله له الريح؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-59",
    "text": "فائدة: أيوب عليه السلام — من النبي الذي اشتهر بالصبر على البلاء؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-60",
    "text": "فائدة: أبو بكر الصديق — من أول الخلفاء الراشدين؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-61",
    "text": "فائدة: عمر بن الخطاب — من ثاني الخلفاء الراشدين؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-62",
    "text": "فائدة: عثمان بن عفان — من ثالث الخلفاء الراشدين؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-63",
    "text": "فائدة: علي بن أبي طالب — من رابع الخلفاء الراشدين؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-64",
    "text": "فائدة: عثمان بن عفان — من الصحابي الملقب بذي النورين؟",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-65",
    "text": "فائدة: نوح عليه السلام — من أول الرسل إلى أهل الأرض بعد آدم؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-66",
    "text": "فائدة: إبراهيم عليه السلام — من النبي الذي اتخذه الله خليلاً؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-67",
    "text": "فائدة: موسى عليه السلام — من النبي الذي كلمه الله تكليماً؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-68",
    "text": "فائدة: هود عليه السلام — من النبي الذي أرسل إلى قوم عاد؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-69",
    "text": "فائدة: صالح عليه السلام — من النبي الذي أرسل إلى قوم ثمود؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-70",
    "text": "فائدة: يونس عليه السلام — من النبي الذي ابتلعه الحوت؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-71",
    "text": "فائدة: عيسى عليه السلام — من النبي الذي رفعه الله إليه؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-72",
    "text": "فائدة: إبراهيم عليه السلام — من والد إسماعيل عليه السلام؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-73",
    "text": "فائدة: سليمان عليه السلام — من النبي الذي سخر الله له الريح؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-74",
    "text": "فائدة: أيوب عليه السلام — من النبي الذي اشتهر بالصبر على البلاء؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-75",
    "text": "فائدة: أبو بكر الصديق — من أول الخلفاء الراشدين؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-76",
    "text": "فائدة: عمر بن الخطاب — من ثاني الخلفاء الراشدين؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-77",
    "text": "فائدة: عثمان بن عفان — من ثالث الخلفاء الراشدين؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-78",
    "text": "فائدة: علي بن أبي طالب — من رابع الخلفاء الراشدين؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-79",
    "text": "فائدة: عثمان بن عفان — من الصحابي الملقب بذي النورين؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-80",
    "text": "فائدة: عمر بن الخطاب — من الصحابي الملقب بالفاروق؟",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-81",
    "text": "فائدة: نوح عليه السلام — من أول الرسل إلى أهل الأرض بعد آدم؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-82",
    "text": "فائدة: إبراهيم عليه السلام — من النبي الذي اتخذه الله خليلاً؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-83",
    "text": "فائدة: موسى عليه السلام — من النبي الذي كلمه الله تكليماً؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-84",
    "text": "فائدة: هود عليه السلام — من النبي الذي أرسل إلى قوم عاد؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-85",
    "text": "فائدة: صالح عليه السلام — من النبي الذي أرسل إلى قوم ثمود؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-86",
    "text": "فائدة: يونس عليه السلام — من النبي الذي ابتلعه الحوت؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-87",
    "text": "فائدة: عيسى عليه السلام — من النبي الذي رفعه الله إليه؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-88",
    "text": "فائدة: إبراهيم عليه السلام — من والد إسماعيل عليه السلام؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-89",
    "text": "فائدة: سليمان عليه السلام — من النبي الذي سخر الله له الريح؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-90",
    "text": "فائدة: أيوب عليه السلام — من النبي الذي اشتهر بالصبر على البلاء؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-91",
    "text": "فائدة: أبو بكر الصديق — من أول الخلفاء الراشدين؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-92",
    "text": "فائدة: عمر بن الخطاب — من ثاني الخلفاء الراشدين؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-93",
    "text": "فائدة: عثمان بن عفان — من ثالث الخلفاء الراشدين؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-94",
    "text": "فائدة: علي بن أبي طالب — من رابع الخلفاء الراشدين؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-95",
    "text": "فائدة: عثمان بن عفان — من الصحابي الملقب بذي النورين؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-96",
    "text": "فائدة: عمر بن الخطاب — من الصحابي الملقب بالفاروق؟",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-97",
    "text": "فائدة: نوح عليه السلام — من أول الرسل إلى أهل الأرض بعد آدم؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-98",
    "text": "فائدة: إبراهيم عليه السلام — من النبي الذي اتخذه الله خليلاً؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-99",
    "text": "فائدة: موسى عليه السلام — من النبي الذي كلمه الله تكليماً؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-100",
    "text": "فائدة: هود عليه السلام — من النبي الذي أرسل إلى قوم عاد؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-101",
    "text": "فائدة: صالح عليه السلام — من النبي الذي أرسل إلى قوم ثمود؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-102",
    "text": "فائدة: يونس عليه السلام — من النبي الذي ابتلعه الحوت؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-103",
    "text": "فائدة: عيسى عليه السلام — من النبي الذي رفعه الله إليه؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-104",
    "text": "فائدة: إبراهيم عليه السلام — من والد إسماعيل عليه السلام؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-105",
    "text": "فائدة: سليمان عليه السلام — من النبي الذي سخر الله له الريح؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-106",
    "text": "فائدة: أيوب عليه السلام — من النبي الذي اشتهر بالصبر على البلاء؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-107",
    "text": "فائدة: أبو بكر الصديق — من أول الخلفاء الراشدين؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-108",
    "text": "فائدة: عمر بن الخطاب — من ثاني الخلفاء الراشدين؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-109",
    "text": "فائدة: عثمان بن عفان — من ثالث الخلفاء الراشدين؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-110",
    "text": "فائدة: علي بن أبي طالب — من رابع الخلفاء الراشدين؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-111",
    "text": "فائدة: عثمان بن عفان — من الصحابي الملقب بذي النورين؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-112",
    "text": "فائدة: عمر بن الخطاب — من الصحابي الملقب بالفاروق؟",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": null,
    "status": "approved"
  }
];

export function filterSeedFawaid({
  category,
  search,
}: {
  category?: string;
  search?: string;
}) {
  let items = SEED_FAWAID.filter((f) => f.status === "approved");
  if (category && category !== "all") {
    items = items.filter((f) => f.category === category);
  }
  if (search?.trim()) {
    const s = search.trim();
    items = items.filter((f) => arabicMatchAny([f.text, f.author_name, f.source], s));
  }
  return items;
}
