// Auto-generated by scripts/generate-content-seed.mjs — do not edit manually
import { arabicMatchAny } from "./arabic-search";

export const FAWAID_CATEGORIES = [
  "فوائد قرآنية",
  "فوائد حديثية",
  "فوائد عقدية",
  "فوائد فقهية",
  "فوائد تربوية",
  "فوائد دعوية",
  "آداب وأخلاق"
] as const;

export const SEED_FAWAID = [
  {
    "id": "seed-fawaid-1",
    "text": "تدبر آيات الرحمة يورث القلب توقير الله وخوفاً من معصيته.",
    "category": "فوائد قرآنية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-2",
    "text": "من فوائد قراءة القرآن: هداية القلب وطمأنينة النفس ونور البصيرة.",
    "category": "فوائد قرآنية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-3",
    "text": "المواظبة على ورد قرآني يثبت اللسان على ذكر الله ويحفظ العهد مع كتاب رب العالمين.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-4",
    "text": "المواظبة على الأذكار المأثورة تحفظ العبد من الغفلة وتربط القلب بالله.",
    "category": "فوائد قرآنية",
    "source": "السنة النبوية",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-5",
    "text": "من فوائد اتباع السنة: استقامة السلوك وبركة الوقت وقبول العمل.",
    "category": "فوائد قرآنية",
    "source": "السنة",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-6",
    "text": "حفظ الأحاديث الصحيحة يقوي المعرفة بالدين ويصون المسلم من الضلال.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "فائدة علمية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-7",
    "text": "معرفة توحيد الله أساس قبول الأعمال وصيانة القلب من الشرك الخفي.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-8",
    "text": "الإخلاص لله وحده يجعل العبادة خالصة مقبولة عند رب العالمين.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-9",
    "text": "تعلم أحكام الطهارة والصلاة يحفظ العبادة من البطلان ويرفع الخشوع.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-10",
    "text": "معرفة الحلال والحرام تحمي المسلم من الوقوع في المحرمات وتيسر المعاملات.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-11",
    "text": "الصحبة الصالحة تذكّر بالآخرة وتدفع إلى طاعة الله وترك المعاصي.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-12",
    "text": "حسن الخلق من أعظم ما يقرب العبد إلى الله ويرفع مكانته عند الناس.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-13",
    "text": "التواضع للعلماء والاستفادة من مجالس العلم يورث حلاوة الإيمان.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-14",
    "text": "الدعوة بالحكمة والموعظة الحسنة أقرب إلى القبول وأبعد عن التنفير.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-15",
    "text": "قدوة المسلم في سلوكه أبلغ من كثير من الكلام في تأثير الدعوة.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-16",
    "text": "بر الوالدين من أعظم أبواب الخير وسبب لبركة العمر والرزق.",
    "category": "فوائد قرآنية",
    "source": null,
    "author_name": "آداب",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-17",
    "text": "المواظبة على الأذكار المأثورة تحفظ العبد من الغفلة وتربط القلب بالله.",
    "category": "فوائد حديثية",
    "source": "السنة النبوية",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-18",
    "text": "من فوائد اتباع السنة: استقامة السلوك وبركة الوقت وقبول العمل.",
    "category": "فوائد حديثية",
    "source": "السنة",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-19",
    "text": "حفظ الأحاديث الصحيحة يقوي المعرفة بالدين ويصون المسلم من الضلال.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "فائدة علمية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-20",
    "text": "تدبر آيات الرحمة يورث القلب توقير الله وخوفاً من معصيته.",
    "category": "فوائد حديثية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-21",
    "text": "من فوائد قراءة القرآن: هداية القلب وطمأنينة النفس ونور البصيرة.",
    "category": "فوائد حديثية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-22",
    "text": "المواظبة على ورد قرآني يثبت اللسان على ذكر الله ويحفظ العهد مع كتاب رب العالمين.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-23",
    "text": "معرفة توحيد الله أساس قبول الأعمال وصيانة القلب من الشرك الخفي.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-24",
    "text": "الإخلاص لله وحده يجعل العبادة خالصة مقبولة عند رب العالمين.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-25",
    "text": "تعلم أحكام الطهارة والصلاة يحفظ العبادة من البطلان ويرفع الخشوع.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-26",
    "text": "معرفة الحلال والحرام تحمي المسلم من الوقوع في المحرمات وتيسر المعاملات.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-27",
    "text": "الصحبة الصالحة تذكّر بالآخرة وتدفع إلى طاعة الله وترك المعاصي.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-28",
    "text": "حسن الخلق من أعظم ما يقرب العبد إلى الله ويرفع مكانته عند الناس.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-29",
    "text": "التواضع للعلماء والاستفادة من مجالس العلم يورث حلاوة الإيمان.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-30",
    "text": "الدعوة بالحكمة والموعظة الحسنة أقرب إلى القبول وأبعد عن التنفير.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-31",
    "text": "قدوة المسلم في سلوكه أبلغ من كثير من الكلام في تأثير الدعوة.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-32",
    "text": "بر الوالدين من أعظم أبواب الخير وسبب لبركة العمر والرزق.",
    "category": "فوائد حديثية",
    "source": null,
    "author_name": "آداب",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-33",
    "text": "معرفة توحيد الله أساس قبول الأعمال وصيانة القلب من الشرك الخفي.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-34",
    "text": "الإخلاص لله وحده يجعل العبادة خالصة مقبولة عند رب العالمين.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-35",
    "text": "تدبر آيات الرحمة يورث القلب توقير الله وخوفاً من معصيته.",
    "category": "فوائد عقدية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-36",
    "text": "المواظبة على ورد قرآني يثبت اللسان على ذكر الله ويحفظ العهد مع كتاب رب العالمين.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-37",
    "text": "المواظبة على الأذكار المأثورة تحفظ العبد من الغفلة وتربط القلب بالله.",
    "category": "فوائد عقدية",
    "source": "السنة النبوية",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-38",
    "text": "الصحبة الصالحة تذكّر بالآخرة وتدفع إلى طاعة الله وترك المعاصي.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-39",
    "text": "حسن الخلق من أعظم ما يقرب العبد إلى الله ويرفع مكانته عند الناس.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-40",
    "text": "من فوائد قراءة القرآن: هداية القلب وطمأنينة النفس ونور البصيرة.",
    "category": "فوائد عقدية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-41",
    "text": "من فوائد اتباع السنة: استقامة السلوك وبركة الوقت وقبول العمل.",
    "category": "فوائد عقدية",
    "source": "السنة",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-42",
    "text": "حفظ الأحاديث الصحيحة يقوي المعرفة بالدين ويصون المسلم من الضلال.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "فائدة علمية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-43",
    "text": "تعلم أحكام الطهارة والصلاة يحفظ العبادة من البطلان ويرفع الخشوع.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-44",
    "text": "معرفة الحلال والحرام تحمي المسلم من الوقوع في المحرمات وتيسر المعاملات.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-45",
    "text": "التواضع للعلماء والاستفادة من مجالس العلم يورث حلاوة الإيمان.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-46",
    "text": "الدعوة بالحكمة والموعظة الحسنة أقرب إلى القبول وأبعد عن التنفير.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-47",
    "text": "قدوة المسلم في سلوكه أبلغ من كثير من الكلام في تأثير الدعوة.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-48",
    "text": "بر الوالدين من أعظم أبواب الخير وسبب لبركة العمر والرزق.",
    "category": "فوائد عقدية",
    "source": null,
    "author_name": "آداب",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-49",
    "text": "تعلم أحكام الطهارة والصلاة يحفظ العبادة من البطلان ويرفع الخشوع.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-50",
    "text": "معرفة الحلال والحرام تحمي المسلم من الوقوع في المحرمات وتيسر المعاملات.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-51",
    "text": "تدبر آيات الرحمة يورث القلب توقير الله وخوفاً من معصيته.",
    "category": "فوائد فقهية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-52",
    "text": "من فوائد قراءة القرآن: هداية القلب وطمأنينة النفس ونور البصيرة.",
    "category": "فوائد فقهية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-53",
    "text": "المواظبة على ورد قرآني يثبت اللسان على ذكر الله ويحفظ العهد مع كتاب رب العالمين.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-54",
    "text": "المواظبة على الأذكار المأثورة تحفظ العبد من الغفلة وتربط القلب بالله.",
    "category": "فوائد فقهية",
    "source": "السنة النبوية",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-55",
    "text": "من فوائد اتباع السنة: استقامة السلوك وبركة الوقت وقبول العمل.",
    "category": "فوائد فقهية",
    "source": "السنة",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-56",
    "text": "حفظ الأحاديث الصحيحة يقوي المعرفة بالدين ويصون المسلم من الضلال.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "فائدة علمية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-57",
    "text": "معرفة توحيد الله أساس قبول الأعمال وصيانة القلب من الشرك الخفي.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-58",
    "text": "الإخلاص لله وحده يجعل العبادة خالصة مقبولة عند رب العالمين.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-59",
    "text": "الصحبة الصالحة تذكّر بالآخرة وتدفع إلى طاعة الله وترك المعاصي.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-60",
    "text": "حسن الخلق من أعظم ما يقرب العبد إلى الله ويرفع مكانته عند الناس.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-61",
    "text": "التواضع للعلماء والاستفادة من مجالس العلم يورث حلاوة الإيمان.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-62",
    "text": "الدعوة بالحكمة والموعظة الحسنة أقرب إلى القبول وأبعد عن التنفير.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-63",
    "text": "قدوة المسلم في سلوكه أبلغ من كثير من الكلام في تأثير الدعوة.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-64",
    "text": "بر الوالدين من أعظم أبواب الخير وسبب لبركة العمر والرزق.",
    "category": "فوائد فقهية",
    "source": null,
    "author_name": "آداب",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-65",
    "text": "الصحبة الصالحة تذكّر بالآخرة وتدفع إلى طاعة الله وترك المعاصي.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-66",
    "text": "حسن الخلق من أعظم ما يقرب العبد إلى الله ويرفع مكانته عند الناس.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-67",
    "text": "التواضع للعلماء والاستفادة من مجالس العلم يورث حلاوة الإيمان.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-68",
    "text": "تعلم أحكام الطهارة والصلاة يحفظ العبادة من البطلان ويرفع الخشوع.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-69",
    "text": "تدبر آيات الرحمة يورث القلب توقير الله وخوفاً من معصيته.",
    "category": "فوائد تربوية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-70",
    "text": "من فوائد قراءة القرآن: هداية القلب وطمأنينة النفس ونور البصيرة.",
    "category": "فوائد تربوية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-71",
    "text": "المواظبة على ورد قرآني يثبت اللسان على ذكر الله ويحفظ العهد مع كتاب رب العالمين.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-72",
    "text": "المواظبة على الأذكار المأثورة تحفظ العبد من الغفلة وتربط القلب بالله.",
    "category": "فوائد تربوية",
    "source": "السنة النبوية",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-73",
    "text": "من فوائد اتباع السنة: استقامة السلوك وبركة الوقت وقبول العمل.",
    "category": "فوائد تربوية",
    "source": "السنة",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-74",
    "text": "حفظ الأحاديث الصحيحة يقوي المعرفة بالدين ويصون المسلم من الضلال.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "فائدة علمية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-75",
    "text": "معرفة توحيد الله أساس قبول الأعمال وصيانة القلب من الشرك الخفي.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-76",
    "text": "الإخلاص لله وحده يجعل العبادة خالصة مقبولة عند رب العالمين.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-77",
    "text": "معرفة الحلال والحرام تحمي المسلم من الوقوع في المحرمات وتيسر المعاملات.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-78",
    "text": "الدعوة بالحكمة والموعظة الحسنة أقرب إلى القبول وأبعد عن التنفير.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-79",
    "text": "قدوة المسلم في سلوكه أبلغ من كثير من الكلام في تأثير الدعوة.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-80",
    "text": "بر الوالدين من أعظم أبواب الخير وسبب لبركة العمر والرزق.",
    "category": "فوائد تربوية",
    "source": null,
    "author_name": "آداب",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-81",
    "text": "الدعوة بالحكمة والموعظة الحسنة أقرب إلى القبول وأبعد عن التنفير.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-82",
    "text": "قدوة المسلم في سلوكه أبلغ من كثير من الكلام في تأثير الدعوة.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "فائدة دعوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-83",
    "text": "تدبر آيات الرحمة يورث القلب توقير الله وخوفاً من معصيته.",
    "category": "فوائد دعوية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-84",
    "text": "من فوائد قراءة القرآن: هداية القلب وطمأنينة النفس ونور البصيرة.",
    "category": "فوائد دعوية",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-85",
    "text": "المواظبة على ورد قرآني يثبت اللسان على ذكر الله ويحفظ العهد مع كتاب رب العالمين.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-86",
    "text": "المواظبة على الأذكار المأثورة تحفظ العبد من الغفلة وتربط القلب بالله.",
    "category": "فوائد دعوية",
    "source": "السنة النبوية",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-87",
    "text": "من فوائد اتباع السنة: استقامة السلوك وبركة الوقت وقبول العمل.",
    "category": "فوائد دعوية",
    "source": "السنة",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-88",
    "text": "حفظ الأحاديث الصحيحة يقوي المعرفة بالدين ويصون المسلم من الضلال.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "فائدة علمية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-89",
    "text": "معرفة توحيد الله أساس قبول الأعمال وصيانة القلب من الشرك الخفي.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-90",
    "text": "الإخلاص لله وحده يجعل العبادة خالصة مقبولة عند رب العالمين.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-91",
    "text": "تعلم أحكام الطهارة والصلاة يحفظ العبادة من البطلان ويرفع الخشوع.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-92",
    "text": "معرفة الحلال والحرام تحمي المسلم من الوقوع في المحرمات وتيسر المعاملات.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-93",
    "text": "الصحبة الصالحة تذكّر بالآخرة وتدفع إلى طاعة الله وترك المعاصي.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-94",
    "text": "حسن الخلق من أعظم ما يقرب العبد إلى الله ويرفع مكانته عند الناس.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-95",
    "text": "التواضع للعلماء والاستفادة من مجالس العلم يورث حلاوة الإيمان.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-96",
    "text": "بر الوالدين من أعظم أبواب الخير وسبب لبركة العمر والرزق.",
    "category": "فوائد دعوية",
    "source": null,
    "author_name": "آداب",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-97",
    "text": "بر الوالدين من أعظم أبواب الخير وسبب لبركة العمر والرزق.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "آداب",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-98",
    "text": "كظم الغيظ وصفح النفس من صفات المتقين وعلامات قوة الإيمان.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "آداب",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-99",
    "text": "حفظ اللسان من الغيبة والنميمة يصون المجتمع ويرفع درجة العبد.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "آداب",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-100",
    "text": "المواظبة على ورد قرآني يثبت اللسان على ذكر الله ويحفظ العهد مع كتاب رب العالمين.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-101",
    "text": "الإخلاص لله وحده يجعل العبادة خالصة مقبولة عند رب العالمين.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-102",
    "text": "التواضع للعلماء والاستفادة من مجالس العلم يورث حلاوة الإيمان.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-103",
    "text": "تدبر آيات الرحمة يورث القلب توقير الله وخوفاً من معصيته.",
    "category": "آداب وأخلاق",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-104",
    "text": "من فوائد قراءة القرآن: هداية القلب وطمأنينة النفس ونور البصيرة.",
    "category": "آداب وأخلاق",
    "source": "القرآن الكريم",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-105",
    "text": "المواظبة على الأذكار المأثورة تحفظ العبد من الغفلة وتربط القلب بالله.",
    "category": "آداب وأخلاق",
    "source": "السنة النبوية",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-106",
    "text": "من فوائد اتباع السنة: استقامة السلوك وبركة الوقت وقبول العمل.",
    "category": "آداب وأخلاق",
    "source": "السنة",
    "author_name": null,
    "status": "approved"
  },
  {
    "id": "seed-fawaid-107",
    "text": "حفظ الأحاديث الصحيحة يقوي المعرفة بالدين ويصون المسلم من الضلال.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "فائدة علمية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-108",
    "text": "معرفة توحيد الله أساس قبول الأعمال وصيانة القلب من الشرك الخفي.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "فائدة عقدية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-109",
    "text": "تعلم أحكام الطهارة والصلاة يحفظ العبادة من البطلان ويرفع الخشوع.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-110",
    "text": "معرفة الحلال والحرام تحمي المسلم من الوقوع في المحرمات وتيسر المعاملات.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "فائدة فقهية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-111",
    "text": "الصحبة الصالحة تذكّر بالآخرة وتدفع إلى طاعة الله وترك المعاصي.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  },
  {
    "id": "seed-fawaid-112",
    "text": "حسن الخلق من أعظم ما يقرب العبد إلى الله ويرفع مكانته عند الناس.",
    "category": "آداب وأخلاق",
    "source": null,
    "author_name": "فائدة تربوية",
    "status": "approved"
  }
];

export function filterSeedFawaid({
  category,
  search,
}: {
  category?: string;
  search?: string;
}) {
  let items = SEED_FAWAID.filter((f) => f.status === "approved");
  if (category && category !== "all") {
    items = items.filter((f) => f.category === category);
  }
  if (search?.trim()) {
    const s = search.trim();
    items = items.filter((f) => arabicMatchAny([f.text, f.author_name, f.source], s));
  }
  return items;
}
