/** بيانات دروس الحرمين الشريفين — المسجد الحرام والمسجد النبوي */

export type HaramainLesson = {
  id: string;
  external_key: string;
  title: string;
  speaker_name: string;
  mosque: string;
  city: string;
  region: string;
  country: string;
  category: string;
  day_of_week: string;
  lesson_time: string;
  schedule: string;
  description: string;
  audience: string;
  delivery: string;
  status: "approved";
  keywords: string[];
  live_url?: string;
  activity_type: "درس" | "دورة";
  is_course: boolean;
  is_recurring: boolean;
  haramain_type: "مكة" | "المدينة";
};

export const HARAMAIN_LESSONS: HaramainLesson[] = [
  // ── دروس المسجد الحرام — مكة المكرمة ──────────────────────────────────
  {
    id: "haramain-haram-sudais-tafsir",
    external_key: "haramain-haram-sudais-tafsir",
    title: "درس التفسير — الشيخ عبدالرحمن السديس",
    speaker_name: "عبدالرحمن بن عبدالعزيز السديس",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "تفسير",
    day_of_week: "الجمعة",
    lesson_time: "بعد الفجر",
    schedule: "أسبوعي كل جمعة بعد صلاة الفجر",
    description: "درس في تفسير القرآن الكريم يُلقيه معالي الشيخ عبدالرحمن السديس إمام وخطيب المسجد الحرام في الحلقة العلمية الأسبوعية.",
    audience: "الجميع",
    delivery: "حضوري ومباشر",
    status: "approved",
    keywords: ["تفسير", "قرآن", "المسجد الحرام", "السديس", "مكة"],
    live_url: "https://www.saudiradio.net.sa",
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-ghazzawi-hadith",
    external_key: "haramain-haram-ghazzawi-hadith",
    title: "درس الحديث والسيرة — المسجد الحرام",
    speaker_name: "سعود الشريم",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "حديث",
    day_of_week: "الاثنين،الخميس",
    lesson_time: "بعد المغرب",
    schedule: "أسبوعي الاثنين والخميس بعد صلاة المغرب",
    description: "حلقة علمية في الحديث النبوي الشريف والسيرة النبوية بالمسجد الحرام.",
    audience: "الجميع",
    delivery: "حضوري ومباشر",
    status: "approved",
    keywords: ["حديث", "سيرة", "المسجد الحرام", "الشريم", "مكة"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-fiqh-weekly",
    external_key: "haramain-haram-fiqh-weekly",
    title: "درس الفقه الأسبوعي — المسجد الحرام",
    speaker_name: "عبدالله بن سليمان المنيع",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "فقه",
    day_of_week: "الثلاثاء",
    lesson_time: "بعد العصر",
    schedule: "أسبوعي كل ثلاثاء بعد صلاة العصر",
    description: "درس في الفقه الإسلامي المقارن يشمل أحكام العبادات والمعاملات.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["فقه", "أحكام", "المسجد الحرام", "مكة"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-aqeedah-fajr",
    external_key: "haramain-haram-aqeedah-fajr",
    title: "درس العقيدة بعد الفجر — المسجد الحرام",
    speaker_name: "خالد الغامدي",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "عقيدة",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "بعد الفجر",
    schedule: "يومي (ما عدا الجمعة) بعد الفجر",
    description: "دروس يومية في العقيدة الإسلامية وأصول الدين تُعقد بعد صلاة الفجر في رحاب المسجد الحرام.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["عقيدة", "توحيد", "المسجد الحرام", "مكة", "الغامدي"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-tafsir-juz-daily",
    external_key: "haramain-haram-tafsir-juz-daily",
    title: "تفسير جزء يومي — المسجد الحرام",
    speaker_name: "ماهر المعيقلي",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "تفسير",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس،الجمعة",
    lesson_time: "بعد التراويح",
    schedule: "يومي في رمضان بعد التراويح",
    description: "تفسير مختصر وميسَّر لجزء من القرآن الكريم يُقدَّم بعد صلاة التراويح في شهر رمضان المبارك.",
    audience: "الجميع",
    delivery: "حضوري ومباشر",
    status: "approved",
    keywords: ["تفسير", "رمضان", "تراويح", "المسجد الحرام", "المعيقلي", "مكة"],
    activity_type: "درس",
    is_course: false,
    is_recurring: false,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-quran-halaqat",
    external_key: "haramain-haram-quran-halaqat",
    title: "حلقات تحفيظ القرآن الكريم — المسجد الحرام",
    speaker_name: "مجموعة من المشايخ والمعلمين",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "قرآن",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "بعد الفجر وبعد العصر",
    schedule: "يومي في الصباح والمساء طوال السنة",
    description: "حلقات منظمة لتحفيظ القرآن الكريم وتجويده تحت إشراف رئاسة شؤون المسجد الحرام.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["تحفيظ", "قرآن", "تجويد", "المسجد الحرام", "مكة"],
    activity_type: "دورة",
    is_course: true,
    is_recurring: true,
    haramain_type: "مكة",
  },

  // ── دروس المسجد النبوي — المدينة المنورة ──────────────────────────────
  {
    id: "haramain-nabawi-tafsir-fajr",
    external_key: "haramain-nabawi-tafsir-fajr",
    title: "درس التفسير بعد الفجر — المسجد النبوي",
    speaker_name: "علي عبدالرحمن الحذيفي",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "تفسير",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "بعد الفجر",
    schedule: "يومي (ما عدا الجمعة) بعد الفجر",
    description: "درس يومي في تفسير القرآن الكريم يُلقيه فضيلة الشيخ علي الحذيفي إمام المسجد النبوي في صحن المسجد.",
    audience: "الجميع",
    delivery: "حضوري ومباشر",
    status: "approved",
    keywords: ["تفسير", "قرآن", "المسجد النبوي", "الحذيفي", "المدينة"],
    live_url: "https://www.mp3quran.net",
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-hadith-bukhari",
    external_key: "haramain-nabawi-hadith-bukhari",
    title: "شرح صحيح البخاري — المسجد النبوي",
    speaker_name: "عبدالمحسن العباد البدر",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "حديث",
    day_of_week: "الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "بعد الفجر",
    schedule: "أسبوعي أربعة أيام بعد صلاة الفجر",
    description: "شرح موسَّع ومفصَّل لصحيح الإمام البخاري يُتيح للطلاب فهم الحديث النبوي ومعرفة رجاله وفقهه.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["حديث", "البخاري", "المسجد النبوي", "العباد", "المدينة", "شرح"],
    activity_type: "درس",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-fiqh-maghrib",
    external_key: "haramain-nabawi-fiqh-maghrib",
    title: "درس الفقه بعد المغرب — المسجد النبوي",
    speaker_name: "عبدالله بن عبدالرحمن الجبرين",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "فقه",
    day_of_week: "الأحد،الثلاثاء،الخميس",
    lesson_time: "بعد المغرب",
    schedule: "ثلاثة أيام في الأسبوع بعد المغرب",
    description: "درس في الفقه الحنبلي وفقه المقارن يُركز على مسائل الفقه العملية في العبادات والمعاملات.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["فقه", "حنبلي", "المسجد النبوي", "المدينة", "أحكام"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-aqeedah-isha",
    external_key: "haramain-nabawi-aqeedah-isha",
    title: "درس العقيدة بعد العشاء — المسجد النبوي",
    speaker_name: "صالح بن عبدالعزيز آل الشيخ",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "عقيدة",
    day_of_week: "الأحد،الأربعاء",
    lesson_time: "بعد العشاء",
    schedule: "مرتين في الأسبوع بعد العشاء",
    description: "دروس في التوحيد والعقيدة الإسلامية تُركز على تصحيح المفاهيم وبيان منهج أهل السنة والجماعة.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["عقيدة", "توحيد", "المسجد النبوي", "المدينة", "آل الشيخ"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-arabic-sarf",
    external_key: "haramain-nabawi-arabic-sarf",
    title: "درس النحو والصرف — المسجد النبوي",
    speaker_name: "عطية محمد سالم",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "لغة عربية",
    day_of_week: "الاثنين،الخميس",
    lesson_time: "بعد الظهر",
    schedule: "أسبوعي الاثنين والخميس بعد الظهر",
    description: "درس متخصص في علوم اللغة العربية — النحو والصرف والبلاغة — لطلاب العلم الشرعي.",
    audience: "طلاب العلم",
    delivery: "حضوري",
    status: "approved",
    keywords: ["نحو", "صرف", "لغة عربية", "المسجد النبوي", "المدينة"],
    activity_type: "درس",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-seerah-weekly",
    external_key: "haramain-nabawi-seerah-weekly",
    title: "درس السيرة النبوية الأسبوعي — المسجد النبوي",
    speaker_name: "محمد بن عبدالله الشبل",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "سيرة",
    day_of_week: "الجمعة",
    lesson_time: "قبل الجمعة",
    schedule: "أسبوعي قبيل صلاة الجمعة",
    description: "سرد تاريخي وتحليلي لسيرة النبي محمد ﷺ مع ربط الأحداث بمواضعها في المدينة المنورة.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["سيرة", "نبوية", "المسجد النبوي", "المدينة", "تاريخ"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-quran-halaqat",
    external_key: "haramain-nabawi-quran-halaqat",
    title: "حلقات التحفيظ والتجويد — المسجد النبوي",
    speaker_name: "مجموعة من المشايخ والمعلمين",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "قرآن",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "بعد الفجر وبعد العصر وبعد العشاء",
    schedule: "يومي في أوقات متعددة طوال السنة",
    description: "منظومة حلقات شاملة لتحفيظ القرآن الكريم ورواية حفص وورش وغيرها من القراءات.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["تحفيظ", "قرآن", "تجويد", "قراءات", "المسجد النبوي", "المدينة"],
    activity_type: "دورة",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-islamic-university-lectures",
    external_key: "haramain-nabawi-islamic-university-lectures",
    title: "محاضرات الجامعة الإسلامية — المدينة المنورة",
    speaker_name: "أساتذة الجامعة الإسلامية",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "تأصيل",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء",
    lesson_time: "بعد العصر",
    schedule: "أسبوعي بإشراف الجامعة الإسلامية",
    description: "محاضرات علمية تخصصية تُعقد بالتنسيق مع الجامعة الإسلامية بالمدينة المنورة في شتى العلوم الشرعية.",
    audience: "طلاب العلم",
    delivery: "حضوري",
    status: "approved",
    keywords: ["جامعة إسلامية", "علوم شرعية", "المدينة", "تأصيل", "محاضرات"],
    live_url: "https://www.iu.edu.sa",
    activity_type: "دورة",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },

  // ── دروس المسجد الحرام — إضافية ───────────────────────────────────────
  {
    id: "haramain-haram-usool-fiqh",
    external_key: "haramain-haram-usool-fiqh",
    title: "درس أصول الفقه — المسجد الحرام",
    speaker_name: "وليد بن إدريس المنيسي",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "أصول الفقه",
    day_of_week: "الاثنين",
    lesson_time: "بعد العصر",
    schedule: "أسبوعي كل اثنين بعد العصر",
    description: "شرح مختصر في أصول الفقه الإسلامي يُغطي المصادر الشرعية والمنهجية الأصولية.",
    audience: "طلاب العلم",
    delivery: "حضوري",
    status: "approved",
    keywords: ["أصول الفقه", "مصادر الشريعة", "المسجد الحرام", "مكة"],
    activity_type: "درس",
    is_course: true,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-arabic-quran",
    external_key: "haramain-haram-arabic-quran",
    title: "التجويد والقراءة — المسجد الحرام",
    speaker_name: "أحمد بن محمد عامر",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "تجويد",
    day_of_week: "الأربعاء،السبت",
    lesson_time: "بعد المغرب",
    schedule: "أسبوعي الأربعاء والسبت بعد المغرب",
    description: "دروس مكثفة في تجويد القرآن الكريم وأحكام التلاوة وفق رواية حفص عن عاصم.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["تجويد", "قرآن", "تلاوة", "المسجد الحرام", "مكة", "حفص"],
    activity_type: "دورة",
    is_course: true,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-seerah-fajr",
    external_key: "haramain-haram-seerah-fajr",
    title: "درس السيرة بعد الفجر — المسجد الحرام",
    speaker_name: "سعد بن ناصر الشثري",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "سيرة",
    day_of_week: "الجمعة",
    lesson_time: "بعد الفجر",
    schedule: "أسبوعي كل جمعة بعد الفجر",
    description: "دراسة تحليلية لسيرة النبي ﷺ مع التطبيقات التربوية والاستخلاص من الحوادث النبوية.",
    audience: "الجميع",
    delivery: "حضوري ومباشر",
    status: "approved",
    keywords: ["سيرة", "نبوية", "المسجد الحرام", "مكة", "الشثري"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-zuhd-raqaiq",
    external_key: "haramain-haram-zuhd-raqaiq",
    title: "درس الزهد والرقائق — المسجد الحرام",
    speaker_name: "عبدالله بن محمد المطلق",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "رقائق",
    day_of_week: "الخميس",
    lesson_time: "بعد العشاء",
    schedule: "أسبوعي كل خميس بعد العشاء",
    description: "دروس في الزهد والتصفية القلبية والتذكير بالآخرة وأساليب تزكية النفس.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["زهد", "رقائق", "تزكية", "المسجد الحرام", "مكة"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-uloom-hadith",
    external_key: "haramain-haram-uloom-hadith",
    title: "علوم الحديث والمصطلح — المسجد الحرام",
    speaker_name: "محمد بن عمر بازمول",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "علوم الحديث",
    day_of_week: "الأحد",
    lesson_time: "بعد الظهر",
    schedule: "أسبوعي كل أحد بعد الظهر",
    description: "شرح في علوم الحديث النبوي ومصطلحاته ودراسة الأسانيد وتحقيق الروايات.",
    audience: "طلاب العلم",
    delivery: "حضوري",
    status: "approved",
    keywords: ["علوم الحديث", "مصطلح", "إسناد", "المسجد الحرام", "مكة"],
    activity_type: "درس",
    is_course: true,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-durus-summer",
    external_key: "haramain-haram-durus-summer",
    title: "الدورة الصيفية العلمية — المسجد الحرام",
    speaker_name: "نخبة من العلماء",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "دورة علمية",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "بعد العصر",
    schedule: "يومي في الإجازة الصيفية",
    description: "دورة علمية صيفية مكثفة تشمل الفقه والتوحيد والتفسير والحديث تُعقد في رحاب المسجد الحرام.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["دورة صيفية", "علمية", "المسجد الحرام", "مكة", "تأهيل"],
    activity_type: "دورة",
    is_course: true,
    is_recurring: false,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-fiqh-nisaa",
    external_key: "haramain-haram-fiqh-nisaa",
    title: "فقه المرأة في الإسلام — المسجد الحرام",
    speaker_name: "نخبة من المشايخ",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "فقه",
    day_of_week: "الاثنين",
    lesson_time: "بعد الظهر",
    schedule: "أسبوعي كل اثنين بعد الظهر",
    description: "دروس تخصصية في الأحكام الشرعية المتعلقة بالمرأة في الفقه الإسلامي.",
    audience: "النساء",
    delivery: "حضوري",
    status: "approved",
    keywords: ["فقه", "المرأة", "أحكام", "المسجد الحرام", "مكة"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-tawhid-ramadan",
    external_key: "haramain-haram-tawhid-ramadan",
    title: "حلقات التوحيد في رمضان — المسجد الحرام",
    speaker_name: "عبدالرحمن بن صالح المحمود",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "عقيدة",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس،الجمعة",
    lesson_time: "بعد الفجر",
    schedule: "يومي في شهر رمضان بعد الفجر",
    description: "حلقات يومية في التوحيد وتصحيح المفاهيم العقدية خلال شهر رمضان المبارك.",
    audience: "الجميع",
    delivery: "حضوري ومباشر",
    status: "approved",
    keywords: ["توحيد", "رمضان", "عقيدة", "المسجد الحرام", "مكة"],
    activity_type: "درس",
    is_course: false,
    is_recurring: false,
    haramain_type: "مكة",
  },

  // ── دروس المسجد النبوي — إضافية ────────────────────────────────────────
  {
    id: "haramain-nabawi-muwatta-maliki",
    external_key: "haramain-nabawi-muwatta-maliki",
    title: "شرح موطأ الإمام مالك — المسجد النبوي",
    speaker_name: "عبدالكريم الخضير",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "حديث",
    day_of_week: "الاثنين،الثلاثاء",
    lesson_time: "بعد الفجر",
    schedule: "أسبوعي الاثنين والثلاثاء بعد الفجر",
    description: "شرح موسع للموطأ يتناول أحاديثه وآثاره مع بيان الفوائد الفقهية والتربوية.",
    audience: "طلاب العلم",
    delivery: "حضوري",
    status: "approved",
    keywords: ["موطأ", "مالك", "حديث", "المسجد النبوي", "المدينة", "الخضير"],
    activity_type: "درس",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-aqeedah-tahawiyya",
    external_key: "haramain-nabawi-aqeedah-tahawiyya",
    title: "شرح العقيدة الطحاوية — المسجد النبوي",
    speaker_name: "صالح آل الشيخ",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "عقيدة",
    day_of_week: "الأحد،الأربعاء",
    lesson_time: "بعد العصر",
    schedule: "مرتين في الأسبوع بعد العصر",
    description: "شرح متن العقيدة الطحاوية مع بيان مسائل الأسماء والصفات وأصول الاعتقاد السلفي.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["الطحاوية", "عقيدة", "أسماء وصفات", "المسجد النبوي", "المدينة"],
    activity_type: "درس",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-zad-mustaqni",
    external_key: "haramain-nabawi-zad-mustaqni",
    title: "شرح زاد المستقنع في الفقه — المسجد النبوي",
    speaker_name: "عبدالرحمن بن ناصر البراك",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "فقه",
    day_of_week: "الثلاثاء،الخميس",
    lesson_time: "بعد العصر",
    schedule: "أسبوعي الثلاثاء والخميس بعد العصر",
    description: "شرح مفصل لمختصر زاد المستقنع في الفقه الحنبلي مع مقارنة المذاهب في المسائل المهمة.",
    audience: "طلاب العلم",
    delivery: "حضوري",
    status: "approved",
    keywords: ["زاد المستقنع", "فقه حنبلي", "المسجد النبوي", "المدينة"],
    activity_type: "درس",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-tazkiyah-isha",
    external_key: "haramain-nabawi-tazkiyah-isha",
    title: "درس تزكية النفس بعد العشاء — المسجد النبوي",
    speaker_name: "محمد بن حسن الددو الشنقيطي",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "رقائق",
    day_of_week: "الجمعة",
    lesson_time: "بعد العشاء",
    schedule: "أسبوعي كل جمعة بعد العشاء",
    description: "درس في تزكية النفس والسلوك الروحي مستنداً إلى الكتاب والسنة وآثار السلف.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["تزكية", "سلوك", "المسجد النبوي", "المدينة", "الشنقيطي"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-uloom-quran",
    external_key: "haramain-nabawi-uloom-quran",
    title: "علوم القرآن والتفسير — المسجد النبوي",
    speaker_name: "ابراهيم بن عمر الحسن",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "علوم القرآن",
    day_of_week: "الاثنين",
    lesson_time: "بعد الظهر",
    schedule: "أسبوعي كل اثنين بعد الظهر",
    description: "دراسة في علوم القرآن الكريم تشمل أسباب النزول والناسخ والمنسوخ والمحكم والمتشابه.",
    audience: "طلاب العلم",
    delivery: "حضوري",
    status: "approved",
    keywords: ["علوم القرآن", "تفسير", "ناسخ ومنسوخ", "المسجد النبوي", "المدينة"],
    activity_type: "درس",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-arabic-balagh",
    external_key: "haramain-nabawi-arabic-balagh",
    title: "البلاغة القرآنية — المسجد النبوي",
    speaker_name: "فاضل السامرائي",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "لغة عربية",
    day_of_week: "الأربعاء",
    lesson_time: "بعد العصر",
    schedule: "أسبوعي كل أربعاء بعد العصر",
    description: "دراسة في الإعجاز البياني للقرآن الكريم من خلال البلاغة والأسلوب والتراكيب اللغوية.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["بلاغة", "إعجاز", "قرآن", "المسجد النبوي", "المدينة"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-fiqh-muasir",
    external_key: "haramain-nabawi-fiqh-muasir",
    title: "الفقه المعاصر — المسجد النبوي",
    speaker_name: "يوسف بن عبدالله الشبيلي",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "فقه معاصر",
    day_of_week: "الخميس",
    lesson_time: "بعد الظهر",
    schedule: "أسبوعي كل خميس بعد الظهر",
    description: "معالجة للمسائل الفقهية المستجدة في ضوء الكتاب والسنة والقياس الصحيح مع مراعاة الواقع المعاصر.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["فقه معاصر", "مستجدات", "المسجد النبوي", "المدينة", "الشبيلي"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-riyadh-salihin",
    external_key: "haramain-nabawi-riyadh-salihin",
    title: "شرح رياض الصالحين — المسجد النبوي",
    speaker_name: "محمد بن عبدالله الغامدي",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "حديث",
    day_of_week: "الأحد",
    lesson_time: "بعد المغرب",
    schedule: "أسبوعي كل أحد بعد المغرب",
    description: "شرح مبسط لأحاديث رياض الصالحين للإمام النووي مع استخلاص الفوائد التربوية والعملية.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["رياض الصالحين", "حديث", "النووي", "المسجد النبوي", "المدينة"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-summer-course",
    external_key: "haramain-nabawi-summer-course",
    title: "الدورة الصيفية الشاملة — المدينة المنورة",
    speaker_name: "نخبة من علماء الجامعة الإسلامية",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "دورة علمية",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "الصباح والمساء",
    schedule: "يومي مكثف في الإجازة الصيفية",
    description: "دورة صيفية مكثفة للطلاب الجادين تشمل الفقه وأصوله والحديث والتفسير والعربية.",
    audience: "طلاب العلم",
    delivery: "حضوري",
    status: "approved",
    keywords: ["دورة صيفية", "جامعة إسلامية", "علمية", "المدينة", "تأهيل شرعي"],
    live_url: "https://www.iu.edu.sa",
    activity_type: "دورة",
    is_course: true,
    is_recurring: false,
    haramain_type: "المدينة",
  },
];

/** تصفية دروس الحرمين حسب الموقع */
export function getHaramainLessonsByType(type: "مكة" | "المدينة" | "all" = "all") {
  if (type === "all") return HARAMAIN_LESSONS;
  return HARAMAIN_LESSONS.filter((l) => l.haramain_type === type);
}

/** تحويل درس الحرمين لبنية بيانات الدرس القياسية */
export function haramainToLessonPayload(lesson: HaramainLesson) {
  return {
    external_key: lesson.external_key,
    title: lesson.title,
    speaker_name: lesson.speaker_name,
    mosque: lesson.mosque,
    city: lesson.city,
    region: lesson.region,
    category: lesson.category,
    day_of_week: lesson.day_of_week,
    lesson_time: lesson.lesson_time,
    schedule: lesson.schedule,
    description: lesson.description,
    audience: lesson.audience,
    delivery: lesson.delivery,
    status: lesson.status,
    keywords: lesson.keywords,
    live_url: lesson.live_url ?? null,
    activity_type: lesson.activity_type,
    is_course: lesson.is_course,
    is_recurring: lesson.is_recurring,
  };
}
