/** بيانات دروس الحرمين الشريفين — المسجد الحرام والمسجد النبوي */

export type HaramainLesson = {
  id: string;
  external_key: string;
  title: string;
  speaker_name: string;
  mosque: string;
  city: string;
  region: string;
  country: string;
  category: string;
  day_of_week: string;
  lesson_time: string;
  schedule: string;
  description: string;
  audience: string;
  delivery: string;
  status: "approved";
  keywords: string[];
  live_url?: string;
  activity_type: "درس" | "دورة";
  is_course: boolean;
  is_recurring: boolean;
  haramain_type: "مكة" | "المدينة";
};

export const HARAMAIN_LESSONS: HaramainLesson[] = [
  // ── دروس المسجد الحرام — مكة المكرمة ──────────────────────────────────
  {
    id: "haramain-haram-sudais-tafsir",
    external_key: "haramain-haram-sudais-tafsir",
    title: "درس التفسير — الشيخ عبدالرحمن السديس",
    speaker_name: "عبدالرحمن بن عبدالعزيز السديس",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "تفسير",
    day_of_week: "الجمعة",
    lesson_time: "بعد الفجر",
    schedule: "أسبوعي كل جمعة بعد صلاة الفجر",
    description: "درس في تفسير القرآن الكريم يُلقيه معالي الشيخ عبدالرحمن السديس إمام وخطيب المسجد الحرام في الحلقة العلمية الأسبوعية.",
    audience: "الجميع",
    delivery: "حضوري ومباشر",
    status: "approved",
    keywords: ["تفسير", "قرآن", "المسجد الحرام", "السديس", "مكة"],
    live_url: "https://www.saudiradio.net.sa",
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-ghazzawi-hadith",
    external_key: "haramain-haram-ghazzawi-hadith",
    title: "درس الحديث والسيرة — المسجد الحرام",
    speaker_name: "سعود الشريم",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "حديث",
    day_of_week: "الاثنين،الخميس",
    lesson_time: "بعد المغرب",
    schedule: "أسبوعي الاثنين والخميس بعد صلاة المغرب",
    description: "حلقة علمية في الحديث النبوي الشريف والسيرة النبوية بالمسجد الحرام.",
    audience: "الجميع",
    delivery: "حضوري ومباشر",
    status: "approved",
    keywords: ["حديث", "سيرة", "المسجد الحرام", "الشريم", "مكة"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-fiqh-weekly",
    external_key: "haramain-haram-fiqh-weekly",
    title: "درس الفقه الأسبوعي — المسجد الحرام",
    speaker_name: "عبدالله بن سليمان المنيع",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "فقه",
    day_of_week: "الثلاثاء",
    lesson_time: "بعد العصر",
    schedule: "أسبوعي كل ثلاثاء بعد صلاة العصر",
    description: "درس في الفقه الإسلامي المقارن يشمل أحكام العبادات والمعاملات.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["فقه", "أحكام", "المسجد الحرام", "مكة"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-aqeedah-fajr",
    external_key: "haramain-haram-aqeedah-fajr",
    title: "درس العقيدة بعد الفجر — المسجد الحرام",
    speaker_name: "خالد الغامدي",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "عقيدة",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "بعد الفجر",
    schedule: "يومي (ما عدا الجمعة) بعد الفجر",
    description: "دروس يومية في العقيدة الإسلامية وأصول الدين تُعقد بعد صلاة الفجر في رحاب المسجد الحرام.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["عقيدة", "توحيد", "المسجد الحرام", "مكة", "الغامدي"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-tafsir-juz-daily",
    external_key: "haramain-haram-tafsir-juz-daily",
    title: "تفسير جزء يومي — المسجد الحرام",
    speaker_name: "ماهر المعيقلي",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "تفسير",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس،الجمعة",
    lesson_time: "بعد التراويح",
    schedule: "يومي في رمضان بعد التراويح",
    description: "تفسير مختصر وميسَّر لجزء من القرآن الكريم يُقدَّم بعد صلاة التراويح في شهر رمضان المبارك.",
    audience: "الجميع",
    delivery: "حضوري ومباشر",
    status: "approved",
    keywords: ["تفسير", "رمضان", "تراويح", "المسجد الحرام", "المعيقلي", "مكة"],
    activity_type: "درس",
    is_course: false,
    is_recurring: false,
    haramain_type: "مكة",
  },
  {
    id: "haramain-haram-quran-halaqat",
    external_key: "haramain-haram-quran-halaqat",
    title: "حلقات تحفيظ القرآن الكريم — المسجد الحرام",
    speaker_name: "مجموعة من المشايخ والمعلمين",
    mosque: "المسجد الحرام",
    city: "مكة المكرمة",
    region: "منطقة مكة المكرمة",
    country: "المملكة العربية السعودية",
    category: "قرآن",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "بعد الفجر وبعد العصر",
    schedule: "يومي في الصباح والمساء طوال السنة",
    description: "حلقات منظمة لتحفيظ القرآن الكريم وتجويده تحت إشراف رئاسة شؤون المسجد الحرام.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["تحفيظ", "قرآن", "تجويد", "المسجد الحرام", "مكة"],
    activity_type: "دورة",
    is_course: true,
    is_recurring: true,
    haramain_type: "مكة",
  },

  // ── دروس المسجد النبوي — المدينة المنورة ──────────────────────────────
  {
    id: "haramain-nabawi-tafsir-fajr",
    external_key: "haramain-nabawi-tafsir-fajr",
    title: "درس التفسير بعد الفجر — المسجد النبوي",
    speaker_name: "علي عبدالرحمن الحذيفي",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "تفسير",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "بعد الفجر",
    schedule: "يومي (ما عدا الجمعة) بعد الفجر",
    description: "درس يومي في تفسير القرآن الكريم يُلقيه فضيلة الشيخ علي الحذيفي إمام المسجد النبوي في صحن المسجد.",
    audience: "الجميع",
    delivery: "حضوري ومباشر",
    status: "approved",
    keywords: ["تفسير", "قرآن", "المسجد النبوي", "الحذيفي", "المدينة"],
    live_url: "https://www.mp3quran.net",
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-hadith-bukhari",
    external_key: "haramain-nabawi-hadith-bukhari",
    title: "شرح صحيح البخاري — المسجد النبوي",
    speaker_name: "عبدالمحسن العباد البدر",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "حديث",
    day_of_week: "الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "بعد الفجر",
    schedule: "أسبوعي أربعة أيام بعد صلاة الفجر",
    description: "شرح موسَّع ومفصَّل لصحيح الإمام البخاري يُتيح للطلاب فهم الحديث النبوي ومعرفة رجاله وفقهه.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["حديث", "البخاري", "المسجد النبوي", "العباد", "المدينة", "شرح"],
    activity_type: "درس",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-fiqh-maghrib",
    external_key: "haramain-nabawi-fiqh-maghrib",
    title: "درس الفقه بعد المغرب — المسجد النبوي",
    speaker_name: "عبدالله بن عبدالرحمن الجبرين",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "فقه",
    day_of_week: "الأحد،الثلاثاء،الخميس",
    lesson_time: "بعد المغرب",
    schedule: "ثلاثة أيام في الأسبوع بعد المغرب",
    description: "درس في الفقه الحنبلي وفقه المقارن يُركز على مسائل الفقه العملية في العبادات والمعاملات.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["فقه", "حنبلي", "المسجد النبوي", "المدينة", "أحكام"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-aqeedah-isha",
    external_key: "haramain-nabawi-aqeedah-isha",
    title: "درس العقيدة بعد العشاء — المسجد النبوي",
    speaker_name: "صالح بن عبدالعزيز آل الشيخ",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "عقيدة",
    day_of_week: "الأحد،الأربعاء",
    lesson_time: "بعد العشاء",
    schedule: "مرتين في الأسبوع بعد العشاء",
    description: "دروس في التوحيد والعقيدة الإسلامية تُركز على تصحيح المفاهيم وبيان منهج أهل السنة والجماعة.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["عقيدة", "توحيد", "المسجد النبوي", "المدينة", "آل الشيخ"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-arabic-sarf",
    external_key: "haramain-nabawi-arabic-sarf",
    title: "درس النحو والصرف — المسجد النبوي",
    speaker_name: "عطية محمد سالم",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "لغة عربية",
    day_of_week: "الاثنين،الخميس",
    lesson_time: "بعد الظهر",
    schedule: "أسبوعي الاثنين والخميس بعد الظهر",
    description: "درس متخصص في علوم اللغة العربية — النحو والصرف والبلاغة — لطلاب العلم الشرعي.",
    audience: "طلاب العلم",
    delivery: "حضوري",
    status: "approved",
    keywords: ["نحو", "صرف", "لغة عربية", "المسجد النبوي", "المدينة"],
    activity_type: "درس",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-seerah-weekly",
    external_key: "haramain-nabawi-seerah-weekly",
    title: "درس السيرة النبوية الأسبوعي — المسجد النبوي",
    speaker_name: "محمد بن عبدالله الشبل",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "سيرة",
    day_of_week: "الجمعة",
    lesson_time: "قبل الجمعة",
    schedule: "أسبوعي قبيل صلاة الجمعة",
    description: "سرد تاريخي وتحليلي لسيرة النبي محمد ﷺ مع ربط الأحداث بمواضعها في المدينة المنورة.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["سيرة", "نبوية", "المسجد النبوي", "المدينة", "تاريخ"],
    activity_type: "درس",
    is_course: false,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-quran-halaqat",
    external_key: "haramain-nabawi-quran-halaqat",
    title: "حلقات التحفيظ والتجويد — المسجد النبوي",
    speaker_name: "مجموعة من المشايخ والمعلمين",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "قرآن",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء،الخميس",
    lesson_time: "بعد الفجر وبعد العصر وبعد العشاء",
    schedule: "يومي في أوقات متعددة طوال السنة",
    description: "منظومة حلقات شاملة لتحفيظ القرآن الكريم ورواية حفص وورش وغيرها من القراءات.",
    audience: "الجميع",
    delivery: "حضوري",
    status: "approved",
    keywords: ["تحفيظ", "قرآن", "تجويد", "قراءات", "المسجد النبوي", "المدينة"],
    activity_type: "دورة",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },
  {
    id: "haramain-nabawi-islamic-university-lectures",
    external_key: "haramain-nabawi-islamic-university-lectures",
    title: "محاضرات الجامعة الإسلامية — المدينة المنورة",
    speaker_name: "أساتذة الجامعة الإسلامية",
    mosque: "المسجد النبوي الشريف",
    city: "المدينة المنورة",
    region: "منطقة المدينة المنورة",
    country: "المملكة العربية السعودية",
    category: "تأصيل",
    day_of_week: "السبت،الأحد،الاثنين،الثلاثاء،الأربعاء",
    lesson_time: "بعد العصر",
    schedule: "أسبوعي بإشراف الجامعة الإسلامية",
    description: "محاضرات علمية تخصصية تُعقد بالتنسيق مع الجامعة الإسلامية بالمدينة المنورة في شتى العلوم الشرعية.",
    audience: "طلاب العلم",
    delivery: "حضوري",
    status: "approved",
    keywords: ["جامعة إسلامية", "علوم شرعية", "المدينة", "تأصيل", "محاضرات"],
    live_url: "https://www.iu.edu.sa",
    activity_type: "دورة",
    is_course: true,
    is_recurring: true,
    haramain_type: "المدينة",
  },
];

/** تصفية دروس الحرمين حسب الموقع */
export function getHaramainLessonsByType(type: "مكة" | "المدينة" | "all" = "all") {
  if (type === "all") return HARAMAIN_LESSONS;
  return HARAMAIN_LESSONS.filter((l) => l.haramain_type === type);
}

/** تحويل درس الحرمين لبنية بيانات الدرس القياسية */
export function haramainToLessonPayload(lesson: HaramainLesson) {
  return {
    external_key: lesson.external_key,
    title: lesson.title,
    speaker_name: lesson.speaker_name,
    mosque: lesson.mosque,
    city: lesson.city,
    region: lesson.region,
    category: lesson.category,
    day_of_week: lesson.day_of_week,
    lesson_time: lesson.lesson_time,
    schedule: lesson.schedule,
    description: lesson.description,
    audience: lesson.audience,
    delivery: lesson.delivery,
    status: lesson.status,
    keywords: lesson.keywords,
    live_url: lesson.live_url ?? null,
    activity_type: lesson.activity_type,
    is_course: lesson.is_course,
    is_recurring: lesson.is_recurring,
  };
}
