


export const LIBRARY_CATEGORIES = [
  "الكل",
  "حديث",
  "تفسير",
  "عقيدة",
  "فقه",
  "سيرة",
  "آداب",
  "لغة",
  "أصول الفقه",
  "علوم القرآن",
  "مصطلح الحديث",
  "رقائق",
  "منطق وفلسفة",
] as const;

export type LibraryCategory = (typeof LIBRARY_CATEGORIES)[number];

export type LibraryBook = {
  id: string;
  title: string;
  author: string;
  type: string;
  category: string;
  description: string;
  parts_label?: string;
  external_url?: string;
  status: "approved";
  keywords: string[];
  sort_order: number;
};

export const LIBRARY_CATALOG: LibraryBook[] = [
  {
    id: "book-bukhari",
    title: "صحيح البخاري",
    author: "الإمام محمد بن إسماعيل البخاري",
    type: "كتاب",
    category: "حديث",
    description: "أصح كتاب بعد كتاب الله؛ جمع أحاديث النبي ﷺ بأعلى معايير الجرح والتعديل.",
    parts_label: "9 أجزاء",
    external_url: "https://sunnah.com/bukhari",
    status: "approved",
    keywords: ["حديث", "صحيح", "البخاري", "سنة", "أحاديث"],
    sort_order: 1,
  },
  {
    id: "book-muslim",
    title: "صحيح مسلم",
    author: "الإمام مسلم بن الحجاج النيسابوري",
    type: "كتاب",
    category: "حديث",
    description: "ثاني أصح كتب الحديث؛ مرتب حسب الأبواب الفقهية مع تدقيق في السند والمتن.",
    parts_label: "7 أجزاء",
    external_url: "https://sunnah.com/muslim",
    status: "approved",
    keywords: ["حديث", "صحيح", "مسلم", "سنة"],
    sort_order: 2,
  },
  {
    id: "book-muwatta",
    title: "موطأ الإمام مالك",
    author: "الإمام مالك بن أنس",
    type: "كتاب",
    category: "حديث",
    description: "أقدم كتاب حديث وصل إلينا؛ يجمع الأحاديث والآثار على مذهب أهل المدينة.",
    parts_label: "61 كتابًا",
    external_url: "https://sunnah.com/malik",
    status: "approved",
    keywords: ["موطأ", "مالك", "حديث", "آثار", "المدينة"],
    sort_order: 3,
  },
  {
    id: "book-abudawud",
    title: "سنن أبي داود",
    author: "الإمام أبو داود سليمان بن الأشعث السجستاني",
    type: "كتاب",
    category: "حديث",
    description: "من كتب السنن المعتمدة؛ يركز على أحاديث الأحكام مع بيان ما فيها من ضعف.",
    parts_label: "43 كتابًا",
    external_url: "https://sunnah.com/abudawud",
    status: "approved",
    keywords: ["سنن", "أبي داود", "حديث", "أحكام"],
    sort_order: 4,
  },
  {
    id: "book-tirmidhi",
    title: "سنن الترمذي",
    author: "الإمام محمد بن عيسى الترمذي",
    type: "كتاب",
    category: "حديث",
    description: "سنن معتمد يذكر درجة الحديث ويستخرج الفقه من الأحاديث.",
    parts_label: "50 كتابًا",
    external_url: "https://sunnah.com/tirmidhi",
    status: "approved",
    keywords: ["سنن", "الترمذي", "حديث", "جامع"],
    sort_order: 5,
  },
  {
    id: "book-nasai",
    title: "سنن النسائي",
    author: "الإمام أحمد بن شعيب النسائي",
    type: "كتاب",
    category: "حديث",
    description: "من أدق كتب السنن في التحقيق والتدقيق في رواة الأحاديث.",
    parts_label: "51 كتابًا",
    external_url: "https://sunnah.com/nasai",
    status: "approved",
    keywords: ["سنن", "النسائي", "حديث"],
    sort_order: 6,
  },
  {
    id: "book-ibnmajah",
    title: "سنن ابن ماجه",
    author: "الإمام محمد بن يزيد ابن ماجه",
    type: "كتاب",
    category: "حديث",
    description: "أحد كتب السنن الستة؛ يشتمل على أحاديث في العقيدة والآداب والأحكام.",
    parts_label: "37 كتابًا",
    external_url: "https://sunnah.com/ibnmajah",
    status: "approved",
    keywords: ["سنن", "ابن ماجه", "حديث", "السنن الستة"],
    sort_order: 7,
  },
  {
    id: "book-ahmad",
    title: "مسند الإمام أحمد",
    author: "الإمام أحمد بن حنبل",
    type: "كتاب",
    category: "حديث",
    description: "أكبر مسند في الحديث؛ جمع أحاديث الصحابة مرتبة على الصحابي.",
    parts_label: "مسند",
    external_url: "https://sunnah.com/ahmad",
    status: "approved",
    keywords: ["مسند", "أحمد بن حنبل", "حديث"],
    sort_order: 8,
  },
  {
    id: "book-riyadh",
    title: "رياض الصالحين",
    author: "الإمام يحيى بن شرف النووي",
    type: "كتاب",
    category: "آداب",
    description: "مختارات من الأحاديث النبوية في الأخلاق والآداب والزهد والعبادات.",
    parts_label: "19 كتابًا",
    external_url: "https://sunnah.com/riyadussalihin",
    status: "approved",
    keywords: ["رياض الصالحين", "النووي", "آداب", "أخلاق", "حديث"],
    sort_order: 9,
  },
  {
    id: "book-nawawi40",
    title: "الأربعون النووية",
    author: "الإمام يحيى بن شرف النووي",
    type: "كتاب",
    category: "حديث",
    description: "أربعون حديثًا جامعًا لأصول الدين؛ من أشهر المتون في طلب العلم.",
    parts_label: "40 حديثًا",
    external_url: "https://sunnah.com/nawawi40",
    status: "approved",
    keywords: ["الأربعون النووية", "النووي", "حديث", "متن"],
    sort_order: 10,
  },
  {
    id: "book-bulugh",
    title: "بلوغ المرام",
    author: "الإمام ابن حجر العسقلاني",
    type: "كتاب",
    category: "فقه",
    description: "جمع أحاديث الأحكام مع بيان درجة كل حديث ومصدره.",
    parts_label: "16 بابًا",
    external_url: "https://sunnah.com/bulugh",
    status: "approved",
    keywords: ["بلوغ المرام", "ابن حجر", "فقه", "أحكام", "حديث"],
    sort_order: 11,
  },
  {
    id: "book-umdat",
    title: "عمدة الأحكام",
    author: "الإمام عبد الغني المقدسي",
    type: "كتاب",
    category: "فقه",
    description: "مختصر في أحاديث الأحكام؛ يُقرأ مع شرح بلوغ المرام.",
    parts_label: "أبواب",
    status: "approved",
    keywords: ["عمدة الأحكام", "المقدسي", "فقه", "أحكام"],
    sort_order: 12,
  },
  {
    id: "book-zad",
    title: "زاد المعاد",
    author: "الإمام ابن قيم الجوزية",
    type: "كتاب",
    category: "سيرة",
    description: "طب نبوي شامل في السيرة والفقه والآداب والدعوة.",
    parts_label: "5 أجزاء",
    status: "approved",
    keywords: ["زاد المعاد", "ابن القيم", "سيرة", "طب نبوي"],
    sort_order: 13,
  },
  {
    id: "book-madarij",
    title: "مدارج السالكين",
    author: "الإمام ابن قيم الجوزية",
    type: "كتاب",
    category: "آداب",
    description: "شرح منهاج القاصدين في السلوك والتزكية والعبادة.",
    parts_label: "3 أجزاء",
    status: "approved",
    keywords: ["مدارج السالكين", "ابن القيم", "سلوك", "تزكية", "آداب"],
    sort_order: 14,
  },
  {
    id: "book-tafsir-ibnkathir",
    title: "تفسير ابن كثير",
    author: "الإمام ابن كثير",
    type: "كتاب",
    category: "تفسير",
    description: "تفسير بالمأثور؛ يعتمد على القرآن والسنة الصحيحة وأقوال السلف.",
    parts_label: "4 أجزاء",
    status: "approved",
    keywords: ["تفسير", "ابن كثير", "قرآن", "تفسير بالمأثور"],
    sort_order: 15,
  },
  {
    id: "book-tafsir-saadi",
    title: "تفسير السعدي",
    author: "الشيخ عبد الرحمن بن ناصر السعدي",
    type: "كتاب",
    category: "تفسير",
    description: "تفسير ميسّر يركز على معاني الآيات وما تضمنته من هداية وإرشاد.",
    parts_label: "تفسير كامل",
    status: "approved",
    keywords: ["تفسير", "السعدي", "تيسير", "قرآن"],
    sort_order: 16,
  },
  {
    id: "book-tafsir-tabari",
    title: "تفسير الطبري",
    author: "الإمام محمد بن جرير الطبري",
    type: "كتاب",
    category: "تفسير",
    description: "جامع البيان في تفسير القرآن؛ من أهم التفاسير بالرواية.",
    parts_label: "30 جزءًا",
    status: "approved",
    keywords: ["تفسير", "الطبري", "جامع البيان", "قرآن"],
    sort_order: 17,
  },
  {
    id: "book-wasitiyyah",
    title: "العقيدة الواسطية",
    author: "شيخ الإسلام ابن تيمية",
    type: "كتاب",
    category: "عقيدة",
    description: "رسالة في عقيدة أهل السنة والجماعة؛ مختصرة واضحة في أصول الإيمان.",
    status: "approved",
    keywords: ["العقيدة الواسطية", "ابن تيمية", "عقيدة", "توحيد"],
    sort_order: 18,
  },
  {
    id: "book-tawhid",
    title: "كتاب التوحيد",
    author: "الإمام محمد بن عبد الوهاب",
    type: "كتاب",
    category: "عقيدة",
    description: "كتاب في توحيد الله وإخلاص العبادة؛ من أهم كتب العقيدة.",
    status: "approved",
    keywords: ["كتاب التوحيد", "محمد بن عبد الوهاب", "توحيد", "عقيدة"],
    sort_order: 19,
  },
  {
    id: "book-thalathah",
    title: "ثلاثة الأصول",
    author: "الإمام محمد بن عبد الوهاب",
    type: "كتاب",
    category: "عقيدة",
    description: "رسالة مختصرة في أصول الدين: معرفة الله ودين الإسلام ومعرفة نبيك ﷺ.",
    status: "approved",
    keywords: ["ثلاثة الأصول", "أصول", "عقيدة", "توحيد"],
    sort_order: 20,
  },
  // ── كتب أصول الفقه ────────────────────────────────────────────────────
  {
    id: "book-waraqat",
    title: "الورقات في أصول الفقه",
    author: "إمام الحرمين أبو المعالي الجويني",
    type: "متن",
    category: "أصول الفقه",
    description: "متن مختصر في علم أصول الفقه؛ يُدرَّس في المعاهد الشرعية على نطاق واسع.",
    status: "approved",
    keywords: ["الورقات", "أصول الفقه", "الجويني", "متن"],
    sort_order: 21,
  },
  {
    id: "book-mustasfa",
    title: "المستصفى في علم الأصول",
    author: "حجة الإسلام أبو حامد الغزالي",
    type: "كتاب",
    category: "أصول الفقه",
    description: "كتاب جامع في أصول الفقه يُعالج مسائله بأسلوب فلسفي استدلالي.",
    parts_label: "جزءان",
    status: "approved",
    keywords: ["المستصفى", "الغزالي", "أصول الفقه", "استدلال"],
    sort_order: 22,
  },
  {
    id: "book-rawdah-nadhir",
    title: "روضة الناظر وجنة المناظر",
    author: "ابن قدامة المقدسي",
    type: "كتاب",
    category: "أصول الفقه",
    description: "مؤلَّف في علم الأصول على المذهب الحنبلي؛ من أبرز المراجع في هذا الفن.",
    status: "approved",
    keywords: ["روضة الناظر", "ابن قدامة", "أصول الفقه", "حنبلي"],
    sort_order: 23,
  },
  // ── علوم القرآن ─────────────────────────────────────────────────────
  {
    id: "book-itqan",
    title: "الإتقان في علوم القرآن",
    author: "جلال الدين السيوطي",
    type: "كتاب",
    category: "علوم القرآن",
    description: "موسوعة شاملة في علوم القرآن الكريم: النزول، الجمع، القراءات، التفسير.",
    parts_label: "جزءان",
    status: "approved",
    keywords: ["الإتقان", "السيوطي", "علوم القرآن", "القراءات"],
    sort_order: 24,
  },
  {
    id: "book-burhan",
    title: "البرهان في علوم القرآن",
    author: "بدر الدين الزركشي",
    type: "كتاب",
    category: "علوم القرآن",
    description: "مرجع أساسي في علوم القرآن يتضمن 47 نوعاً من أنواع علوم القرآن.",
    parts_label: "4 أجزاء",
    status: "approved",
    keywords: ["البرهان", "الزركشي", "علوم القرآن"],
    sort_order: 25,
  },
  {
    id: "book-tibyan",
    title: "التبيان في آداب حملة القرآن",
    author: "الإمام النووي",
    type: "كتاب",
    category: "علوم القرآن",
    description: "كتاب في آداب حامل القرآن وتلاوته والتعامل معه من قِبل المعلم والمتعلم.",
    status: "approved",
    keywords: ["التبيان", "النووي", "قرآن", "آداب التلاوة"],
    sort_order: 26,
  },
  // ── مصطلح الحديث ────────────────────────────────────────────────────
  {
    id: "book-nukhbah",
    title: "نخبة الفكر في مصطلح أهل الأثر",
    author: "الإمام ابن حجر العسقلاني",
    type: "متن",
    category: "مصطلح الحديث",
    description: "أشهر متن في علم مصطلح الحديث؛ جمع أنواعه بأسلوب موجز ومتقن.",
    status: "approved",
    keywords: ["نخبة الفكر", "ابن حجر", "مصطلح الحديث", "متن"],
    sort_order: 27,
  },
  {
    id: "book-muqaddimah-ibn-salah",
    title: "مقدمة ابن الصلاح في علوم الحديث",
    author: "ابن الصلاح الشهرزوري",
    type: "كتاب",
    category: "مصطلح الحديث",
    description: "مرجع أساسي في علم مصطلح الحديث يُعدّ أُماً للمصنفات اللاحقة في هذا الفن.",
    status: "approved",
    keywords: ["مقدمة ابن الصلاح", "علوم الحديث", "مصطلح"],
    sort_order: 28,
  },
  // ── رقائق وتزكية ───────────────────────────────────────────────────
  {
    id: "book-ihya",
    title: "إحياء علوم الدين",
    author: "حجة الإسلام أبو حامد الغزالي",
    type: "كتاب",
    category: "رقائق",
    description: "موسوعة في تزكية النفس والسلوك والأخلاق تُعدّ من أجمع الكتب في هذا الميدان.",
    parts_label: "4 أجزاء",
    status: "approved",
    keywords: ["إحياء علوم الدين", "الغزالي", "تزكية", "أخلاق", "سلوك"],
    sort_order: 29,
  },
  {
    id: "book-risalah-qushayri",
    title: "الرسالة القشيرية",
    author: "أبو القاسم القشيري",
    type: "كتاب",
    category: "رقائق",
    description: "كتاب في الأحوال والمقامات الروحية؛ مرجع في التصوف الإسلامي الشرعي.",
    status: "approved",
    keywords: ["الرسالة القشيرية", "القشيري", "سلوك", "تزكية"],
    sort_order: 30,
  },
  {
    id: "book-madaarij",
    title: "مدارج السالكين بين منازل إياك نعبد وإياك نستعين",
    author: "ابن القيم الجوزية",
    type: "كتاب",
    category: "رقائق",
    description: "شرح مستفيض لكتاب منازل السائرين يُعدّ من أجمع كتب السلوك والتزكية.",
    parts_label: "3 أجزاء",
    status: "approved",
    keywords: ["مدارج السالكين", "ابن القيم", "تزكية", "سلوك", "منازل السالكين"],
    sort_order: 31,
  },
  // ── كتب السيرة ─────────────────────────────────────────────────────
  {
    id: "book-seerah-ibn-hisham",
    title: "السيرة النبوية",
    author: "ابن هشام الحميري",
    type: "كتاب",
    category: "سيرة",
    description: "أشهر كتب السيرة النبوية؛ اختصار لسيرة ابن إسحاق مع إضافات مهمة.",
    parts_label: "4 أجزاء",
    status: "approved",
    keywords: ["السيرة النبوية", "ابن هشام", "سيرة", "تاريخ"],
    sort_order: 32,
  },
  {
    id: "book-raheeq",
    title: "الرحيق المختوم",
    author: "الشيخ صفي الرحمن المباركفوري",
    type: "كتاب",
    category: "سيرة",
    description: "حاز جائزة رابطة العالم الإسلامي الأولى؛ كتاب في السيرة بأسلوب سلس محقق.",
    status: "approved",
    keywords: ["الرحيق المختوم", "المباركفوري", "سيرة", "نبوية"],
    sort_order: 33,
  },
  // ── فقه ─────────────────────────────────────────────────────────────
  {
    id: "book-minhaj-talibin",
    title: "منهاج الطالبين",
    author: "الإمام النووي",
    type: "كتاب",
    category: "فقه",
    description: "متن في الفقه الشافعي شديد الاتقان؛ أحد أهم المراجع في الفقه الشافعي.",
    status: "approved",
    keywords: ["منهاج الطالبين", "النووي", "فقه", "شافعي"],
    sort_order: 34,
  },
  {
    id: "book-mughni",
    title: "المغني",
    author: "ابن قدامة المقدسي",
    type: "كتاب",
    category: "فقه",
    description: "موسوعة في الفقه المقارن من وجهة نظر المذهب الحنبلي؛ 10 مجلدات.",
    parts_label: "10 أجزاء",
    status: "approved",
    keywords: ["المغني", "ابن قدامة", "فقه", "حنبلي", "مقارن"],
    sort_order: 35,
  },
  {
    id: "book-fiqh-sunnah",
    title: "فقه السنة",
    author: "الشيخ سيد سابق",
    type: "كتاب",
    category: "فقه",
    description: "كتاب شامل في الفقه الإسلامي مستنداً إلى الأدلة من الكتاب والسنة بأسلوب ميسّر.",
    parts_label: "3 أجزاء",
    status: "approved",
    keywords: ["فقه السنة", "سيد سابق", "فقه", "عبادات"],
    sort_order: 36,
  },
  // ── لغة عربية ───────────────────────────────────────────────────────
  {
    id: "book-alfiyyah",
    title: "ألفية ابن مالك في النحو والصرف",
    author: "ابن مالك الأندلسي",
    type: "متن",
    category: "لغة",
    description: "أشهر منظومة في النحو العربي تشتمل على ألف بيت شعري.",
    status: "approved",
    keywords: ["ألفية", "ابن مالك", "نحو", "صرف", "لغة"],
    sort_order: 37,
  },
  {
    id: "book-ajrumiyyah",
    title: "متن الآجرومية في النحو",
    author: "ابن آجروم الصنهاجي",
    type: "متن",
    category: "لغة",
    description: "مقدمة مختصرة في علم النحو للمبتدئين؛ مدرَّسة في المعاهد الشرعية.",
    status: "approved",
    keywords: ["الآجرومية", "نحو", "مبتدئ", "لغة عربية"],
    sort_order: 38,
  },
  // ── عقيدة ───────────────────────────────────────────────────────────
  {
    id: "book-tahawiyyah",
    title: "العقيدة الطحاوية",
    author: "الإمام أبو جعفر الطحاوي",
    type: "متن",
    category: "عقيدة",
    description: "متن عقدي شامل يُمثّل مذهب أهل السنة والجماعة في الاعتقاد.",
    status: "approved",
    keywords: ["الطحاوية", "عقيدة", "أهل السنة", "الطحاوي"],
    sort_order: 39,
  },
  {
    id: "book-luma-safarini",
    title: "لوامع الأنوار البهية — شرح الدرة المضية",
    author: "السفاريني الحنبلي",
    type: "كتاب",
    category: "عقيدة",
    description: "شرح كبير على منظومة الدرة المضية في عقيدة أهل الفرقة المرضية.",
    parts_label: "جزءان",
    status: "approved",
    keywords: ["السفاريني", "عقيدة", "لوامع الأنوار"],
    sort_order: 40,
  },
  // ── تفسير ───────────────────────────────────────────────────────────
  {
    id: "book-saadi",
    title: "تيسير الكريم الرحمن — تفسير السعدي",
    author: "الشيخ عبدالرحمن السعدي",
    type: "كتاب",
    category: "تفسير",
    description: "تفسير ميسر بأسلوب سهل واضح يستهدف عموم القراء؛ من أكثر التفاسير رواجاً.",
    external_url: "https://quran.ksu.edu.sa/tafseer/saadi/",
    status: "approved",
    keywords: ["تفسير السعدي", "السعدي", "تيسير الكريم", "تفسير ميسر"],
    sort_order: 41,
  },
  {
    id: "book-qurtubi",
    title: "الجامع لأحكام القرآن — تفسير القرطبي",
    author: "الإمام القرطبي",
    type: "كتاب",
    category: "تفسير",
    description: "تفسير فقهي موسّع يستقصي الأحكام الشرعية المستنبطة من الآيات القرآنية.",
    parts_label: "20 جزءاً",
    external_url: "https://quran.ksu.edu.sa/tafseer/qurtubi/",
    status: "approved",
    keywords: ["القرطبي", "تفسير أحكام", "فقه القرآن"],
    sort_order: 42,
  },
];
