


export const LIBRARY_CATEGORIES = [
  "الكل",
  "حديث",
  "تفسير",
  "عقيدة",
  "فقه",
  "سيرة",
  "آداب",
  "لغة",
  "أصول الفقه",
  "علوم القرآن",
  "مصطلح الحديث",
  "رقائق",
  "منطق وفلسفة",
] as const;

export type LibraryCategory = (typeof LIBRARY_CATEGORIES)[number];

export type LibraryBook = {
  id: string;
  title: string;
  author: string;
  type: string;
  category: string;
  description: string;
  parts_label?: string;
  external_url?: string;
  status: "approved";
  keywords: string[];
  sort_order: number;
};

export const LIBRARY_CATALOG: LibraryBook[] = [
  {
    id: "book-bukhari",
    title: "صحيح البخاري",
    author: "الإمام محمد بن إسماعيل البخاري",
    type: "كتاب",
    category: "حديث",
    description: "أصح كتاب بعد كتاب الله؛ جمع أحاديث النبي ﷺ بأعلى معايير الجرح والتعديل.",
    parts_label: "9 أجزاء",
    external_url: "https://sunnah.com/bukhari",
    status: "approved",
    keywords: ["حديث", "صحيح", "البخاري", "سنة", "أحاديث"],
    sort_order: 1,
  },
  {
    id: "book-muslim",
    title: "صحيح مسلم",
    author: "الإمام مسلم بن الحجاج النيسابوري",
    type: "كتاب",
    category: "حديث",
    description: "ثاني أصح كتب الحديث؛ مرتب حسب الأبواب الفقهية مع تدقيق في السند والمتن.",
    parts_label: "7 أجزاء",
    external_url: "https://sunnah.com/muslim",
    status: "approved",
    keywords: ["حديث", "صحيح", "مسلم", "سنة"],
    sort_order: 2,
  },
  {
    id: "book-muwatta",
    title: "موطأ الإمام مالك",
    author: "الإمام مالك بن أنس",
    type: "كتاب",
    category: "حديث",
    description: "أقدم كتاب حديث وصل إلينا؛ يجمع الأحاديث والآثار على مذهب أهل المدينة.",
    parts_label: "61 كتابًا",
    external_url: "https://sunnah.com/malik",
    status: "approved",
    keywords: ["موطأ", "مالك", "حديث", "آثار", "المدينة"],
    sort_order: 3,
  },
  {
    id: "book-abudawud",
    title: "سنن أبي داود",
    author: "الإمام أبو داود سليمان بن الأشعث السجستاني",
    type: "كتاب",
    category: "حديث",
    description: "من كتب السنن المعتمدة؛ يركز على أحاديث الأحكام مع بيان ما فيها من ضعف.",
    parts_label: "43 كتابًا",
    external_url: "https://sunnah.com/abudawud",
    status: "approved",
    keywords: ["سنن", "أبي داود", "حديث", "أحكام"],
    sort_order: 4,
  },
  {
    id: "book-tirmidhi",
    title: "سنن الترمذي",
    author: "الإمام محمد بن عيسى الترمذي",
    type: "كتاب",
    category: "حديث",
    description: "سنن معتمد يذكر درجة الحديث ويستخرج الفقه من الأحاديث.",
    parts_label: "50 كتابًا",
    external_url: "https://sunnah.com/tirmidhi",
    status: "approved",
    keywords: ["سنن", "الترمذي", "حديث", "جامع"],
    sort_order: 5,
  },
  {
    id: "book-nasai",
    title: "سنن النسائي",
    author: "الإمام أحمد بن شعيب النسائي",
    type: "كتاب",
    category: "حديث",
    description: "من أدق كتب السنن في التحقيق والتدقيق في رواة الأحاديث.",
    parts_label: "51 كتابًا",
    external_url: "https://sunnah.com/nasai",
    status: "approved",
    keywords: ["سنن", "النسائي", "حديث"],
    sort_order: 6,
  },
  {
    id: "book-ibnmajah",
    title: "سنن ابن ماجه",
    author: "الإمام محمد بن يزيد ابن ماجه",
    type: "كتاب",
    category: "حديث",
    description: "أحد كتب السنن الستة؛ يشتمل على أحاديث في العقيدة والآداب والأحكام.",
    parts_label: "37 كتابًا",
    external_url: "https://sunnah.com/ibnmajah",
    status: "approved",
    keywords: ["سنن", "ابن ماجه", "حديث", "السنن الستة"],
    sort_order: 7,
  },
  {
    id: "book-ahmad",
    title: "مسند الإمام أحمد",
    author: "الإمام أحمد بن حنبل",
    type: "كتاب",
    category: "حديث",
    description: "أكبر مسند في الحديث؛ جمع أحاديث الصحابة مرتبة على الصحابي.",
    parts_label: "مسند",
    external_url: "https://sunnah.com/ahmad",
    status: "approved",
    keywords: ["مسند", "أحمد بن حنبل", "حديث"],
    sort_order: 8,
  },
  {
    id: "book-riyadh",
    title: "رياض الصالحين",
    author: "الإمام يحيى بن شرف النووي",
    type: "كتاب",
    category: "آداب",
    description: "مختارات من الأحاديث النبوية في الأخلاق والآداب والزهد والعبادات.",
    parts_label: "19 كتابًا",
    external_url: "https://sunnah.com/riyadussalihin",
    status: "approved",
    keywords: ["رياض الصالحين", "النووي", "آداب", "أخلاق", "حديث"],
    sort_order: 9,
  },
  {
    id: "book-nawawi40",
    title: "الأربعون النووية",
    author: "الإمام يحيى بن شرف النووي",
    type: "كتاب",
    category: "حديث",
    description: "أربعون حديثًا جامعًا لأصول الدين؛ من أشهر المتون في طلب العلم.",
    parts_label: "40 حديثًا",
    external_url: "https://sunnah.com/nawawi40",
    status: "approved",
    keywords: ["الأربعون النووية", "النووي", "حديث", "متن"],
    sort_order: 10,
  },
  {
    id: "book-bulugh",
    title: "بلوغ المرام",
    author: "الإمام ابن حجر العسقلاني",
    type: "كتاب",
    category: "فقه",
    description: "جمع أحاديث الأحكام مع بيان درجة كل حديث ومصدره.",
    parts_label: "16 بابًا",
    external_url: "https://sunnah.com/bulugh",
    status: "approved",
    keywords: ["بلوغ المرام", "ابن حجر", "فقه", "أحكام", "حديث"],
    sort_order: 11,
  },
  {
    id: "book-umdat",
    title: "عمدة الأحكام",
    author: "الإمام عبد الغني المقدسي",
    type: "كتاب",
    category: "فقه",
    description: "مختصر في أحاديث الأحكام؛ يُقرأ مع شرح بلوغ المرام.",
    parts_label: "أبواب",
    status: "approved",
    keywords: ["عمدة الأحكام", "المقدسي", "فقه", "أحكام"],
    sort_order: 12,
  },
  {
    id: "book-zad",
    title: "زاد المعاد",
    author: "الإمام ابن قيم الجوزية",
    type: "كتاب",
    category: "سيرة",
    description: "طب نبوي شامل في السيرة والفقه والآداب والدعوة.",
    parts_label: "5 أجزاء",
    status: "approved",
    keywords: ["زاد المعاد", "ابن القيم", "سيرة", "طب نبوي"],
    sort_order: 13,
  },
  {
    id: "book-madarij",
    title: "مدارج السالكين",
    author: "الإمام ابن قيم الجوزية",
    type: "كتاب",
    category: "آداب",
    description: "شرح منهاج القاصدين في السلوك والتزكية والعبادة.",
    parts_label: "3 أجزاء",
    status: "approved",
    keywords: ["مدارج السالكين", "ابن القيم", "سلوك", "تزكية", "آداب"],
    sort_order: 14,
  },
  {
    id: "book-tafsir-ibnkathir",
    title: "تفسير ابن كثير",
    author: "الإمام ابن كثير",
    type: "كتاب",
    category: "تفسير",
    description: "تفسير بالمأثور؛ يعتمد على القرآن والسنة الصحيحة وأقوال السلف.",
    parts_label: "4 أجزاء",
    status: "approved",
    keywords: ["تفسير", "ابن كثير", "قرآن", "تفسير بالمأثور"],
    sort_order: 15,
  },
  {
    id: "book-tafsir-saadi",
    title: "تفسير السعدي",
    author: "الشيخ عبد الرحمن بن ناصر السعدي",
    type: "كتاب",
    category: "تفسير",
    description: "تفسير ميسّر يركز على معاني الآيات وما تضمنته من هداية وإرشاد.",
    parts_label: "تفسير كامل",
    status: "approved",
    keywords: ["تفسير", "السعدي", "تيسير", "قرآن"],
    sort_order: 16,
  },
  {
    id: "book-tafsir-tabari",
    title: "تفسير الطبري",
    author: "الإمام محمد بن جرير الطبري",
    type: "كتاب",
    category: "تفسير",
    description: "جامع البيان في تفسير القرآن؛ من أهم التفاسير بالرواية.",
    parts_label: "30 جزءًا",
    status: "approved",
    keywords: ["تفسير", "الطبري", "جامع البيان", "قرآن"],
    sort_order: 17,
  },
  {
    id: "book-wasitiyyah",
    title: "العقيدة الواسطية",
    author: "شيخ الإسلام ابن تيمية",
    type: "كتاب",
    category: "عقيدة",
    description: "رسالة في عقيدة أهل السنة والجماعة؛ مختصرة واضحة في أصول الإيمان.",
    status: "approved",
    keywords: ["العقيدة الواسطية", "ابن تيمية", "عقيدة", "توحيد"],
    sort_order: 18,
  },
  {
    id: "book-tawhid",
    title: "كتاب التوحيد",
    author: "الإمام محمد بن عبد الوهاب",
    type: "كتاب",
    category: "عقيدة",
    description: "كتاب في توحيد الله وإخلاص العبادة؛ من أهم كتب العقيدة.",
    status: "approved",
    keywords: ["كتاب التوحيد", "محمد بن عبد الوهاب", "توحيد", "عقيدة"],
    sort_order: 19,
  },
  {
    id: "book-thalathah",
    title: "ثلاثة الأصول",
    author: "الإمام محمد بن عبد الوهاب",
    type: "كتاب",
    category: "عقيدة",
    description: "رسالة مختصرة في أصول الدين: معرفة الله ودين الإسلام ومعرفة نبيك ﷺ.",
    status: "approved",
    keywords: ["ثلاثة الأصول", "أصول", "عقيدة", "توحيد"],
    sort_order: 20,
  },
  // ── كتب أصول الفقه ────────────────────────────────────────────────────
  {
    id: "book-waraqat",
    title: "الورقات في أصول الفقه",
    author: "إمام الحرمين أبو المعالي الجويني",
    type: "متن",
    category: "أصول الفقه",
    description: "متن مختصر في علم أصول الفقه؛ يُدرَّس في المعاهد الشرعية على نطاق واسع.",
    status: "approved",
    keywords: ["الورقات", "أصول الفقه", "الجويني", "متن"],
    sort_order: 21,
  },
  {
    id: "book-mustasfa",
    title: "المستصفى في علم الأصول",
    author: "حجة الإسلام أبو حامد الغزالي",
    type: "كتاب",
    category: "أصول الفقه",
    description: "كتاب جامع في أصول الفقه يُعالج مسائله بأسلوب فلسفي استدلالي.",
    parts_label: "جزءان",
    status: "approved",
    keywords: ["المستصفى", "الغزالي", "أصول الفقه", "استدلال"],
    sort_order: 22,
  },
  {
    id: "book-rawdah-nadhir",
    title: "روضة الناظر وجنة المناظر",
    author: "ابن قدامة المقدسي",
    type: "كتاب",
    category: "أصول الفقه",
    description: "مؤلَّف في علم الأصول على المذهب الحنبلي؛ من أبرز المراجع في هذا الفن.",
    status: "approved",
    keywords: ["روضة الناظر", "ابن قدامة", "أصول الفقه", "حنبلي"],
    sort_order: 23,
  },
  // ── علوم القرآن ─────────────────────────────────────────────────────
  {
    id: "book-itqan",
    title: "الإتقان في علوم القرآن",
    author: "جلال الدين السيوطي",
    type: "كتاب",
    category: "علوم القرآن",
    description: "موسوعة شاملة في علوم القرآن الكريم: النزول، الجمع، القراءات، التفسير.",
    parts_label: "جزءان",
    status: "approved",
    keywords: ["الإتقان", "السيوطي", "علوم القرآن", "القراءات"],
    sort_order: 24,
  },
  {
    id: "book-burhan",
    title: "البرهان في علوم القرآن",
    author: "بدر الدين الزركشي",
    type: "كتاب",
    category: "علوم القرآن",
    description: "مرجع أساسي في علوم القرآن يتضمن 47 نوعاً من أنواع علوم القرآن.",
    parts_label: "4 أجزاء",
    status: "approved",
    keywords: ["البرهان", "الزركشي", "علوم القرآن"],
    sort_order: 25,
  },
  {
    id: "book-tibyan",
    title: "التبيان في آداب حملة القرآن",
    author: "الإمام النووي",
    type: "كتاب",
    category: "علوم القرآن",
    description: "كتاب في آداب حامل القرآن وتلاوته والتعامل معه من قِبل المعلم والمتعلم.",
    status: "approved",
    keywords: ["التبيان", "النووي", "قرآن", "آداب التلاوة"],
    sort_order: 26,
  },
  // ── مصطلح الحديث ────────────────────────────────────────────────────
  {
    id: "book-nukhbah",
    title: "نخبة الفكر في مصطلح أهل الأثر",
    author: "الإمام ابن حجر العسقلاني",
    type: "متن",
    category: "مصطلح الحديث",
    description: "أشهر متن في علم مصطلح الحديث؛ جمع أنواعه بأسلوب موجز ومتقن.",
    status: "approved",
    keywords: ["نخبة الفكر", "ابن حجر", "مصطلح الحديث", "متن"],
    sort_order: 27,
  },
  {
    id: "book-muqaddimah-ibn-salah",
    title: "مقدمة ابن الصلاح في علوم الحديث",
    author: "ابن الصلاح الشهرزوري",
    type: "كتاب",
    category: "مصطلح الحديث",
    description: "مرجع أساسي في علم مصطلح الحديث يُعدّ أُماً للمصنفات اللاحقة في هذا الفن.",
    status: "approved",
    keywords: ["مقدمة ابن الصلاح", "علوم الحديث", "مصطلح"],
    sort_order: 28,
  },
  // ── رقائق وتزكية ───────────────────────────────────────────────────
  {
    id: "book-ihya",
    title: "إحياء علوم الدين",
    author: "حجة الإسلام أبو حامد الغزالي",
    type: "كتاب",
    category: "رقائق",
    description: "موسوعة في تزكية النفس والسلوك والأخلاق تُعدّ من أجمع الكتب في هذا الميدان.",
    parts_label: "4 أجزاء",
    status: "approved",
    keywords: ["إحياء علوم الدين", "الغزالي", "تزكية", "أخلاق", "سلوك"],
    sort_order: 29,
  },
  {
    id: "book-risalah-qushayri",
    title: "الرسالة القشيرية",
    author: "أبو القاسم القشيري",
    type: "كتاب",
    category: "رقائق",
    description: "كتاب في الأحوال والمقامات الروحية؛ مرجع في التصوف الإسلامي الشرعي.",
    status: "approved",
    keywords: ["الرسالة القشيرية", "القشيري", "سلوك", "تزكية"],
    sort_order: 30,
  },
  {
    id: "book-madaarij",
    title: "مدارج السالكين بين منازل إياك نعبد وإياك نستعين",
    author: "ابن القيم الجوزية",
    type: "كتاب",
    category: "رقائق",
    description: "شرح مستفيض لكتاب منازل السائرين يُعدّ من أجمع كتب السلوك والتزكية.",
    parts_label: "3 أجزاء",
    status: "approved",
    keywords: ["مدارج السالكين", "ابن القيم", "تزكية", "سلوك", "منازل السالكين"],
    sort_order: 31,
  },
  // ── كتب السيرة ─────────────────────────────────────────────────────
  {
    id: "book-seerah-ibn-hisham",
    title: "السيرة النبوية",
    author: "ابن هشام الحميري",
    type: "كتاب",
    category: "سيرة",
    description: "أشهر كتب السيرة النبوية؛ اختصار لسيرة ابن إسحاق مع إضافات مهمة.",
    parts_label: "4 أجزاء",
    status: "approved",
    keywords: ["السيرة النبوية", "ابن هشام", "سيرة", "تاريخ"],
    sort_order: 32,
  },
  {
    id: "book-raheeq",
    title: "الرحيق المختوم",
    author: "الشيخ صفي الرحمن المباركفوري",
    type: "كتاب",
    category: "سيرة",
    description: "حاز جائزة رابطة العالم الإسلامي الأولى؛ كتاب في السيرة بأسلوب سلس محقق.",
    status: "approved",
    keywords: ["الرحيق المختوم", "المباركفوري", "سيرة", "نبوية"],
    sort_order: 33,
  },
  // ── فقه ─────────────────────────────────────────────────────────────
  {
    id: "book-minhaj-talibin",
    title: "منهاج الطالبين",
    author: "الإمام النووي",
    type: "كتاب",
    category: "فقه",
    description: "متن في الفقه الشافعي شديد الاتقان؛ أحد أهم المراجع في الفقه الشافعي.",
    status: "approved",
    keywords: ["منهاج الطالبين", "النووي", "فقه", "شافعي"],
    sort_order: 34,
  },
  {
    id: "book-mughni",
    title: "المغني",
    author: "ابن قدامة المقدسي",
    type: "كتاب",
    category: "فقه",
    description: "موسوعة في الفقه المقارن من وجهة نظر المذهب الحنبلي؛ 10 مجلدات.",
    parts_label: "10 أجزاء",
    status: "approved",
    keywords: ["المغني", "ابن قدامة", "فقه", "حنبلي", "مقارن"],
    sort_order: 35,
  },
  {
    id: "book-fiqh-sunnah",
    title: "فقه السنة",
    author: "الشيخ سيد سابق",
    type: "كتاب",
    category: "فقه",
    description: "كتاب شامل في الفقه الإسلامي مستنداً إلى الأدلة من الكتاب والسنة بأسلوب ميسّر.",
    parts_label: "3 أجزاء",
    status: "approved",
    keywords: ["فقه السنة", "سيد سابق", "فقه", "عبادات"],
    sort_order: 36,
  },
  // ── لغة عربية ───────────────────────────────────────────────────────
  {
    id: "book-alfiyyah",
    title: "ألفية ابن مالك في النحو والصرف",
    author: "ابن مالك الأندلسي",
    type: "متن",
    category: "لغة",
    description: "أشهر منظومة في النحو العربي تشتمل على ألف بيت شعري.",
    status: "approved",
    keywords: ["ألفية", "ابن مالك", "نحو", "صرف", "لغة"],
    sort_order: 37,
  },
  {
    id: "book-ajrumiyyah",
    title: "متن الآجرومية في النحو",
    author: "ابن آجروم الصنهاجي",
    type: "متن",
    category: "لغة",
    description: "مقدمة مختصرة في علم النحو للمبتدئين؛ مدرَّسة في المعاهد الشرعية.",
    status: "approved",
    keywords: ["الآجرومية", "نحو", "مبتدئ", "لغة عربية"],
    sort_order: 38,
  },
  // ── عقيدة ───────────────────────────────────────────────────────────
  {
    id: "book-tahawiyyah",
    title: "العقيدة الطحاوية",
    author: "الإمام أبو جعفر الطحاوي",
    type: "متن",
    category: "عقيدة",
    description: "متن عقدي شامل يُمثّل مذهب أهل السنة والجماعة في الاعتقاد.",
    status: "approved",
    keywords: ["الطحاوية", "عقيدة", "أهل السنة", "الطحاوي"],
    sort_order: 39,
  },
  {
    id: "book-luma-safarini",
    title: "لوامع الأنوار البهية — شرح الدرة المضية",
    author: "السفاريني الحنبلي",
    type: "كتاب",
    category: "عقيدة",
    description: "شرح كبير على منظومة الدرة المضية في عقيدة أهل الفرقة المرضية.",
    parts_label: "جزءان",
    status: "approved",
    keywords: ["السفاريني", "عقيدة", "لوامع الأنوار"],
    sort_order: 40,
  },
  // ── تفسير ───────────────────────────────────────────────────────────
  {
    id: "book-saadi",
    title: "تيسير الكريم الرحمن — تفسير السعدي",
    author: "الشيخ عبدالرحمن السعدي",
    type: "كتاب",
    category: "تفسير",
    description: "تفسير ميسر بأسلوب سهل واضح يستهدف عموم القراء؛ من أكثر التفاسير رواجاً.",
    external_url: "https://quran.ksu.edu.sa/tafseer/saadi/",
    status: "approved",
    keywords: ["تفسير السعدي", "السعدي", "تيسير الكريم", "تفسير ميسر"],
    sort_order: 41,
  },
  {
    id: "book-qurtubi",
    title: "الجامع لأحكام القرآن — تفسير القرطبي",
    author: "الإمام القرطبي",
    type: "كتاب",
    category: "تفسير",
    description: "تفسير فقهي موسّع يستقصي الأحكام الشرعية المستنبطة من الآيات القرآنية.",
    parts_label: "20 جزءاً",
    external_url: "https://quran.ksu.edu.sa/tafseer/qurtubi/",
    status: "approved",
    keywords: ["القرطبي", "تفسير أحكام", "فقه القرآن"],
    sort_order: 42,
  },
  // ── تفسير (إضافة) ──────────────────────────────────────────────────
  {
    id: "book-tabari-tafsir",
    title: "جامع البيان عن تأويل آي القرآن — تفسير الطبري",
    author: "الإمام محمد بن جرير الطبري",
    type: "كتاب",
    category: "تفسير",
    description: "أقدم وأضخم تفاسير القرآن الكريم بالمأثور، يجمع روايات الصحابة والتابعين مع ترجيح الطبري.",
    parts_label: "30 جزءاً",
    external_url: "https://quran.ksu.edu.sa/tafseer/tabary/",
    status: "approved",
    keywords: ["الطبري", "تفسير بالمأثور", "جامع البيان", "تفسير كلاسيكي"],
    sort_order: 43,
  },
  {
    id: "book-baghawi-tafsir",
    title: "معالم التنزيل — تفسير البغوي",
    author: "الإمام البغوي",
    type: "كتاب",
    category: "تفسير",
    description: "تفسير بالمأثور موجز يُعدّ خلاصة من تفسير الثعلبي مع حذف الأحاديث الضعيفة.",
    parts_label: "8 أجزاء",
    status: "approved",
    keywords: ["البغوي", "معالم التنزيل", "تفسير"],
    sort_order: 44,
  },
  {
    id: "book-razi-tafsir",
    title: "مفاتيح الغيب — تفسير الرازي",
    author: "الإمام فخر الدين الرازي",
    type: "كتاب",
    category: "تفسير",
    description: "تفسير عقلي كلامي موسّع يناقش الآيات من جوانب فلسفية وعلمية ولغوية.",
    parts_label: "32 جزءاً",
    status: "approved",
    keywords: ["الرازي", "مفاتيح الغيب", "تفسير عقلي", "التفسير الكبير"],
    sort_order: 45,
  },
  // ── حديث (إضافة) ───────────────────────────────────────────────────
  {
    id: "book-tirmidhi",
    title: "الجامع الترمذي (سنن الترمذي)",
    author: "الإمام أبو عيسى الترمذي",
    type: "كتاب",
    category: "حديث",
    description: "من كتب السنن الستة، يتميز بتعليق المؤلف على الأحاديث وذكر آراء الفقهاء.",
    parts_label: "5 أجزاء",
    external_url: "https://sunnah.com/tirmidhi",
    status: "approved",
    keywords: ["الترمذي", "سنن", "جامع", "أحاديث"],
    sort_order: 46,
  },
  {
    id: "book-ibn-majah",
    title: "سنن ابن ماجه",
    author: "الإمام ابن ماجه",
    type: "كتاب",
    category: "حديث",
    description: "سادس كتب الصحاح الستة، يحتوي على أحاديث منها ما تفرد به عن بقية الكتب الستة.",
    parts_label: "جزآن",
    external_url: "https://sunnah.com/ibnmajah",
    status: "approved",
    keywords: ["ابن ماجه", "سنن", "الكتب الستة"],
    sort_order: 47,
  },
  {
    id: "book-darimi",
    title: "سنن الدارمي",
    author: "الإمام الدارمي",
    type: "كتاب",
    category: "حديث",
    description: "من أوائل كتب الحديث المصنفة، يشتمل على المسند والسنن ويقدم الأحاديث مع أسانيدها.",
    status: "approved",
    keywords: ["الدارمي", "سنن", "مسند", "حديث"],
    sort_order: 48,
  },
  {
    id: "book-bulugh-maram",
    title: "بلوغ المرام من أدلة الأحكام",
    author: "الحافظ ابن حجر العسقلاني",
    type: "كتاب",
    category: "حديث",
    description: "جمع الأحاديث الفقهية الواردة في الأحكام الشرعية مع بيان درجة كل حديث.",
    status: "approved",
    keywords: ["بلوغ المرام", "ابن حجر", "أحاديث الأحكام", "فقه الحديث"],
    sort_order: 49,
  },
  {
    id: "book-riyadh-salihin",
    title: "رياض الصالحين",
    author: "الإمام النووي",
    type: "كتاب",
    category: "حديث",
    description: "كتاب جامع للأحاديث المتعلقة بالآداب والأخلاق والتزكية مع آيات قرآنية مناسبة.",
    external_url: "https://sunnah.com/riyadussalihin",
    status: "approved",
    keywords: ["رياض الصالحين", "النووي", "آداب", "حديث", "تزكية"],
    sort_order: 50,
  },
  // ── فقه (إضافة) ────────────────────────────────────────────────────
  {
    id: "book-mughni",
    title: "المغني",
    author: "الإمام ابن قدامة المقدسي",
    type: "كتاب",
    category: "فقه",
    description: "موسوعة فقهية حنبلية كبرى تعرض أدلة المذاهب وتناقشها وتُرجّح بينها.",
    parts_label: "15 جزءاً",
    status: "approved",
    keywords: ["المغني", "ابن قدامة", "فقه حنبلي", "الخلاف"],
    sort_order: 51,
  },
  {
    id: "book-majmoo",
    title: "المجموع شرح المهذب",
    author: "الإمام النووي",
    type: "كتاب",
    category: "فقه",
    description: "موسوعة فقهية شافعية مقارنة، يجمع آراء المذاهب مع الترجيح والأدلة.",
    parts_label: "23 جزءاً",
    status: "approved",
    keywords: ["المجموع", "النووي", "فقه شافعي", "المهذب"],
    sort_order: 52,
  },
  {
    id: "book-bidayat-mujtahid",
    title: "بداية المجتهد ونهاية المقتصد",
    author: "الإمام ابن رشد القرطبي",
    type: "كتاب",
    category: "فقه",
    description: "كتاب في الفقه المقارن يعرض مسائل الخلاف بين المذاهب مع أدلتها وأسباب الخلاف.",
    parts_label: "جزآن",
    status: "approved",
    keywords: ["بداية المجتهد", "ابن رشد", "فقه مقارن", "خلاف"],
    sort_order: 53,
  },
  {
    id: "book-zaad-mustaqni",
    title: "زاد المستقنع في اختصار المقنع",
    author: "الشيخ الحجاوي",
    type: "متن",
    category: "فقه",
    description: "متن فقهي حنبلي مختصر من أكثر المتون شيوعاً في الدراسة الفقهية.",
    status: "approved",
    keywords: ["زاد المستقنع", "الحجاوي", "متن", "فقه حنبلي"],
    sort_order: 54,
  },
  {
    id: "book-hashiyat-ibn-abidin",
    title: "رد المحتار على الدر المختار (حاشية ابن عابدين)",
    author: "الإمام محمد أمين ابن عابدين",
    type: "كتاب",
    category: "فقه",
    description: "أشمل موسوعة فقهية حنفية، وهو حاشية على الدر المختار للحصكفي.",
    parts_label: "8 أجزاء",
    status: "approved",
    keywords: ["ابن عابدين", "رد المحتار", "فقه حنفي", "الدر المختار"],
    sort_order: 55,
  },
  // ── عقيدة (إضافة) ─────────────────────────────────────────────────
  {
    id: "book-tahawiyya-sharh",
    title: "شرح العقيدة الطحاوية",
    author: "الإمام ابن أبي العز الحنفي",
    type: "كتاب",
    category: "عقيدة",
    description: "أبرز شرح لمتن الطحاوية، يشرح عقيدة أهل السنة المتفق عليها بأسلوب علمي متقن.",
    status: "approved",
    keywords: ["الطحاوية", "عقيدة", "شرح", "ابن أبي العز"],
    sort_order: 56,
  },
  {
    id: "book-fath-majeed",
    title: "فتح المجيد شرح كتاب التوحيد",
    author: "الشيخ عبدالرحمن بن حسن آل الشيخ",
    type: "كتاب",
    category: "عقيدة",
    description: "شرح مبسوط على كتاب التوحيد للشيخ محمد بن عبدالوهاب مع الأدلة والتعليق.",
    status: "approved",
    keywords: ["فتح المجيد", "كتاب التوحيد", "عقيدة", "توحيد"],
    sort_order: 57,
  },
  {
    id: "book-madarij",
    title: "مدارج السالكين بين منازل إياك نعبد وإياك نستعين",
    author: "الإمام ابن قيم الجوزية",
    type: "كتاب",
    category: "رقائق",
    description: "موسوعة في سلوك الطريق إلى الله ومنازل العبودية والتزكية.",
    parts_label: "3 أجزاء",
    status: "approved",
    keywords: ["مدارج السالكين", "ابن القيم", "تزكية", "سلوك", "رقائق"],
    sort_order: 58,
  },
  // ── سيرة (إضافة) ─────────────────────────────────────────────────
  {
    id: "book-sirah-halabiyya",
    title: "إنسان العيون (السيرة الحلبية)",
    author: "علي بن برهان الدين الحلبي",
    type: "كتاب",
    category: "سيرة",
    description: "من أوسع كتب السيرة النبوية تفصيلاً وشمولاً للجوانب المختلفة من حياة النبي ﷺ.",
    parts_label: "3 أجزاء",
    status: "approved",
    keywords: ["السيرة الحلبية", "سيرة", "النبي ﷺ"],
    sort_order: 59,
  },
  {
    id: "book-sirah-dahlawi",
    title: "إزالة الخفاء عن خلافة الخلفاء",
    author: "الشاه ولي الله الدهلوي",
    type: "كتاب",
    category: "سيرة",
    description: "يُعنى بتاريخ الخلافة الراشدة وجوانبها الفقهية والتاريخية.",
    status: "approved",
    keywords: ["الدهلوي", "الخلافة", "تاريخ", "سيرة"],
    sort_order: 60,
  },
  // ── آداب ورقائق (إضافة) ───────────────────────────────────────────
  {
    id: "book-ihya",
    title: "إحياء علوم الدين",
    author: "الإمام أبو حامد الغزالي",
    type: "كتاب",
    category: "رقائق",
    description: "موسوعة في العلوم الشرعية والتصوف والتزكية، من أشهر كتب الإسلام.",
    parts_label: "4 أجزاء",
    status: "approved",
    keywords: ["إحياء العلوم", "الغزالي", "تزكية", "أخلاق", "رقائق"],
    sort_order: 61,
  },
  {
    id: "book-tawbah-ibn-qudamah",
    title: "التوابين",
    author: "الإمام ابن قدامة المقدسي",
    type: "كتاب",
    category: "رقائق",
    description: "كتاب في قصص التائبين يحثّ على التوبة بذكر أخبار من تابوا وقُبلت توبتهم.",
    status: "approved",
    keywords: ["التوابين", "ابن قدامة", "توبة", "رقائق"],
    sort_order: 62,
  },
  {
    id: "book-risala-muawiyah",
    title: "الرسالة القشيرية",
    author: "الإمام القشيري",
    type: "كتاب",
    category: "رقائق",
    description: "من أشهر كتب التصوف السني، يعرض مقامات السلوك وأخلاق الصوفية.",
    status: "approved",
    keywords: ["القشيرية", "القشيري", "تصوف", "مقامات", "سلوك"],
    sort_order: 63,
  },
  // ── أصول الفقه (إضافة) ────────────────────────────────────────────
  {
    id: "book-waraqat",
    title: "الورقات في أصول الفقه",
    author: "إمام الحرمين الجويني",
    type: "متن",
    category: "أصول الفقه",
    description: "متن مختصر في أصول الفقه من أشهر المتون المدروسة في المدارس الشرعية.",
    status: "approved",
    keywords: ["الورقات", "الجويني", "أصول الفقه", "متن"],
    sort_order: 64,
  },
  {
    id: "book-mukhtar-sagheer",
    title: "مختصر الروضة",
    author: "الإمام الطوفي",
    type: "كتاب",
    category: "أصول الفقه",
    description: "اختصار لروضة الناظر لابن قدامة في أصول الفقه الحنبلي.",
    status: "approved",
    keywords: ["أصول الفقه", "الطوفي", "حنبلي"],
    sort_order: 65,
  },
  // ── علوم القرآن (إضافة) ──────────────────────────────────────────
  {
    id: "book-itqan",
    title: "الإتقان في علوم القرآن",
    author: "الإمام جلال الدين السيوطي",
    type: "كتاب",
    category: "علوم القرآن",
    description: "موسوعة في علوم القرآن من أشمل ما كُتب في هذا الفن.",
    parts_label: "جزآن",
    status: "approved",
    keywords: ["الإتقان", "السيوطي", "علوم القرآن", "ناسخ", "منسوخ"],
    sort_order: 66,
  },
  {
    id: "book-tibyan-nawawi",
    title: "التبيان في آداب حملة القرآن",
    author: "الإمام النووي",
    type: "كتاب",
    category: "علوم القرآن",
    description: "كتاب في آداب تلاوة القرآن وحفظه وتعليمه وتعلمه.",
    status: "approved",
    keywords: ["التبيان", "النووي", "آداب القرآن", "حفظ", "تلاوة"],
    sort_order: 67,
  },
  // ── مصطلح الحديث (إضافة) ─────────────────────────────────────────
  {
    id: "book-nukhbah",
    title: "نخبة الفكر في مصطلح أهل الأثر",
    author: "الحافظ ابن حجر العسقلاني",
    type: "متن",
    category: "مصطلح الحديث",
    description: "متن مختصر في مصطلح الحديث يُعدّ من أفضل الكتب المبتدئة في هذا الفن.",
    status: "approved",
    keywords: ["نخبة الفكر", "ابن حجر", "مصطلح الحديث", "علوم الحديث"],
    sort_order: 68,
  },
  {
    id: "book-bayquniyya",
    title: "المنظومة البيقونية",
    author: "عمر بن محمد البيقوني",
    type: "متن",
    category: "مصطلح الحديث",
    description: "أرجوزة صغيرة في مصطلح الحديث تذكر أنواع الحديث في أبيات.",
    status: "approved",
    keywords: ["البيقونية", "مصطلح الحديث", "منظومة", "أنواع الحديث"],
    sort_order: 69,
  },
  // ── لغة (إضافة) ───────────────────────────────────────────────────
  {
    id: "book-ajurrumiyya",
    title: "الآجرومية",
    author: "محمد بن محمد بن داود الصنهاجي",
    type: "متن",
    category: "لغة",
    description: "متن مختصر في النحو العربي يُدرَّس للمبتدئين في كل مكان.",
    status: "approved",
    keywords: ["الآجرومية", "نحو", "لغة عربية", "متن", "مبتدئ"],
    sort_order: 70,
  },
  {
    id: "book-alfiyya",
    title: "ألفية ابن مالك",
    author: "الإمام ابن مالك الأندلسي",
    type: "منظومة",
    category: "لغة",
    description: "ألف بيت في النحو والصرف، من أهم المنظومات اللغوية وأوسعها انتشاراً.",
    status: "approved",
    keywords: ["ألفية ابن مالك", "نحو", "صرف", "لغة عربية", "منظومة"],
    sort_order: 71,
  },
  {
    id: "book-sarf-mutah",
    title: "متن مراح الأرواح في علم الصرف",
    author: "أحمد بن علي بن مسعود",
    type: "متن",
    category: "لغة",
    description: "متن في الصرف يُعدّ من أشهر الكتب التعليمية في هذا الفن.",
    status: "approved",
    keywords: ["الصرف", "مراح الأرواح", "لغة عربية", "متن"],
    sort_order: 72,
  },
  // ── منطق وفلسفة (إضافة) ──────────────────────────────────────────
  {
    id: "book-muqaddimah",
    title: "المقدمة",
    author: "الإمام ابن خلدون",
    type: "كتاب",
    category: "منطق وفلسفة",
    description: "مقدمة موسوعية لكتاب العبر، تؤسس لعلم الاجتماع والتاريخ ببنية فلسفية فريدة.",
    status: "approved",
    keywords: ["المقدمة", "ابن خلدون", "تاريخ", "اجتماع", "فلسفة"],
    sort_order: 73,
  },
  {
    id: "book-dara-at-taarus",
    title: "درء تعارض العقل والنقل",
    author: "شيخ الإسلام ابن تيمية",
    type: "كتاب",
    category: "منطق وفلسفة",
    description: "عمل ضخم يردّ فيه ابن تيمية على من زعم تعارض صريح العقل ومقتضى النقل، ويبيّن أن النقل الصحيح لا يعارض العقل الصريح أبداً.",
    parts_label: "12 جزءاً",
    status: "approved",
    keywords: ["درء تعارض", "ابن تيمية", "عقل ونقل", "فلسفة إسلامية", "الكلام"],
    sort_order: 74,
  },
  {
    id: "book-isaghoji",
    title: "إيساغوجي في المنطق",
    author: "أثير الدين الأبهري",
    type: "متن",
    category: "منطق وفلسفة",
    description: "مختصر متداول في المنطق الأرسطي يُعدّ من أبرز المقدمات لهذا العلم في التراث الإسلامي.",
    status: "approved",
    keywords: ["إيساغوجي", "الأبهري", "منطق", "متن"],
    sort_order: 75,
  },
  // ── آداب (توسعة) ──────────────────────────────────────────────────
  {
    id: "book-adab-al-mufrad",
    title: "الأدب المفرد",
    author: "الإمام محمد بن إسماعيل البخاري",
    type: "كتاب",
    category: "آداب",
    description: "جمع البخاري في هذا الكتاب أحاديث النبي ﷺ في الآداب والأخلاق والمعاملات اليومية.",
    status: "approved",
    keywords: ["الأدب المفرد", "البخاري", "آداب", "أخلاق", "حديث"],
    sort_order: 76,
  },
  {
    id: "book-risalat-al-qushayri",
    title: "الرسالة القشيرية",
    author: "الإمام أبو القاسم القشيري",
    type: "كتاب",
    category: "آداب",
    description: "مرجع كلاسيكي في آداب الطريق الروحي والتزكية، يجمع تعريفات المصطلحات وأقوال الصالحين.",
    status: "approved",
    keywords: ["الرسالة القشيرية", "التصوف", "تزكية", "آداب", "القشيري"],
    sort_order: 77,
  },
  {
    id: "book-mukhtar-al-sihah",
    title: "مختار الصحاح",
    author: "محمد بن أبي بكر الرازي",
    type: "معجم",
    category: "لغة",
    description: "مختصر نافع من الصحاح للجوهري، يُرجع إليه في معرفة أصول الكلمات ودلالاتها في اللغة العربية.",
    status: "approved",
    keywords: ["مختار الصحاح", "الرازي", "معجم", "لغة عربية"],
    sort_order: 78,
  },
  // ── مصطلح الحديث (توسعة) ─────────────────────────────────────────
  {
    id: "book-taqrib-al-tayseer",
    title: "التقريب والتيسير لمعرفة سنن البشير النذير",
    author: "الإمام يحيى بن شرف النووي",
    type: "كتاب",
    category: "مصطلح الحديث",
    description: "مختصر كتاب ابن الصلاح في علوم الحديث، يُعدّ من أيسر المصنفات وأجمعها في هذا الفن.",
    status: "approved",
    keywords: ["التقريب والتيسير", "النووي", "مصطلح الحديث", "ابن الصلاح"],
    sort_order: 79,
  },
  {
    id: "book-al-irshaad",
    title: "الإرشاد في معرفة علماء الحديث",
    author: "الإمام أبو يعلى الخليل بن عبد الله الخليلي",
    type: "كتاب",
    category: "مصطلح الحديث",
    description: "كتاب جامع في معرفة رجال الحديث وأحوالهم، يتناول طبقات المحدثين من الصحابة إلى عصر المؤلف.",
    status: "approved",
    keywords: ["الإرشاد", "الخليلي", "رجال الحديث", "طبقات", "مصطلح"],
    sort_order: 80,
  },
];
