/** أسئلة وتصنيفات إضافية للإطلاق — تُدمج مع qa-seed */

export const QA_EXTRA_CATEGORIES = [
  { id: "seed-cat-fiqh", name: "الفقه", slug: "fiqh" },
  { id: "seed-cat-tafsir", name: "التفسير", slug: "tafsir" },
  { id: "seed-cat-akhlaq", name: "الأخلاق", slug: "akhlaq" },
  { id: "seed-cat-taharah", name: "الطهارة", slug: "taharah" },
  { id: "seed-cat-janaiz", name: "الجنائز", slug: "janaiz" },
  { id: "seed-cat-nikah", name: "النكاح", slug: "nikah" },
  { id: "seed-cat-buyu", name: "البيوع", slug: "buyu" },
  { id: "seed-cat-food", name: "الأطعمة", slug: "food" },
  { id: "seed-cat-libas", name: "اللباس", slug: "libas" },
  { id: "seed-cat-adhkar-cat", name: "الأذكار", slug: "adhkar" },
] as const;

export const QA_EXTRA = [
  {
    id: "seed-qa-extra-1",
    question: "ما حكم ترك الوضوء عمدًا ثم الصلاة؟",
    answer: "الجواب: لا تصح الصلاة بدون طهارة، ويجب إعادتها بعد الوضوء.",
    category_id: "seed-cat-taharah",
    ruling_type: null,
    evidence: null,
    reference: "من فقه الطهارة المعروف",
    status: "published",
    review_status: "approved",
    created_at: "2024-02-01T09:00:00.000Z",
    qa_categories: { name: "الطهارة", slug: "taharah" },
  },
  {
    id: "seed-qa-extra-2",
    question: "هل يجوز للمرأة أن تصلي في البيت؟",
    answer: "الجواب: نعم، صلاتها في البيت أفضل لها إلا من حاجة.",
    category_id: "seed-cat-salah",
    ruling_type: "مباح",
    evidence: null,
    reference: "من فقه الصلاة",
    status: "published",
    review_status: "approved",
    created_at: "2024-02-01T10:00:00.000Z",
    qa_categories: { name: "الصلاة", slug: "salah" },
  },
  {
    id: "seed-qa-extra-3",
    question: "ما معنى «إياك نعبد وإياك نستعين»؟",
    answer: "الجواب: نخصك وحدك بالعبادة، ونطلب منك وحدك النصر والتوفيق.",
    category_id: "seed-cat-tafsir",
    ruling_type: null,
    evidence: "سورة الفاتحة — 5",
    reference: "تفسير ابن كثير",
    status: "published",
    review_status: "approved",
    created_at: "2024-02-01T11:00:00.000Z",
    qa_categories: { name: "التفسير", slug: "tafsir" },
  },
  {
    id: "seed-qa-extra-4",
    question: "ما أهم صفات المؤمن في معاملته؟",
    answer: "الجواب: الصدق، الأمانة، حسن الخلق، والوفاء بالعهد.",
    category_id: "seed-cat-akhlaq",
    ruling_type: null,
    evidence: null,
    reference: "من آداب الإسلام",
    status: "published",
    review_status: "approved",
    created_at: "2024-02-01T12:00:00.000Z",
    qa_categories: { name: "الأخلاق", slug: "akhlaq" },
  },
  {
    id: "seed-qa-extra-5",
    question: "ما حكم الصيام في رمضان؟",
    answer: "الجواب: فرض على كل مسلم بالغ عاقل قادر.",
    category_id: "seed-cat-sawm",
    ruling_type: "فرض",
    evidence: null,
    reference: "من فقه الصيام",
    status: "published",
    review_status: "approved",
    created_at: "2024-02-01T13:00:00.000Z",
    qa_categories: { name: "الصيام", slug: "sawm" },
  },
  {
    id: "seed-qa-extra-6",
    question: "ما حكم أكل لحم الحيوان المذبوح على غير ذكر الله؟",
    answer: "الجواب: لا يحل أكله؛ لقوله تعالى: ﴿وَلَا تَأْكُلُوا مِمَّا لَمْ يُذْكَرِ اسْمُ اللَّهِ عَلَيْهِ﴾.",
    category_id: "seed-cat-food",
    ruling_type: "حرام",
    evidence: "سورة الأنعام — 121",
    reference: "من فقه الأطعمة",
    status: "published",
    review_status: "approved",
    created_at: "2024-02-01T14:00:00.000Z",
    qa_categories: { name: "الأطعمة", slug: "food" },
  },
  {
    id: "seed-qa-extra-7",
    question: "هل يجوز للرجل لبس الذهب؟",
    answer: "الجواب: لا يجوز للرجل لبس الذهب؛ لما ثبت عن النبي ﷺ في النهي عنه.",
    category_id: "seed-cat-libas",
    ruling_type: "حرام",
    evidence: null,
    reference: "من فقه اللباس",
    status: "published",
    review_status: "approved",
    created_at: "2024-02-01T15:00:00.000Z",
    qa_categories: { name: "اللباس", slug: "libas" },
  },
  {
    id: "seed-qa-extra-8",
    question: "ما حكم الدعاء بعد الصلاة؟",
    answer: "الجواب: مشروع؛ من الأذكار المأثورة بعد الفرض.",
    category_id: "seed-cat-adhkar-cat",
    ruling_type: "سنة",
    evidence: null,
    reference: "حصن المسلم",
    status: "published",
    review_status: "approved",
    created_at: "2024-02-01T16:00:00.000Z",
    qa_categories: { name: "الأذكار", slug: "adhkar" },
  },
  {
    id: "seed-qa-extra-9",
    question: "ما حكم الصلاة على الميت؟",
    answer: "الجواب: فرض كفاية؛ إذا قام بها البعض سقط الإثم عن الباقين.",
    category_id: "seed-cat-janaiz",
    ruling_type: "فرض",
    evidence: null,
    reference: "من فقه الجنائز",
    status: "published",
    review_status: "approved",
    created_at: "2024-02-01T17:00:00.000Z",
    qa_categories: { name: "الجنائز", slug: "janaiz" },
  },
  {
    id: "seed-qa-extra-10",
    question: "ما شروط صحة النكاح؟",
    answer: "الجواب: منها: الولي، الصداق، الشهود، وعدم الموانع الشرعية.",
    category_id: "seed-cat-nikah",
    ruling_type: null,
    evidence: null,
    reference: "من فقه النكاح",
    status: "published",
    review_status: "approved",
    created_at: "2024-02-01T18:00:00.000Z",
    qa_categories: { name: "النكاح", slug: "nikah" },
  },
];
