// Auto-generated by scripts/generate-content-seed.mjs — do not edit manually
import { arabicMatchAny } from "./arabic-search";

export const QA_CATEGORIES = [
  {
    "id": "seed-cat-aqeedah",
    "name": "العقيدة",
    "slug": "aqeedah"
  },
  {
    "id": "seed-cat-tahara",
    "name": "الطهارة",
    "slug": "tahara"
  },
  {
    "id": "seed-cat-salah",
    "name": "الصلاة",
    "slug": "salah"
  },
  {
    "id": "seed-cat-zakat",
    "name": "الزكاة",
    "slug": "zakat"
  },
  {
    "id": "seed-cat-sawm",
    "name": "الصيام",
    "slug": "sawm"
  },
  {
    "id": "seed-cat-hajj",
    "name": "الحج",
    "slug": "hajj"
  },
  {
    "id": "seed-cat-seerah",
    "name": "السيرة",
    "slug": "seerah"
  },
  {
    "id": "seed-cat-quran",
    "name": "القرآن",
    "slug": "quran"
  },
  {
    "id": "seed-cat-hadith",
    "name": "الحديث",
    "slug": "hadith"
  },
  {
    "id": "seed-cat-adhkar",
    "name": "الأذكار",
    "slug": "adhkar"
  },
  {
    "id": "seed-cat-adab",
    "name": "الآداب",
    "slug": "adab"
  }
] as const;

export const SEED_QA = [
  {
    "id": "seed-qa-1",
    "question": "من أول الرسل إلى أهل الأرض بعد آدم؟",
    "answer": "الجواب: نوح عليه السلام.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T09:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-2",
    "question": "من النبي الذي اتخذه الله خليلاً؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T10:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-3",
    "question": "من النبي الذي كلمه الله تكليماً؟",
    "answer": "الجواب: موسى عليه السلام.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T11:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-4",
    "question": "من النبي الذي أرسل إلى قوم عاد؟",
    "answer": "الجواب: هود عليه السلام.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T12:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-5",
    "question": "من النبي الذي أرسل إلى قوم ثمود؟",
    "answer": "الجواب: صالح عليه السلام.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T13:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-6",
    "question": "من النبي الذي ابتلعه الحوت؟",
    "answer": "الجواب: يونس عليه السلام.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T14:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-7",
    "question": "من النبي الذي رفعه الله إليه؟",
    "answer": "الجواب: عيسى عليه السلام.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T15:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-8",
    "question": "من والد إسماعيل عليه السلام؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T16:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-9",
    "question": "من النبي الذي سخر الله له الريح؟",
    "answer": "الجواب: سليمان عليه السلام.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T17:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-10",
    "question": "من النبي الذي اشتهر بالصبر على البلاء؟",
    "answer": "الجواب: أيوب عليه السلام.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T18:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-11",
    "question": "من أول الخلفاء الراشدين؟",
    "answer": "الجواب: أبو بكر الصديق.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T19:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-12",
    "question": "من ثاني الخلفاء الراشدين؟",
    "answer": "الجواب: عمر بن الخطاب.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T20:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-13",
    "question": "من ثالث الخلفاء الراشدين؟",
    "answer": "الجواب: عثمان بن عفان.",
    "category_id": "seed-cat-aqeedah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T21:00:00.000Z",
    "qa_categories": {
      "name": "العقيدة",
      "slug": "aqeedah"
    }
  },
  {
    "id": "seed-qa-14",
    "question": "بماذا يتطهر المسلم عند عدم وجود الماء؟",
    "answer": "الجواب: التيمم.",
    "category_id": "seed-cat-tahara",
    "ruling_type": "واجب",
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T22:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-15",
    "question": "ما الطهارة المطلوبة قبل الصلاة؟",
    "answer": "الجواب: الوضوء.",
    "category_id": "seed-cat-tahara",
    "ruling_type": "واجب",
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-01T23:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-16",
    "question": "ما حكم من نسي مسح رأسه في الوضوء؟",
    "answer": "الجواب: يجوز؛ فإن مسح بعض الرأس يكفي عن الكل.",
    "category_id": "seed-cat-tahara",
    "ruling_type": "واجب",
    "evidence": "السنة",
    "reference": "متفق عليه",
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T00:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-17",
    "question": "هل يجوز الوضوء بماء مغلوب عليه؟",
    "answer": "الجواب: نعم؛ ما لم يتغير اسمه أو صفته.",
    "category_id": "seed-cat-tahara",
    "ruling_type": "جائز",
    "evidence": "الإجماع",
    "reference": "الفقه العام",
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T01:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-18",
    "question": "ما حكم ترك غسل جزء من الوجه في الوضوء؟",
    "answer": "الجواب: لا يصح الوضوء حتى يُغسل الجزء.",
    "category_id": "seed-cat-tahara",
    "ruling_type": "واجب",
    "evidence": "القرآن والسنة",
    "reference": "الفقه",
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T02:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-19",
    "question": "هل يجوز التيمم قبل وقت الصلاة؟",
    "answer": "الجواب: نعم عند فقد الماء أو العجز عن استعماله.",
    "category_id": "seed-cat-tahara",
    "ruling_type": "جائز",
    "evidence": "القرآن",
    "reference": "سورة المائدة",
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T03:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-20",
    "question": "ما حكم من شك في عدد غسلات الوضوء؟",
    "answer": "الجواب: يبني على اليقين؛ وهو الأقل.",
    "category_id": "seed-cat-tahara",
    "ruling_type": "واجب",
    "evidence": "السنة",
    "reference": "البيهقي",
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T04:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-21",
    "question": "من أول الرسل إلى أهل الأرض بعد آدم؟",
    "answer": "الجواب: نوح عليه السلام.",
    "category_id": "seed-cat-tahara",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T05:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-22",
    "question": "من النبي الذي اتخذه الله خليلاً؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-tahara",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T06:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-23",
    "question": "من النبي الذي كلمه الله تكليماً؟",
    "answer": "الجواب: موسى عليه السلام.",
    "category_id": "seed-cat-tahara",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T07:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-24",
    "question": "من النبي الذي أرسل إلى قوم عاد؟",
    "answer": "الجواب: هود عليه السلام.",
    "category_id": "seed-cat-tahara",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T08:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-25",
    "question": "من النبي الذي أرسل إلى قوم ثمود؟",
    "answer": "الجواب: صالح عليه السلام.",
    "category_id": "seed-cat-tahara",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T09:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-26",
    "question": "من النبي الذي ابتلعه الحوت؟",
    "answer": "الجواب: يونس عليه السلام.",
    "category_id": "seed-cat-tahara",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T10:00:00.000Z",
    "qa_categories": {
      "name": "الطهارة",
      "slug": "tahara"
    }
  },
  {
    "id": "seed-qa-27",
    "question": "ما أول ما يحاسب عليه العبد من عمله؟",
    "answer": "الجواب: الصلاة.",
    "category_id": "seed-cat-salah",
    "ruling_type": "واجب",
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T11:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-28",
    "question": "كم عدد الصلوات المفروضة في اليوم والليلة؟",
    "answer": "الجواب: خمس صلوات.",
    "category_id": "seed-cat-salah",
    "ruling_type": "واجب",
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T12:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-29",
    "question": "ما القبلة التي يتجه إليها المسلمون في الصلاة؟",
    "answer": "الجواب: الكعبة.",
    "category_id": "seed-cat-salah",
    "ruling_type": "واجب",
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T13:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-30",
    "question": "من أول الرسل إلى أهل الأرض بعد آدم؟",
    "answer": "الجواب: نوح عليه السلام.",
    "category_id": "seed-cat-salah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T14:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-31",
    "question": "من النبي الذي اتخذه الله خليلاً؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-salah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T15:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-32",
    "question": "من النبي الذي كلمه الله تكليماً؟",
    "answer": "الجواب: موسى عليه السلام.",
    "category_id": "seed-cat-salah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T16:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-33",
    "question": "من النبي الذي أرسل إلى قوم عاد؟",
    "answer": "الجواب: هود عليه السلام.",
    "category_id": "seed-cat-salah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T17:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-34",
    "question": "من النبي الذي أرسل إلى قوم ثمود؟",
    "answer": "الجواب: صالح عليه السلام.",
    "category_id": "seed-cat-salah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T18:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-35",
    "question": "من النبي الذي ابتلعه الحوت؟",
    "answer": "الجواب: يونس عليه السلام.",
    "category_id": "seed-cat-salah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T19:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-36",
    "question": "من النبي الذي رفعه الله إليه؟",
    "answer": "الجواب: عيسى عليه السلام.",
    "category_id": "seed-cat-salah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T20:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-37",
    "question": "من والد إسماعيل عليه السلام؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-salah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T21:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-38",
    "question": "من النبي الذي سخر الله له الريح؟",
    "answer": "الجواب: سليمان عليه السلام.",
    "category_id": "seed-cat-salah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T22:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-39",
    "question": "من النبي الذي اشتهر بالصبر على البلاء؟",
    "answer": "الجواب: أيوب عليه السلام.",
    "category_id": "seed-cat-salah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-02T23:00:00.000Z",
    "qa_categories": {
      "name": "الصلاة",
      "slug": "salah"
    }
  },
  {
    "id": "seed-qa-40",
    "question": "ما العبادة المالية الواجبة على المال بشروطها؟",
    "answer": "الجواب: الزكاة.",
    "category_id": "seed-cat-zakat",
    "ruling_type": "واجب",
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T00:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-41",
    "question": "من أول الرسل إلى أهل الأرض بعد آدم؟",
    "answer": "الجواب: نوح عليه السلام.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T01:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-42",
    "question": "من النبي الذي اتخذه الله خليلاً؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T02:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-43",
    "question": "من النبي الذي كلمه الله تكليماً؟",
    "answer": "الجواب: موسى عليه السلام.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T03:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-44",
    "question": "من النبي الذي أرسل إلى قوم عاد؟",
    "answer": "الجواب: هود عليه السلام.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T04:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-45",
    "question": "من النبي الذي أرسل إلى قوم ثمود؟",
    "answer": "الجواب: صالح عليه السلام.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T05:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-46",
    "question": "من النبي الذي ابتلعه الحوت؟",
    "answer": "الجواب: يونس عليه السلام.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T06:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-47",
    "question": "من النبي الذي رفعه الله إليه؟",
    "answer": "الجواب: عيسى عليه السلام.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T07:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-48",
    "question": "من والد إسماعيل عليه السلام؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T08:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-49",
    "question": "من النبي الذي سخر الله له الريح؟",
    "answer": "الجواب: سليمان عليه السلام.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T09:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-50",
    "question": "من النبي الذي اشتهر بالصبر على البلاء؟",
    "answer": "الجواب: أيوب عليه السلام.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T10:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-51",
    "question": "من أول الخلفاء الراشدين؟",
    "answer": "الجواب: أبو بكر الصديق.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T11:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-52",
    "question": "من ثاني الخلفاء الراشدين؟",
    "answer": "الجواب: عمر بن الخطاب.",
    "category_id": "seed-cat-zakat",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T12:00:00.000Z",
    "qa_categories": {
      "name": "الزكاة",
      "slug": "zakat"
    }
  },
  {
    "id": "seed-qa-53",
    "question": "في أي شهر يصوم المسلمون؟",
    "answer": "الجواب: رمضان.",
    "category_id": "seed-cat-sawm",
    "ruling_type": "واجب",
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T13:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-54",
    "question": "ما الوجبة التي تكون قبل الفجر للصائم؟",
    "answer": "الجواب: السحور.",
    "category_id": "seed-cat-sawm",
    "ruling_type": "واجب",
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T14:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-55",
    "question": "من أول الرسل إلى أهل الأرض بعد آدم؟",
    "answer": "الجواب: نوح عليه السلام.",
    "category_id": "seed-cat-sawm",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T15:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-56",
    "question": "من النبي الذي اتخذه الله خليلاً؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-sawm",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T16:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-57",
    "question": "من النبي الذي كلمه الله تكليماً؟",
    "answer": "الجواب: موسى عليه السلام.",
    "category_id": "seed-cat-sawm",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T17:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-58",
    "question": "من النبي الذي أرسل إلى قوم عاد؟",
    "answer": "الجواب: هود عليه السلام.",
    "category_id": "seed-cat-sawm",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T18:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-59",
    "question": "من النبي الذي أرسل إلى قوم ثمود؟",
    "answer": "الجواب: صالح عليه السلام.",
    "category_id": "seed-cat-sawm",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T19:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-60",
    "question": "من النبي الذي ابتلعه الحوت؟",
    "answer": "الجواب: يونس عليه السلام.",
    "category_id": "seed-cat-sawm",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T20:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-61",
    "question": "من النبي الذي رفعه الله إليه؟",
    "answer": "الجواب: عيسى عليه السلام.",
    "category_id": "seed-cat-sawm",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T21:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-62",
    "question": "من والد إسماعيل عليه السلام؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-sawm",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T22:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-63",
    "question": "من النبي الذي سخر الله له الريح؟",
    "answer": "الجواب: سليمان عليه السلام.",
    "category_id": "seed-cat-sawm",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-03T23:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-64",
    "question": "من النبي الذي اشتهر بالصبر على البلاء؟",
    "answer": "الجواب: أيوب عليه السلام.",
    "category_id": "seed-cat-sawm",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T00:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-65",
    "question": "من أول الخلفاء الراشدين؟",
    "answer": "الجواب: أبو بكر الصديق.",
    "category_id": "seed-cat-sawm",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T01:00:00.000Z",
    "qa_categories": {
      "name": "الصيام",
      "slug": "sawm"
    }
  },
  {
    "id": "seed-qa-66",
    "question": "ما الركن الأعظم في الحج؟",
    "answer": "الجواب: الوقوف بعرفة.",
    "category_id": "seed-cat-hajj",
    "ruling_type": "واجب",
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T02:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-67",
    "question": "ما البيت الذي يقصده المسلمون في الحج؟",
    "answer": "الجواب: الكعبة.",
    "category_id": "seed-cat-hajj",
    "ruling_type": "واجب",
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T03:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-68",
    "question": "من أول الرسل إلى أهل الأرض بعد آدم؟",
    "answer": "الجواب: نوح عليه السلام.",
    "category_id": "seed-cat-hajj",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T04:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-69",
    "question": "من النبي الذي اتخذه الله خليلاً؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-hajj",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T05:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-70",
    "question": "من النبي الذي كلمه الله تكليماً؟",
    "answer": "الجواب: موسى عليه السلام.",
    "category_id": "seed-cat-hajj",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T06:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-71",
    "question": "من النبي الذي أرسل إلى قوم عاد؟",
    "answer": "الجواب: هود عليه السلام.",
    "category_id": "seed-cat-hajj",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T07:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-72",
    "question": "من النبي الذي أرسل إلى قوم ثمود؟",
    "answer": "الجواب: صالح عليه السلام.",
    "category_id": "seed-cat-hajj",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T08:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-73",
    "question": "من النبي الذي ابتلعه الحوت؟",
    "answer": "الجواب: يونس عليه السلام.",
    "category_id": "seed-cat-hajj",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T09:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-74",
    "question": "من النبي الذي رفعه الله إليه؟",
    "answer": "الجواب: عيسى عليه السلام.",
    "category_id": "seed-cat-hajj",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T10:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-75",
    "question": "من والد إسماعيل عليه السلام؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-hajj",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T11:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-76",
    "question": "من النبي الذي سخر الله له الريح؟",
    "answer": "الجواب: سليمان عليه السلام.",
    "category_id": "seed-cat-hajj",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T12:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-77",
    "question": "من النبي الذي اشتهر بالصبر على البلاء؟",
    "answer": "الجواب: أيوب عليه السلام.",
    "category_id": "seed-cat-hajj",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T13:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-78",
    "question": "من أول الخلفاء الراشدين؟",
    "answer": "الجواب: أبو بكر الصديق.",
    "category_id": "seed-cat-hajj",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T14:00:00.000Z",
    "qa_categories": {
      "name": "الحج",
      "slug": "hajj"
    }
  },
  {
    "id": "seed-qa-79",
    "question": "من أول الخلفاء الراشدين؟",
    "answer": "الجواب: أبو بكر الصديق.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T15:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-80",
    "question": "من ثاني الخلفاء الراشدين؟",
    "answer": "الجواب: عمر بن الخطاب.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T16:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-81",
    "question": "من ثالث الخلفاء الراشدين؟",
    "answer": "الجواب: عثمان بن عفان.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T17:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-82",
    "question": "من رابع الخلفاء الراشدين؟",
    "answer": "الجواب: علي بن أبي طالب.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T18:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-83",
    "question": "من الصحابي الملقب بذي النورين؟",
    "answer": "الجواب: عثمان بن عفان.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T19:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-84",
    "question": "من الصحابي الملقب بالفاروق؟",
    "answer": "الجواب: عمر بن الخطاب.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T20:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-85",
    "question": "من أول الرجال إسلاماً؟",
    "answer": "الجواب: أبو بكر الصديق.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T21:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-86",
    "question": "من أول الصبيان إسلاماً؟",
    "answer": "الجواب: علي بن أبي طالب.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T22:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-87",
    "question": "من أم المؤمنين ابنة أبي بكر؟",
    "answer": "الجواب: عائشة رضي الله عنها.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-04T23:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-88",
    "question": "في أي غار نزل الوحي أول مرة؟",
    "answer": "الجواب: غار حراء.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T00:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-89",
    "question": "من أول من آمن من النساء؟",
    "answer": "الجواب: خديجة بنت خويلد.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T01:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-90",
    "question": "إلى أي مدينة هاجر النبي صلى الله عليه وسلم؟",
    "answer": "الجواب: المدينة المنورة.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T02:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-91",
    "question": "من صاحب النبي صلى الله عليه وسلم في الهجرة؟",
    "answer": "الجواب: أبو بكر الصديق.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T03:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-92",
    "question": "ما أول مسجد أسسه النبي صلى الله عليه وسلم بعد الهجرة؟",
    "answer": "الجواب: مسجد قباء.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T04:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-93",
    "question": "ما أول غزوة كبرى في الإسلام؟",
    "answer": "الجواب: غزوة بدر.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T05:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-94",
    "question": "في أي غزوة وقع حفر الخندق؟",
    "answer": "الجواب: غزوة الخندق.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T06:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-95",
    "question": "ما الغزوة التي وقعت في السنة الثالثة للهجرة؟",
    "answer": "الجواب: غزوة أحد.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T07:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-96",
    "question": "ما اسم الصلح الذي عقده النبي صلى الله عليه وسلم مع قريش؟",
    "answer": "الجواب: صلح الحديبية.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T08:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-97",
    "question": "ما الحدث الذي دخل فيه النبي صلى الله عليه وسلم مكة فاتحاً؟",
    "answer": "الجواب: فتح مكة.",
    "category_id": "seed-cat-seerah",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T09:00:00.000Z",
    "qa_categories": {
      "name": "السيرة",
      "slug": "seerah"
    }
  },
  {
    "id": "seed-qa-98",
    "question": "من أول الرسل إلى أهل الأرض بعد آدم؟",
    "answer": "الجواب: نوح عليه السلام.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T10:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-99",
    "question": "من النبي الذي اتخذه الله خليلاً؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T11:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-100",
    "question": "من النبي الذي كلمه الله تكليماً؟",
    "answer": "الجواب: موسى عليه السلام.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T12:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-101",
    "question": "من النبي الذي أرسل إلى قوم عاد؟",
    "answer": "الجواب: هود عليه السلام.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T13:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-102",
    "question": "من النبي الذي أرسل إلى قوم ثمود؟",
    "answer": "الجواب: صالح عليه السلام.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T14:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-103",
    "question": "من النبي الذي ابتلعه الحوت؟",
    "answer": "الجواب: يونس عليه السلام.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T15:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-104",
    "question": "من النبي الذي رفعه الله إليه؟",
    "answer": "الجواب: عيسى عليه السلام.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T16:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-105",
    "question": "من والد إسماعيل عليه السلام؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T17:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-106",
    "question": "من النبي الذي سخر الله له الريح؟",
    "answer": "الجواب: سليمان عليه السلام.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T18:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-107",
    "question": "من النبي الذي اشتهر بالصبر على البلاء؟",
    "answer": "الجواب: أيوب عليه السلام.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T19:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-108",
    "question": "من أول الخلفاء الراشدين؟",
    "answer": "الجواب: أبو بكر الصديق.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T20:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-109",
    "question": "من ثاني الخلفاء الراشدين؟",
    "answer": "الجواب: عمر بن الخطاب.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T21:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-110",
    "question": "من ثالث الخلفاء الراشدين؟",
    "answer": "الجواب: عثمان بن عفان.",
    "category_id": "seed-cat-quran",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T22:00:00.000Z",
    "qa_categories": {
      "name": "القرآن",
      "slug": "quran"
    }
  },
  {
    "id": "seed-qa-111",
    "question": "من أكثر الصحابة رواية للحديث؟",
    "answer": "الجواب: أبو هريرة.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-05T23:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-112",
    "question": "من مؤسس المذهب الحنفي؟",
    "answer": "الجواب: أبو حنيفة النعمان.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T00:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-113",
    "question": "من مؤسس المذهب المالكي؟",
    "answer": "الجواب: مالك بن أنس.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T01:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-114",
    "question": "من مؤسس المذهب الشافعي؟",
    "answer": "الجواب: محمد بن إدريس الشافعي.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T02:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-115",
    "question": "من مؤسس المذهب الحنبلي؟",
    "answer": "الجواب: أحمد بن حنبل.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T03:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-116",
    "question": "من صاحب صحيح البخاري؟",
    "answer": "الجواب: محمد بن إسماعيل البخاري.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T04:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-117",
    "question": "من صاحب صحيح مسلم؟",
    "answer": "الجواب: مسلم بن الحجاج.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T05:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-118",
    "question": "من الإمام المعروف بإمام دار الهجرة؟",
    "answer": "الجواب: مالك بن أنس.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T06:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-119",
    "question": "من الإمام صاحب كتاب الموطأ؟",
    "answer": "الجواب: مالك بن أنس.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T07:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-120",
    "question": "من أول الرسل إلى أهل الأرض بعد آدم؟",
    "answer": "الجواب: نوح عليه السلام.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T08:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-121",
    "question": "من النبي الذي اتخذه الله خليلاً؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T09:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-122",
    "question": "من النبي الذي كلمه الله تكليماً؟",
    "answer": "الجواب: موسى عليه السلام.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T10:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-123",
    "question": "من النبي الذي أرسل إلى قوم عاد؟",
    "answer": "الجواب: هود عليه السلام.",
    "category_id": "seed-cat-hadith",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T11:00:00.000Z",
    "qa_categories": {
      "name": "الحديث",
      "slug": "hadith"
    }
  },
  {
    "id": "seed-qa-124",
    "question": "ما حكم قول «سبحان الله» بعد الصلاة؟",
    "answer": "الجواب: سنة مؤكدة؛ ثلاثاً وثلاثين.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": "سنة",
    "evidence": "البخاري ومسلم",
    "reference": "صحيح مسلم",
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T12:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-125",
    "question": "ما أفضل ذكر بعد الفجر؟",
    "answer": "الجواب: قراءة آية الكرسي والمعوذات.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": "سنة",
    "evidence": "السنة",
    "reference": "أبو داود",
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T13:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-126",
    "question": "هل يجوز الجهر بالأذكار بعد الصلاة؟",
    "answer": "الجواب: جائز؛ والسر أفضل إلا ما دلّ دليل على الجهر.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": "جائز",
    "evidence": "السنة",
    "reference": "الفقه",
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T14:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-127",
    "question": "ما حكم من ترك أذكار الصباح والمساء؟",
    "answer": "الجواب: فاته خير كثير؛ وليس كبيرة إذا لم يُهمل عمداً.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": null,
    "evidence": "السنة",
    "reference": "الأذكار النبوية",
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T15:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-128",
    "question": "ما فائدة الاستغفار في الأذكار؟",
    "answer": "الجواب: مغفرة الذنوب وفرج الهم.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": "مستحب",
    "evidence": "القرآن",
    "reference": "سورة نوح",
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T16:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-129",
    "question": "من أول الرسل إلى أهل الأرض بعد آدم؟",
    "answer": "الجواب: نوح عليه السلام.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T17:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-130",
    "question": "من النبي الذي اتخذه الله خليلاً؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T18:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-131",
    "question": "من النبي الذي كلمه الله تكليماً؟",
    "answer": "الجواب: موسى عليه السلام.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T19:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-132",
    "question": "من النبي الذي أرسل إلى قوم عاد؟",
    "answer": "الجواب: هود عليه السلام.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T20:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-133",
    "question": "من النبي الذي أرسل إلى قوم ثمود؟",
    "answer": "الجواب: صالح عليه السلام.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T21:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-134",
    "question": "من النبي الذي ابتلعه الحوت؟",
    "answer": "الجواب: يونس عليه السلام.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T22:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-135",
    "question": "من النبي الذي رفعه الله إليه؟",
    "answer": "الجواب: عيسى عليه السلام.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-06T23:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-136",
    "question": "من والد إسماعيل عليه السلام؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-adhkar",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T00:00:00.000Z",
    "qa_categories": {
      "name": "الأذكار",
      "slug": "adhkar"
    }
  },
  {
    "id": "seed-qa-137",
    "question": "من أول الرسل إلى أهل الأرض بعد آدم؟",
    "answer": "الجواب: نوح عليه السلام.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T01:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-138",
    "question": "من النبي الذي اتخذه الله خليلاً؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T02:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-139",
    "question": "من النبي الذي كلمه الله تكليماً؟",
    "answer": "الجواب: موسى عليه السلام.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T03:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-140",
    "question": "من النبي الذي أرسل إلى قوم عاد؟",
    "answer": "الجواب: هود عليه السلام.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T04:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-141",
    "question": "من النبي الذي أرسل إلى قوم ثمود؟",
    "answer": "الجواب: صالح عليه السلام.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T05:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-142",
    "question": "من النبي الذي ابتلعه الحوت؟",
    "answer": "الجواب: يونس عليه السلام.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T06:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-143",
    "question": "من النبي الذي رفعه الله إليه؟",
    "answer": "الجواب: عيسى عليه السلام.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T07:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-144",
    "question": "من والد إسماعيل عليه السلام؟",
    "answer": "الجواب: إبراهيم عليه السلام.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T08:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-145",
    "question": "من النبي الذي سخر الله له الريح؟",
    "answer": "الجواب: سليمان عليه السلام.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T09:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-146",
    "question": "من النبي الذي اشتهر بالصبر على البلاء؟",
    "answer": "الجواب: أيوب عليه السلام.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T10:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-147",
    "question": "من أول الخلفاء الراشدين؟",
    "answer": "الجواب: أبو بكر الصديق.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T11:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-148",
    "question": "من ثاني الخلفاء الراشدين؟",
    "answer": "الجواب: عمر بن الخطاب.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T12:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  },
  {
    "id": "seed-qa-149",
    "question": "من ثالث الخلفاء الراشدين؟",
    "answer": "الجواب: عثمان بن عفان.",
    "category_id": "seed-cat-adab",
    "ruling_type": null,
    "evidence": null,
    "reference": null,
    "status": "published",
    "review_status": "approved",
    "created_at": "2024-01-07T13:00:00.000Z",
    "qa_categories": {
      "name": "الآداب",
      "slug": "adab"
    }
  }
];

export function filterSeedQa({
  categoryId,
  search,
}: {
  categoryId?: string;
  search?: string;
}) {
  let items = SEED_QA.filter((q) => q.status === "published");
  if (categoryId && categoryId !== "all") {
    items = items.filter((q) => q.category_id === categoryId);
  }
  if (search?.trim()) {
    const s = search.trim();
    items = items.filter((q) =>
      arabicMatchAny([q.question, q.answer, q.evidence, q.reference, q.qa_categories?.name], s)
    );
  }
  return items;
}
