// Auto-generated by scripts/generate-quiz-questions.mjs — do not edit manually

export type QuizQuestion = {
  id?: string;
  section: string;
  category: string;
  level: string;
  question: string;
  answer: string;
  status?: string;
};

/** Normalize Arabic answer text for fuzzy comparison */
export function normalizeQuizAnswer(text: string) {
  return text
    .trim()
    .replace(/[\u064B-\u065F\u0670]/g, "")
    .replace(/[^\u0600-\u06FFa-zA-Z0-9\s]/g, "")
    .replace(/\s+/g, " ")
    .toLowerCase();
}

export function isQuizAnswerCorrect(input: string, expected: string) {
  const a = normalizeQuizAnswer(input);
  const b = normalizeQuizAnswer(expected);
  if (!a || !b) return false;
  if (a === b) return true;
  if (b.includes(a) && a.length >= Math.min(4, b.length)) return true;
  return false;
}

export function shuffleQuizQuestions<T>(items: T[]): T[] {
  const copy = [...items];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}
