// Auto-generated by scripts/generate-quiz-questions.mjs — do not edit manually
export type QuizQuestion = {
  id?: string;
  section: string;
  category: string;
  level: string;
  question: string;
  answer: string;
  status?: string;
};

export const DEMO_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    "id": "demo-quiz-1",
    "section": "الأنبياء",
    "category": "الرسل",
    "level": "متوسط",
    "question": "من أول الرسل إلى أهل الأرض بعد آدم؟",
    "answer": "نوح عليه السلام"
  },
  {
    "id": "demo-quiz-2",
    "section": "الأنبياء",
    "category": "الرسل",
    "level": "متوسط",
    "question": "من النبي الذي اتخذه الله خليلاً؟",
    "answer": "إبراهيم عليه السلام"
  },
  {
    "id": "demo-quiz-3",
    "section": "الأنبياء",
    "category": "الرسل",
    "level": "متوسط",
    "question": "من النبي الذي كلمه الله تكليماً؟",
    "answer": "موسى عليه السلام"
  },
  {
    "id": "demo-quiz-4",
    "section": "الأنبياء",
    "category": "الرسل",
    "level": "متوسط",
    "question": "من النبي الذي أرسل إلى قوم عاد؟",
    "answer": "هود عليه السلام"
  },
  {
    "id": "demo-quiz-5",
    "section": "الأنبياء",
    "category": "الرسل",
    "level": "متوسط",
    "question": "من النبي الذي أرسل إلى قوم ثمود؟",
    "answer": "صالح عليه السلام"
  },
  {
    "id": "demo-quiz-6",
    "section": "الأنبياء",
    "category": "الرسل",
    "level": "متوسط",
    "question": "من النبي الذي ابتلعه الحوت؟",
    "answer": "يونس عليه السلام"
  },
  {
    "id": "demo-quiz-7",
    "section": "الأنبياء",
    "category": "الرسل",
    "level": "متوسط",
    "question": "من النبي الذي رفعه الله إليه؟",
    "answer": "عيسى عليه السلام"
  },
  {
    "id": "demo-quiz-8",
    "section": "الأنبياء",
    "category": "الرسل",
    "level": "متوسط",
    "question": "من والد إسماعيل عليه السلام؟",
    "answer": "إبراهيم عليه السلام"
  },
  {
    "id": "demo-quiz-9",
    "section": "الأنبياء",
    "category": "الرسل",
    "level": "متوسط",
    "question": "من النبي الذي سخر الله له الريح؟",
    "answer": "سليمان عليه السلام"
  },
  {
    "id": "demo-quiz-10",
    "section": "الأنبياء",
    "category": "الرسل",
    "level": "متوسط",
    "question": "من النبي الذي اشتهر بالصبر على البلاء؟",
    "answer": "أيوب عليه السلام"
  },
  {
    "id": "demo-quiz-11",
    "section": "الصحابة",
    "category": "الخلفاء",
    "level": "متوسط",
    "question": "من أول الخلفاء الراشدين؟",
    "answer": "أبو بكر الصديق"
  },
  {
    "id": "demo-quiz-12",
    "section": "الصحابة",
    "category": "الخلفاء",
    "level": "متوسط",
    "question": "من ثاني الخلفاء الراشدين؟",
    "answer": "عمر بن الخطاب"
  },
  {
    "id": "demo-quiz-13",
    "section": "الصحابة",
    "category": "الخلفاء",
    "level": "متوسط",
    "question": "من ثالث الخلفاء الراشدين؟",
    "answer": "عثمان بن عفان"
  },
  {
    "id": "demo-quiz-14",
    "section": "الصحابة",
    "category": "الخلفاء",
    "level": "متوسط",
    "question": "من رابع الخلفاء الراشدين؟",
    "answer": "علي بن أبي طالب"
  },
  {
    "id": "demo-quiz-15",
    "section": "الصحابة",
    "category": "الألقاب",
    "level": "متوسط",
    "question": "من الصحابي الملقب بذي النورين؟",
    "answer": "عثمان بن عفان"
  },
  {
    "id": "demo-quiz-16",
    "section": "الصحابة",
    "category": "الألقاب",
    "level": "متوسط",
    "question": "من الصحابي الملقب بالفاروق؟",
    "answer": "عمر بن الخطاب"
  },
  {
    "id": "demo-quiz-17",
    "section": "الصحابة",
    "category": "الحديث",
    "level": "متوسط",
    "question": "من أكثر الصحابة رواية للحديث؟",
    "answer": "أبو هريرة"
  },
  {
    "id": "demo-quiz-18",
    "section": "الصحابة",
    "category": "السيرة",
    "level": "متوسط",
    "question": "من أول الرجال إسلاماً؟",
    "answer": "أبو بكر الصديق"
  },
  {
    "id": "demo-quiz-19",
    "section": "الصحابة",
    "category": "السيرة",
    "level": "متوسط",
    "question": "من أول الصبيان إسلاماً؟",
    "answer": "علي بن أبي طالب"
  },
  {
    "id": "demo-quiz-20",
    "section": "الصحابة",
    "category": "أمهات المؤمنين",
    "level": "متوسط",
    "question": "من أم المؤمنين ابنة أبي بكر؟",
    "answer": "عائشة رضي الله عنها"
  },
  {
    "id": "demo-quiz-21",
    "section": "السيرة",
    "category": "الدعوة",
    "level": "متوسط",
    "question": "في أي غار نزل الوحي أول مرة؟",
    "answer": "غار حراء"
  },
  {
    "id": "demo-quiz-22",
    "section": "السيرة",
    "category": "الدعوة",
    "level": "متوسط",
    "question": "من أول من آمن من النساء؟",
    "answer": "خديجة بنت خويلد"
  },
  {
    "id": "demo-quiz-23",
    "section": "السيرة",
    "category": "الهجرة",
    "level": "متوسط",
    "question": "إلى أي مدينة هاجر النبي صلى الله عليه وسلم؟",
    "answer": "المدينة المنورة"
  },
  {
    "id": "demo-quiz-24",
    "section": "السيرة",
    "category": "الهجرة",
    "level": "متوسط",
    "question": "من صاحب النبي صلى الله عليه وسلم في الهجرة؟",
    "answer": "أبو بكر الصديق"
  },
  {
    "id": "demo-quiz-25",
    "section": "السيرة",
    "category": "المساجد",
    "level": "متوسط",
    "question": "ما أول مسجد أسسه النبي صلى الله عليه وسلم بعد الهجرة؟",
    "answer": "مسجد قباء"
  },
  {
    "id": "demo-quiz-26",
    "section": "السيرة",
    "category": "الغزوات",
    "level": "متوسط",
    "question": "ما أول غزوة كبرى في الإسلام؟",
    "answer": "غزوة بدر"
  },
  {
    "id": "demo-quiz-27",
    "section": "السيرة",
    "category": "الغزوات",
    "level": "متوسط",
    "question": "في أي غزوة وقع حفر الخندق؟",
    "answer": "غزوة الخندق"
  },
  {
    "id": "demo-quiz-28",
    "section": "السيرة",
    "category": "الغزوات",
    "level": "متوسط",
    "question": "ما الغزوة التي وقعت في السنة الثالثة للهجرة؟",
    "answer": "غزوة أحد"
  },
  {
    "id": "demo-quiz-29",
    "section": "السيرة",
    "category": "الصلح",
    "level": "متوسط",
    "question": "ما اسم الصلح الذي عقده النبي صلى الله عليه وسلم مع قريش؟",
    "answer": "صلح الحديبية"
  },
  {
    "id": "demo-quiz-30",
    "section": "السيرة",
    "category": "الفتح",
    "level": "متوسط",
    "question": "ما الحدث الذي دخل فيه النبي صلى الله عليه وسلم مكة فاتحاً؟",
    "answer": "فتح مكة"
  },
  {
    "id": "demo-quiz-31",
    "section": "الأحكام",
    "category": "الصلاة",
    "level": "متوسط",
    "question": "ما أول ما يحاسب عليه العبد من عمله؟",
    "answer": "الصلاة"
  },
  {
    "id": "demo-quiz-32",
    "section": "الأحكام",
    "category": "الصلاة",
    "level": "متوسط",
    "question": "كم عدد الصلوات المفروضة في اليوم والليلة؟",
    "answer": "خمس صلوات"
  },
  {
    "id": "demo-quiz-33",
    "section": "الأحكام",
    "category": "الصلاة",
    "level": "متوسط",
    "question": "ما القبلة التي يتجه إليها المسلمون في الصلاة؟",
    "answer": "الكعبة"
  },
  {
    "id": "demo-quiz-34",
    "section": "الأحكام",
    "category": "الطهارة",
    "level": "متوسط",
    "question": "بماذا يتطهر المسلم عند عدم وجود الماء؟",
    "answer": "التيمم"
  },
  {
    "id": "demo-quiz-35",
    "section": "الأحكام",
    "category": "الطهارة",
    "level": "متوسط",
    "question": "ما الطهارة المطلوبة قبل الصلاة؟",
    "answer": "الوضوء"
  },
  {
    "id": "demo-quiz-36",
    "section": "الأحكام",
    "category": "الصيام",
    "level": "متوسط",
    "question": "في أي شهر يصوم المسلمون؟",
    "answer": "رمضان"
  },
  {
    "id": "demo-quiz-37",
    "section": "الأحكام",
    "category": "الصيام",
    "level": "متوسط",
    "question": "ما الوجبة التي تكون قبل الفجر للصائم؟",
    "answer": "السحور"
  },
  {
    "id": "demo-quiz-38",
    "section": "الأحكام",
    "category": "الزكاة",
    "level": "متوسط",
    "question": "ما العبادة المالية الواجبة على المال بشروطها؟",
    "answer": "الزكاة"
  },
  {
    "id": "demo-quiz-39",
    "section": "الأحكام",
    "category": "الحج",
    "level": "متوسط",
    "question": "ما الركن الأعظم في الحج؟",
    "answer": "الوقوف بعرفة"
  },
  {
    "id": "demo-quiz-40",
    "section": "الأحكام",
    "category": "الحج",
    "level": "متوسط",
    "question": "ما البيت الذي يقصده المسلمون في الحج؟",
    "answer": "الكعبة"
  },
  {
    "id": "demo-quiz-41",
    "section": "الصالحون",
    "category": "العلماء",
    "level": "متوسط",
    "question": "من مؤسس المذهب الحنفي؟",
    "answer": "أبو حنيفة النعمان"
  },
  {
    "id": "demo-quiz-42",
    "section": "الصالحون",
    "category": "العلماء",
    "level": "متوسط",
    "question": "من مؤسس المذهب المالكي؟",
    "answer": "مالك بن أنس"
  },
  {
    "id": "demo-quiz-43",
    "section": "الصالحون",
    "category": "العلماء",
    "level": "متوسط",
    "question": "من مؤسس المذهب الشافعي؟",
    "answer": "محمد بن إدريس الشافعي"
  },
  {
    "id": "demo-quiz-44",
    "section": "الصالحون",
    "category": "العلماء",
    "level": "متوسط",
    "question": "من مؤسس المذهب الحنبلي؟",
    "answer": "أحمد بن حنبل"
  },
  {
    "id": "demo-quiz-45",
    "section": "الصالحون",
    "category": "الحديث",
    "level": "متوسط",
    "question": "من صاحب صحيح البخاري؟",
    "answer": "محمد بن إسماعيل البخاري"
  },
  {
    "id": "demo-quiz-46",
    "section": "الصالحون",
    "category": "الحديث",
    "level": "متوسط",
    "question": "من صاحب صحيح مسلم؟",
    "answer": "مسلم بن الحجاج"
  },
  {
    "id": "demo-quiz-47",
    "section": "الصالحون",
    "category": "الفقه",
    "level": "متوسط",
    "question": "من الإمام المعروف بإمام دار الهجرة؟",
    "answer": "مالك بن أنس"
  },
  {
    "id": "demo-quiz-48",
    "section": "الصالحون",
    "category": "التفسير",
    "level": "متوسط",
    "question": "من الصحابي المشهور بتفسير القرآن؟",
    "answer": "عبد الله بن عباس"
  },
  {
    "id": "demo-quiz-49",
    "section": "الصالحون",
    "category": "الزهد",
    "level": "متوسط",
    "question": "من التابعي المشهور من أهل البصرة بالزهد والموعظة؟",
    "answer": "الحسن البصري"
  },
  {
    "id": "demo-quiz-50",
    "section": "الصالحون",
    "category": "العلماء",
    "level": "متوسط",
    "question": "من الإمام صاحب كتاب الموطأ؟",
    "answer": "مالك بن أنس"
  },
  {
    "id": "demo-quiz-51",
    "section": "الألغاز الشرعية",
    "category": "عام",
    "level": "متوسط",
    "question": "شيء يزداد بالإنفاق منه في الخير، فما هو؟",
    "answer": "الأجر"
  },
  {
    "id": "demo-quiz-52",
    "section": "الألغاز الشرعية",
    "category": "عام",
    "level": "متوسط",
    "question": "عبادة لا تصح إلا بدخول الوقت والطهارة واستقبال القبلة، فما هي؟",
    "answer": "الصلاة"
  },
  {
    "id": "demo-quiz-53",
    "section": "الألغاز الشرعية",
    "category": "عام",
    "level": "متوسط",
    "question": "شهر فيه ليلة خير من ألف شهر، فما هو؟",
    "answer": "رمضان"
  },
  {
    "id": "demo-quiz-54",
    "section": "الألغاز الشرعية",
    "category": "عام",
    "level": "متوسط",
    "question": "كتاب لا يأتيه الباطل من بين يديه ولا من خلفه، فما هو؟",
    "answer": "القرآن الكريم"
  },
  {
    "id": "demo-quiz-55",
    "section": "الألغاز الشرعية",
    "category": "عام",
    "level": "متوسط",
    "question": "بيت يطوف حوله المسلمون في الحج والعمرة، فما هو؟",
    "answer": "الكعبة"
  }
];
