/**
 * بيانات حلقات القرآن الكريم
 * ─ الكويت (حضوري + هجين)
 * ─ عالمية عبر الإنترنت
 *
 * المصدر: إدارة شؤون القرآن الكريم / وزارة الأوقاف الكويتية
 *         + مصادر موثوقة للمنصات الإلكترونية
 */

export interface QuranCircleSeed {
  id: string;
  name: string;
  sheikh_name: string | null;
  level: "مبتدئ" | "متوسط" | "متقدم";
  track: "رجال" | "نساء" | "أطفال" | "عام";
  mode: "حضوري" | "عن بُعد" | "هجين";
  meeting_link: string | null;
  location: string | null;
  schedule_days: string[] | null;
  schedule_time: string | null;
  capacity: number | null;
  enrolled_count: number;
  description: string | null;
  cover_image: string | null;
  contact_info: string | null;
  registration_url: string | null;
  website_url: string | null;
  governorate: string | null;
  is_approved: boolean;
  is_active: boolean;
  created_at: string;
}

const REG_AWQAF = "https://halakat.awqaf.gov.kw/Home/RegisterStudent";
const SITE_AWQAF = "https://quran.awqaf.gov.kw";

export const QURAN_CIRCLES_SEED: QuranCircleSeed[] = [

  // ══════════════════════════════════════════════════════
  //  أولاً: مراكز الكويت الحضورية — وزارة الأوقاف
  // ══════════════════════════════════════════════════════

  // ── العاصمة ──
  {
    id: "kw-capital-01",
    name: "مركز العوضي للجاليات لتحفيظ القرآن (بنين)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "رجال",
    mode: "حضوري",
    meeting_link: null,
    location: "العاصمة — الشرق، شارع أحمد الجابر، مقابل مجمع دسمان",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "4:30 م — 7:00 م",
    capacity: 60,
    enrolled_count: 0,
    description: "مركز متخصص لتحفيظ القرآن الكريم للجاليات المسلمة، يُقدّم برامج للبالغين باللغات المتعددة ضمن منظومة وزارة الأوقاف.",
    cover_image: null,
    contact_info: "22493219",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "العاصمة",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "kw-capital-02",
    name: "مركز البشائر لتحفيظ القرآن الكريم (بنين)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "رجال",
    mode: "حضوري",
    meeting_link: null,
    location: "العاصمة — الكويت",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "4:30 م — 7:00 م",
    capacity: 50,
    enrolled_count: 0,
    description: "من مراكز وزارة الأوقاف لتحفيظ القرآن الكريم في محافظة العاصمة، يستقبل الطلاب في الحلقات الصباحية والمسائية.",
    cover_image: null,
    contact_info: "25444162",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "العاصمة",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "kw-capital-03",
    name: "مركز منارات لتحفيظ القرآن (بنات)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "نساء",
    mode: "حضوري",
    meeting_link: null,
    location: "العاصمة — كيفان",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "9:00 ص — 12:00 م",
    capacity: 45,
    enrolled_count: 0,
    description: "مركز نسائي لتحفيظ القرآن الكريم وتعليم أحكام التجويد، يخدم بنات ونساء منطقة كيفان والمناطق المجاورة.",
    cover_image: null,
    contact_info: "25350424",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "العاصمة",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ── حولي ──
  {
    id: "kw-hawalli-01",
    name: "إدارة شؤون القرآن الكريم — المركز الرئيسي",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "هجين",
    meeting_link: "https://halakat.awqaf.gov.kw",
    location: "حولي — الكويت",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "8:00 ص — 2:00 م",
    capacity: 200,
    enrolled_count: 0,
    description: "المركز الرئيسي لإدارة شؤون القرآن الكريم التابعة لوزارة الأوقاف والشؤون الإسلامية. يُشرف على أكثر من 60 مركزاً في جميع محافظات الكويت، ويوفر برنامج المقرأة الإلكترونية للتحفيظ عن بُعد.",
    cover_image: null,
    contact_info: "25350424",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "حولي",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "kw-hawalli-02",
    name: "مركز محمد الوزان لتحفيظ القرآن (بنات)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "نساء",
    mode: "حضوري",
    meeting_link: null,
    location: "حولي — السالمية",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "4:00 م — 7:30 م",
    capacity: 40,
    enrolled_count: 0,
    description: "مركز نسائي لتحفيظ القرآن الكريم في منطقة السالمية، يُقدّم برنامجاً متكاملاً للحفظ والتلاوة والتجويد.",
    cover_image: null,
    contact_info: "25355958",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "حولي",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "kw-hawalli-03",
    name: "مركز مسجد فاطمة المقهوي (بنات)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "نساء",
    mode: "حضوري",
    meeting_link: null,
    location: "حولي — السالمية",
    schedule_days: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء"],
    schedule_time: "4:30 م — 7:00 م",
    capacity: 35,
    enrolled_count: 0,
    description: "حلقة نسائية في مسجد فاطمة المقهوي بالسالمية، تشرف عليها وزارة الأوقاف وتقبل التسجيل إلكترونياً.",
    cover_image: null,
    contact_info: "25350424",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "حولي",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ── الفروانية ──
  {
    id: "kw-farwaniya-01",
    name: "مركز عواصف الصباح لتحفيظ القرآن (بنات)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "نساء",
    mode: "حضوري",
    meeting_link: null,
    location: "الفروانية — الفروانية",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "9:00 ص — 12:00 م",
    capacity: 40,
    enrolled_count: 0,
    description: "مركز نسائي في محافظة الفروانية لتحفيظ القرآن الكريم وتعليم التجويد برواية حفص عن عاصم.",
    cover_image: null,
    contact_info: "24897513",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "الفروانية",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "kw-farwaniya-02",
    name: "مركز إلهام البوشي لتحفيظ القرآن (بنات)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "نساء",
    mode: "حضوري",
    meeting_link: null,
    location: "الفروانية",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "4:00 م — 7:00 م",
    capacity: 35,
    enrolled_count: 0,
    description: "حلقة نسائية لتحفيظ القرآن الكريم وتعليم أحكام التجويد في محافظة الفروانية، تابعة لوزارة الأوقاف.",
    cover_image: null,
    contact_info: "24753113",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "الفروانية",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "kw-farwaniya-03",
    name: "مركز الشاطبي لتحفيظ القرآن (بنين)",
    sheikh_name: null,
    level: "متوسط",
    track: "رجال",
    mode: "حضوري",
    meeting_link: null,
    location: "الفروانية",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "4:30 م — 7:30 م",
    capacity: 45,
    enrolled_count: 0,
    description: "يُعنى بتعليم القرآن وأحكام التجويد، ويوفر مستويات متعددة للطلاب من المبتدئين والمتوسطين.",
    cover_image: null,
    contact_info: "25350424",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "الفروانية",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ── الجهراء ──
  {
    id: "kw-jahra-01",
    name: "مركز الجهراء لتحفيظ القرآن (رجال)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "رجال",
    mode: "حضوري",
    meeting_link: null,
    location: "الجهراء — مدينة الجهراء",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "4:30 م — 7:30 م",
    capacity: 50,
    enrolled_count: 0,
    description: "مركز رجالي في محافظة الجهراء لتحفيظ القرآن الكريم وتلاوته بأحكام التجويد، تابع لوزارة الأوقاف.",
    cover_image: null,
    contact_info: "24576000",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "الجهراء",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "kw-jahra-02",
    name: "مركز الواحة لتحفيظ القرآن (رجال)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "رجال",
    mode: "حضوري",
    meeting_link: null,
    location: "الجهراء",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "4:30 م — 7:30 م",
    capacity: 40,
    enrolled_count: 0,
    description: "يستقبل الطلاب الراغبين في تحفيظ القرآن وتعلّم التجويد، يستوعب المستويات المختلفة.",
    cover_image: null,
    contact_info: "25350424",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "الجهراء",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ── مبارك الكبير ──
  {
    id: "kw-mubarak-01",
    name: "مركز مبارك الكبير لتحفيظ القرآن",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "حضوري",
    meeting_link: null,
    location: "مبارك الكبير — مبارك الكبير",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "4:00 م — 7:30 م",
    capacity: 50,
    enrolled_count: 0,
    description: "مركز لتحفيظ القرآن الكريم في محافظة مبارك الكبير، يقبل الرجال والأطفال ويوفر برامج متنوعة للمستويات المختلفة.",
    cover_image: null,
    contact_info: "25350424",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "مبارك الكبير",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "kw-mubarak-02",
    name: "مركز القرين لتحفيظ القرآن (نساء)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "نساء",
    mode: "حضوري",
    meeting_link: null,
    location: "مبارك الكبير — القرين",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "9:00 ص — 12:00 م",
    capacity: 35,
    enrolled_count: 0,
    description: "حلقة نسائية في منطقة القرين بمحافظة مبارك الكبير، تابعة لإدارة شؤون القرآن الكريم.",
    cover_image: null,
    contact_info: "25350424",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "مبارك الكبير",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ── الأحمدي ──
  {
    id: "kw-ahmadi-01",
    name: "دار القرآن الفحيحيل",
    sheikh_name: null,
    level: "مبتدئ",
    track: "رجال",
    mode: "حضوري",
    meeting_link: null,
    location: "الأحمدي — الفحيحيل",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "4:30 م — 7:30 م",
    capacity: 50,
    enrolled_count: 0,
    description: "دار القرآن في الفحيحيل تستقبل طلاب التحفيظ والتجويد من رجال وشباب محافظة الأحمدي.",
    cover_image: null,
    contact_info: "23982000",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "الأحمدي",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "kw-ahmadi-02",
    name: "مركز علي صباح السالم لتحفيظ القرآن",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "حضوري",
    meeting_link: null,
    location: "الأحمدي — علي صباح السالم",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "4:30 م — 7:00 م",
    capacity: 40,
    enrolled_count: 0,
    description: "مركز لتحفيظ القرآن الكريم في منطقة علي صباح السالم يخدم أبناء المنطقة الجنوبية من الكويت.",
    cover_image: null,
    contact_info: "25350424",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "الأحمدي",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ── الجمعية الخيرية الكويتية (حفاظ) ──
  {
    id: "kw-hofath-01",
    name: "الجمعية الخيرية الكويتية لخدمة القرآن وعلومه (حفاظ)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "هجين",
    meeting_link: "https://hofath.org",
    location: "الكويت — فروع متعددة في جميع المحافظات",
    schedule_days: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "صباحي ومسائي",
    capacity: 500,
    enrolled_count: 0,
    description: "جمعية خيرية كويتية متخصصة في خدمة القرآن الكريم وعلومه، تُدير مراكز للتحفيظ والتجويد والقراءات في جميع محافظات الكويت. تستقبل الرجال والنساء والأطفال وتوفر حلقات حضورية وإلكترونية.",
    cover_image: null,
    contact_info: "halaqat-hofath.org",
    registration_url: "https://halaqat-hofath.org/mycenter.aspx",
    website_url: "https://hofath.org",
    governorate: "جميع المحافظات",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ── مراكز الأطفال ──
  {
    id: "kw-children-01",
    name: "مركز ابن الجزري لتحفيظ القرآن (أطفال)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "أطفال",
    mode: "حضوري",
    meeting_link: null,
    location: "الكويت — فروع متعددة",
    schedule_days: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء"],
    schedule_time: "4:00 م — 6:30 م",
    capacity: 60,
    enrolled_count: 0,
    description: "حلقات قرآنية للأطفال من سن 5 سنوات فصاعداً، تعتمد أساليب تعليمية حديثة مع المتابعة الفردية لكل طفل. تسجيل إلكتروني عبر بوابة الأوقاف.",
    cover_image: null,
    contact_info: "25350424",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "الكويت",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "kw-children-02",
    name: "مركز القارئ الصغير لتحفيظ القرآن (أطفال)",
    sheikh_name: null,
    level: "مبتدئ",
    track: "أطفال",
    mode: "حضوري",
    meeting_link: null,
    location: "الكويت — فروع في العاصمة وحولي والفروانية",
    schedule_days: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء"],
    schedule_time: "4:00 م — 6:00 م",
    capacity: 80,
    enrolled_count: 0,
    description: "برنامج القارئ الصغير لتحفيظ القرآن للأطفال تابع لإدارة شؤون القرآن الكريم، يُقبل الأطفال من سن 5-14 سنة.",
    cover_image: null,
    contact_info: "25350424",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "الكويت",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ── المقرأة الإلكترونية - وزارة الأوقاف ──
  {
    id: "kw-online-awqaf",
    name: "المقرأة الإلكترونية — وزارة الأوقاف الكويتية",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "عن بُعد",
    meeting_link: "https://halakat.awqaf.gov.kw",
    location: "عبر الإنترنت — للمقيمين في الكويت",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "مرن حسب الجدول",
    capacity: 300,
    enrolled_count: 0,
    description: "برنامج التحفيظ الإلكتروني الرسمي لوزارة الأوقاف والشؤون الإسلامية الكويتية، يُقدّم حلقات عن بُعد للرجال والنساء والأطفال عبر منظومة إلكترونية متكاملة. التسجيل بالرقم المدني.",
    cover_image: null,
    contact_info: "1810111",
    registration_url: REG_AWQAF,
    website_url: SITE_AWQAF,
    governorate: "الكويت",
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ══════════════════════════════════════════════════════
  //  ثانياً: حلقات إلكترونية عالمية موثوقة
  // ══════════════════════════════════════════════════════

  {
    id: "online-itqan",
    name: "مقرأة إتقان الافتراضية",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "عن بُعد",
    meeting_link: "https://itqan-quran.com/",
    location: "عالمي — عبر الإنترنت",
    schedule_days: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "مرن — حسب اختيار الطالب",
    capacity: null,
    enrolled_count: 0,
    description: "مقرأة إسلامية إلكترونية تابعة لجمعية مكنون لتحفيظ القرآن الكريم. تُقدّم حلقات مجانية للرجال والنساء والأطفال وغير الناطقين بالعربية، وفق منهجية علمية رصينة بإشراف معلمين ومعلمات مؤهلين. متاحة لجميع أنحاء العالم.",
    cover_image: null,
    contact_info: "+966539065696",
    registration_url: "https://itqan-quran.com/",
    website_url: "https://itqan-quran.com/",
    governorate: null,
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "online-maqraa-sa",
    name: "المقرأة الإلكترونية السعودية",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "عن بُعد",
    meeting_link: "https://maqraa.sa/",
    location: "عالمي — عبر الإنترنت",
    schedule_days: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة"],
    schedule_time: "مرن — حسب الجدول المحدد",
    capacity: null,
    enrolled_count: 0,
    description: "الجمعية الخيرية الإلكترونية لتحفيظ القرآن الكريم — توفر حلقات مجانية ومدعومة للرجال والنساء والأطفال من جميع أنحاء العالم. تتوفر برامج متخصصة للإجازة في القراءات العشر. التسجيل عبر التطبيق أو الموقع.",
    cover_image: null,
    contact_info: "+966500909709",
    registration_url: "https://maqraa.sa/",
    website_url: "https://maqraa.sa/",
    governorate: null,
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "online-tartil",
    name: "منصة ترتيل لتحفيظ القرآن",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "عن بُعد",
    meeting_link: "https://tartilonline.com/",
    location: "عالمي — عبر الإنترنت",
    schedule_days: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة"],
    schedule_time: "مرن — حسب المعلم",
    capacity: null,
    enrolled_count: 0,
    description: "منصة تجمع معلمين أزهريين متخصصين في تحفيظ القرآن الكريم للكبار والأطفال. تُقدّم جلسة تجريبية مجانية ثم اشتراكات شهرية. تغطي التحفيظ والتجويد والتلاوة والتفسير.",
    cover_image: null,
    contact_info: "+201556112022",
    registration_url: "https://tartilonline.com/",
    website_url: "https://tartilonline.com/",
    governorate: null,
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "online-quraan-me",
    name: "منصة قرآني — أول منصة إلكترونية لتعليم القرآن",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "عن بُعد",
    meeting_link: "https://quraan.me/",
    location: "عالمي — عبر الإنترنت",
    schedule_days: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة"],
    schedule_time: "مرن",
    capacity: null,
    enrolled_count: 0,
    description: "أول منصة إلكترونية عربية متكاملة لتعليم وتحفيظ القرآن الكريم وعلومه. تُقدّم تلاوة تفاعلية، خطط حفظ مخصصة، معلمون معتمدون، وتقنيات تواصل مدمجة مع تسجيلات الحصص.",
    cover_image: null,
    contact_info: "quraan.me",
    registration_url: "https://quraan.me/",
    website_url: "https://quraan.me/",
    governorate: null,
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "online-noor-academy",
    name: "أكاديمية نور البيان لتحفيظ القرآن",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "عن بُعد",
    meeting_link: "https://www.nooracademy.online/",
    location: "عالمي — عبر الإنترنت",
    schedule_days: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "مرن — حسب المعلم",
    capacity: null,
    enrolled_count: 0,
    description: "أكاديمية متخصصة في تحفيظ القرآن الكريم وتعليم أحكام التجويد أون لاين عن بُعد. يُدرّس فيها معلمون ومعلمات مجازون من الأزهر الشريف. تشمل برامج للكبار والأطفال.",
    cover_image: null,
    contact_info: "nooracademy.online",
    registration_url: "https://www.nooracademy.online/",
    website_url: "https://www.nooracademy.online/",
    governorate: null,
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "online-maqare",
    name: "منصة مقارئ للتجويد والتحفيظ",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "عن بُعد",
    meeting_link: "https://maqare.com/",
    location: "عالمي — عبر الإنترنت",
    schedule_days: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة"],
    schedule_time: "مرن",
    capacity: null,
    enrolled_count: 0,
    description: "منصة تعليمية متكاملة لتصحيح تلاوة القرآن الكريم وتدريس دورات التجويد وتحفيظ القرآن للكبار والأطفال أون لاين. تتوفر معلمات للطالبات.",
    cover_image: null,
    contact_info: "maqare.com",
    registration_url: "https://maqare.com/",
    website_url: "https://maqare.com/",
    governorate: null,
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "online-awqaf-jordan",
    name: "الحلقات القرآنية الإلكترونية — وزارة الأوقاف الأردنية",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "عن بُعد",
    meeting_link: "https://awqaf.gov.jo/AR/Pages/%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A7%D8%AA_%D8%A7%D9%84%D9%82%D8%B1%D8%A2%D9%86%D9%8A%D8%A9_%D8%A3%D9%88%D9%86_%D9%84%D8%A7%D9%8A%D9%86",
    location: "عالمي — عبر الإنترنت",
    schedule_days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "مرن",
    capacity: null,
    enrolled_count: 0,
    description: "حلقات القرآن الكريم الإلكترونية الرسمية التابعة لوزارة الأوقاف والمقدسات الإسلامية الأردنية. تُقدّم برامج تحفيظ وتجويد عالية الجودة بإشراف علماء معتمدين لكل الأعمار من جميع أنحاء العالم.",
    cover_image: null,
    contact_info: "awqaf.gov.jo",
    registration_url: "https://awqaf.gov.jo/AR/Pages/%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A7%D8%AA_%D8%A7%D9%84%D9%82%D8%B1%D8%A2%D9%86%D9%8A%D8%A9_%D8%A3%D9%88%D9%86_%D9%84%D8%A7%D9%8A%D9%86",
    website_url: "https://awqaf.gov.jo",
    governorate: null,
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "online-hofath-kw",
    name: "حلقات حفاظ الإلكترونية — الكويت",
    sheikh_name: null,
    level: "مبتدئ",
    track: "عام",
    mode: "عن بُعد",
    meeting_link: "https://hofath.org",
    location: "عالمي — عبر الإنترنت (للكويتيين بالأولوية)",
    schedule_days: ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    schedule_time: "مرن",
    capacity: null,
    enrolled_count: 0,
    description: "الجمعية الخيرية الكويتية (حفاظ) توفر حلقات إلكترونية لتحفيظ القرآن الكريم وتجويده للأفراد والعائلات خارج الكويت وللمقيمين الذين يتعذر عليهم الحضور. التسجيل عبر الموقع.",
    cover_image: null,
    contact_info: "hofath.org",
    registration_url: "https://halaqat-hofath.org/mycenter.aspx",
    website_url: "https://hofath.org",
    governorate: null,
    is_approved: true,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
];
