/**
 * علماء ومشايخ — بيانات موثقة
 */
export type SheikhSeedItem = {
  id: string;
  name: string;
  ijazah?: string;
  city?: string;
  years_experience?: number;
  is_verified: boolean;
  specialties: string[];
  bio?: string;
  photo_url?: string;
};

export const SHEIKHS_SEED: SheikhSeedItem[] = [
  {
    id: "sheikh-001",
    name: "الشيخ عبدالله بن عبدالعزيز بن باز",
    ijazah: "إجازة في العقيدة والحديث",
    city: "الرياض",
    years_experience: 40,
    is_verified: true,
    specialties: ["عقيدة", "حديث", "فتاوى"],
    bio: "من كبار علماء المملكة؛ تخصص في العقيدة والحديث؛ له فتاوى ودروس كثيرة.",
  },
  {
    id: "sheikh-002",
    name: "الشيخ محمد بن صالح العثيمين",
    ijazah: "إجازة في الفقه والأصول",
    city: "القصيم",
    years_experience: 35,
    is_verified: true,
    specialties: ["فقه", "أصول", "تفسير"],
    bio: "عالم فقيه مفسر؛ له مؤلفات في التفسير والفقه والعقيدة.",
  },
  {
    id: "sheikh-003",
    name: "الشيخ محمد ناصر الدين الألباني",
    ijazah: "إجازة في علوم الحديث",
    city: "عمان",
    years_experience: 30,
    is_verified: true,
    specialties: ["حديث", "علل", "سنة"],
    bio: "محدث العصر؛ له تصحيح وتضعيف الأحاديث وكتب في السنة.",
  },
  {
    id: "sheikh-004",
    name: "الشيخ صالح بن فوزان الفوزان",
    ijazah: "عضو هيئة كبار العلماء",
    city: "الرياض",
    years_experience: 30,
    is_verified: true,
    specialties: ["فقه", "فتوى", "عقيدة"],
    bio: "عالم فقه وعقيدة؛ له سلسلة «المنتقى من فتاوى» وشروح متعددة.",
  },
  {
    id: "sheikh-005",
    name: "الشيخ عبد العزيز بن عبد الله آل الشيخ",
    ijazah: "مفتي عام المملكة (سابقاً)",
    city: "الرياض",
    years_experience: 25,
    is_verified: true,
    specialties: ["فتوى", "عقيدة"],
    bio: "عضو هيئة كبار العلماء؛ له فتاوى ودروس في العقيدة والفقه.",
  },
  {
    id: "sheikh-006",
    name: "الإمام أحمد بن حنبل",
    ijazah: "إمام أهل السنة",
    city: "بغداد",
    years_experience: 40,
    is_verified: true,
    specialties: ["حديث", "فقه"],
    bio: "صاحب المذهب الحنبلي؛ جمع المسند؛ من أئمة الحديث.",
  },
  {
    id: "sheikh-007",
    name: "الإمام الشافعي",
    ijazah: "إمام المذهب الشافعي",
    city: "مصر",
    years_experience: 35,
    is_verified: true,
    specialties: ["فقه", "أصول"],
    bio: "صاحب الرسالة؛ جمع بين الفقه والحديث والأصول.",
  },
  {
    id: "sheikh-008",
    name: "الإمام مالك بن أنس",
    ijazah: "إمام دار الهجرة",
    city: "المدينة",
    years_experience: 40,
    is_verified: true,
    specialties: ["فقه", "حديث"],
    bio: "صاحب الموطأ؛ إمام أهل المدينة في الفقه والحديث.",
  },
  // ── مشايخ كويتيون ──────────────────────────────────────────────
  {
    id: "salem-bin-saad-altaweel",
    name: "سالم بن سعد الطويل",
    ijazah: "داعية وطالب علم",
    city: "الكويت",
    years_experience: 20,
    is_verified: true,
    specialties: ["عقيدة", "حديث", "دعوة"],
    bio: "داعية كويتي؛ يُلقي دروساً أسبوعية في شرح كتب الحديث والعقيدة، أبرزها شرح كتاب التوحيد من صحيح البخاري. له موقع رسمي saltaweel.com وحضور فاعل في وسائل التواصل.",
    photo_url: undefined,
  },
  {
    id: "hussain-bin-mubarak-almuwaiziri",
    name: "الشيخ حسين بن مبارك المويزري",
    ijazah: "طالب علم — داعية",
    city: "الكويت",
    years_experience: 15,
    is_verified: true,
    specialties: ["حديث", "فقه", "شرح كتب"],
    bio: "شيخ كويتي يُلقي دروساً في شرح كتب الحديث والفقه، منها شرح روضة الأفهام في زوائد المحرر على بلوغ المرام.",
  },
  {
    id: "hamed-ali-almasad",
    name: "حامد علي المسعد",
    ijazah: "داعية — مربٍّ",
    city: "الكويت",
    years_experience: 15,
    is_verified: true,
    specialties: ["تزكية", "وعظ", "قرآن"],
    bio: "داعية كويتي معروف بدروس التزكية والوعظ؛ من مشايخ ملتقى «إجازتي طاعة» وله محاضرات في إحياء القلوب.",
  },
  {
    id: "nassar-khalid-alajmi",
    name: "نصار خالد نصار العجمي",
    ijazah: "داعية — مربٍّ",
    city: "الكويت",
    years_experience: 15,
    is_verified: true,
    specialties: ["وعظ", "تربية", "دعوة"],
    bio: "داعية كويتي؛ يُركز في محاضراته على الجانب التربوي والتزكوي؛ من مشايخ ملتقى «إجازتي طاعة».",
  },
  {
    id: "bandar-mohammed-almaymuni",
    name: "بندر محمد الميموني",
    ijazah: "داعية",
    city: "الكويت",
    years_experience: 15,
    is_verified: true,
    specialties: ["وعظ", "تزكية", "رقائق"],
    bio: "داعية كويتي؛ له محاضرات في الرقائق وأحوال القلوب؛ من مشايخ ملتقى «إجازتي طاعة».",
  },
  {
    id: "saad-hazzaa-alutaibi",
    name: "سعد هزاع العتيبي",
    ijazah: "داعية",
    city: "الكويت",
    years_experience: 12,
    is_verified: true,
    specialties: ["وعظ", "ثبات", "دعوة"],
    bio: "داعية كويتي؛ يُعرف بمحاضرات الثبات والتثبيت على الدين؛ من مشايخ ملتقى «إجازتي طاعة».",
  },
  {
    id: "faisal-zuwaid",
    name: "فيصل زويد",
    ijazah: "داعية",
    city: "الكويت",
    years_experience: 12,
    is_verified: true,
    specialties: ["تزكية", "وعظ", "قلوب"],
    bio: "داعية كويتي؛ له محاضرات في تزكية النفس وصلاح القلب.",
  },
  {
    id: "daham-abu-khashabah",
    name: "د. دهام أبو خشبة",
    ijazah: "دكتوراه في الفقه وأصوله",
    city: "الكويت",
    years_experience: 20,
    is_verified: true,
    specialties: ["فقه", "أصول الفقه", "حديث"],
    bio: "أكاديمي وداعية كويتي؛ يُلقي دروساً فقهية منها شرح عمدة الأحكام.",
  },
  {
    id: "mutlaq-jaser-aljasr",
    name: "د. مطلق جاسر مطلق الجاسر",
    ijazah: "دكتوراه في الشريعة",
    city: "الكويت",
    years_experience: 18,
    is_verified: true,
    specialties: ["طلب العلم", "تأصيل", "دعوة"],
    bio: "داعية وأكاديمي كويتي؛ من مؤسسي برامج تأهيل طلاب العلم المبتدئين؛ يُشرف على دورة «طلائع العلم» الإلكترونية.",
  },
  {
    id: "mohammad-dawwi-al-usaimi",
    name: "د. محمد ضاوي العصيمي",
    ijazah: "أستاذ مشارك — جامعة الكويت",
    city: "الكويت",
    years_experience: 20,
    is_verified: true,
    specialties: ["فقه", "أصول الفقه", "وعظ", "تزكية"],
    bio: "أستاذ مشارك في كلية الشريعة والدراسات الإسلامية بجامعة الكويت. له دروس ومحاضرات وفتاوى.",
    photo_url: "/images/posters/fadat-dawwi-al-usaimi.svg",
  },
];
