import type { PlatformUpdate } from "./platform-types";

export const UPDATES_SEED: PlatformUpdate[] = [
  // ملاحظة تدقيق (٢٠٢٦-٠٧-٣١): حُذف من هنا الصفُّ `update-fiqh-crypto` («قرار
  // جديد: حكم التعامل بالعملات الرقمية»، source_url = /fiqh-council/fiqh-crypto-2024).
  // موجبُ الحذف من المصدر نفسه لا من اجتهاد: (١) وجهتُه ميتةٌ — البندُ
  // `fiqh-crypto-2024` غيرُ موجودٍ في `fiqh-council-seed.ts` فتردُّ
  // `findFiqhCouncilItemBySlug` قيمةَ null وتُعرَضُ صفحةُ «المحتوى غير موجود».
  // (٢) وسببُ موتِها موثَّقٌ: حُذف البندُ في الـcommit 70a689a19 ضمن ثلاثين قرارًا
  // تنسبُ إلى مجامعَ حقيقيةٍ دوراتٍ لم تنعقد، ونسخته محفوظةٌ في
  // `data/fiqh-council-deleted-2026-07-26-backup.json`. (٣) ومتنُ الصفِّ يحملُ
  // الخبرَ الباطلَ عينَه — يُثبِتُ صدورَ قرارٍ ويؤرِّخُه بـ2024-03-15، بينما البندُ
  // القائمُ `items-encrypted-digital-currencies` ينصُّ على أنَّ القرار 237 (24/8)
  // صدر في دورة دبي (4-6 نوفمبر 2019م) وأنَّه «لم يصدر حكم قاطع» بل أوصى
  // المجمعُ بمزيدٍ من البحث. فلم يكن التوجيهُ إلى البند القائم علاجًا — إذ
  // يناقضُ عنوانُ الصفِّ وجهتَه — والعلاجُ إزالةُ الخبرِ لا صياغتُه من جديد.
  {
    id: "update-course-ijazah",
    title: "فتح التسجيل: دورة الإجازة 1447هـ",
    summary: "فُتح باب التسجيل في الدورة السنوية لنيل الإجازة العلمية لعام 1447هـ.",
    update_type: "دورة",
    source_type: "annual_course",
    source_id: "course-ijazah-tahrir-2026",
    source_url: "/annual-courses/course-ijazah-tahrir-2026",
    published_at: "2025-12-01T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-tafsir",
    title: "درس جديد: تفسير سورة النحل",
    summary: "انضم درس تفسير سورة النحل إلى جدول الدروس المتاحة في المنصة.",
    update_type: "درس",
    source_type: "lesson",
    source_id: "kw-othman-tafsir-nahl-0",
    source_url: "/lessons/kw-othman-tafsir-nahl-0",
    published_at: "2025-11-20T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-library-book",
    title: "كتاب جديد: رياض الصالحين",
    summary: "إضافة كتاب رياض الصالحين للإمام النووي إلى المكتبة العلمية.",
    update_type: "كتاب",
    source_type: "library",
    source_id: "book-riyadh",
    source_url: "/library/book-riyadh",
    published_at: "2025-11-10T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-ramadan",
    title: "إعلان: البرنامج العلمي الرمضاني 1447",
    summary: "إعلان عن بدء البرنامج العلمي المكثّف في شهر رمضان.",
    update_type: "إعلان",
    source_url: "/annual-courses/course-ramadan-intensive",
    published_at: "2025-11-15T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-news-conference",
    title: "خبر علمي: مؤتمر الفقه المعاصر",
    summary: "انعقد مؤتمر الفقه المعاصر ونُشرت أبحاثه في منصة المجمع الفقهي.",
    update_type: "خبر علمي",
    source_url: "/fiqh-council",
    published_at: "2025-10-01T05:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-zakat-crypto",
    title: "قرار جديد: زكاة العملات الرقمية",
    summary: "إصدار قرار فقهي بوجوب الزكاة على العملات الرقمية وكيفية احتسابها.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/issues/zakat-crypto",
    published_at: "2026-05-20T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-usul-fiqh",
    title: "درس جديد: أصول الفقه المقارن",
    summary:
      "إضافة حلقة «دراسة مقارنة في أصول المذاهب الأربعة — مسائل الإجماع والقياس والاستصلاح» إلى جدول الدروس.",
    update_type: "درس",
    source_type: "lesson",
    source_id: "sci-usul-fiqh-muqaranah-2026",
    source_url: "/lessons/sci-usul-fiqh-muqaranah-2026",
    published_at: "2026-05-10T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-general-anesthesia",
    title: "فتوى جديدة: حكم التخدير الكلي في الجراحة",
    summary: "بيان جواز التخدير الكلي عند الضرورة الطبية.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/issues/general-anesthesia",
    published_at: "2026-03-01T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-human-cloning",
    title: "قرار جديد: تحريم الاستنساخ البشري التكاثري",
    summary: "قرار فقهي بتحريم الاستنساخ البشري التكاثري وبيان ضوابط الاستنساخ العلاجي.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/issues/human-cloning",
    published_at: "2026-02-10T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-bulugh-maram",
    title: "درس جديد: شرح زوائد بلوغ المرام (روضة الأفهام)",
    summary:
      "إضافة درس «روضة الأفهام في شرح زوائد المحرر على بلوغ المرام» إلى جدول الدروس.",
    update_type: "درس",
    source_type: "lesson",
    source_id: "sci-rawdat-alafham-muwaiziri",
    source_url: "/lessons/sci-rawdat-alafham-muwaiziri",
    published_at: "2026-01-05T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-misyar-marriage",
    title: "فتوى جديدة: حكم زواج المسيار",
    summary: "بيان أحكام وضوابط زواج المسيار وأثره على الحقوق الزوجية.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/issues/misyar-marriage",
    published_at: "2025-11-25T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-electronic-divorce",
    title: "فتوى جديدة: الطلاق الإلكتروني",
    summary: "بيان وقوع الطلاق عبر الرسائل الإلكترونية ووسائل التواصل.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/issues/electronic-divorce",
    published_at: "2025-10-15T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-tajweed",
    title: "درس جديد: أحكام التجويد العملي",
    summary:
      "إضافة حلقة «أحكام التجويد — المخارج والصفات والتطبيق العملي» إلى جدول الدروس.",
    update_type: "درس",
    source_type: "lesson",
    source_id: "sci-tajweed-mushaf-recitation",
    source_url: "/lessons/sci-tajweed-mushaf-recitation",
    published_at: "2025-10-01T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-health-insurance",
    title: "قرار جديد: حكم التأمين الصحي",
    summary: "قرار فقهي في جواز التأمين الصحي التعاوني وضوابط التأمين التجاري.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/issues/health-insurance-ruling",
    published_at: "2025-09-20T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-book-arbaeen-nawawi",
    title: "كتاب جديد: شرح الأربعين النووية",
    summary: "إضافة شرح الأربعين النووية للإمام ابن دقيق العيد إلى المكتبة.",
    update_type: "كتاب",
    source_type: "library",
    source_id: "book-sharh-arbaeen-ibn-daqiq",
    source_url: "/library/book-sharh-arbaeen-ibn-daqiq",
    published_at: "2025-08-25T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-astronaut-prayer",
    title: "فتوى جديدة: صلاة رواد الفضاء",
    summary: "بيان أوقات الصلاة واتجاه القبلة لرواد الفضاء في المدار الأرضي.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/issues/astronaut-prayer",
    published_at: "2025-07-20T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-seerah",
    title: "درس جديد: السيرة النبوية الشاملة",
    summary:
      "إضافة سلسلة «السيرة النبوية الشاملة — من المهد إلى اللحد» إلى جدول الدروس.",
    update_type: "درس",
    source_type: "lesson",
    source_id: "sci-seerah-series-online",
    source_url: "/lessons/sci-seerah-series-online",
    published_at: "2025-06-15T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-new-sections",
    title: "تحديث المسابقات: إضافة أسئلة جديدة",
    summary: "إضافة 25 سؤالاً جديداً في الأخلاق وعلوم القرآن والحديث والألغاز الشرعية.",
    update_type: "خبر علمي",
    source_url: "/quiz",
    published_at: "2026-07-08T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-waqf-digital",
    title: "قرار جديد: الوقف الرقمي",
    summary: "قرار فقهي بإقرار الوقف الرقمي كنوع مستجد من أنواع الوقف المشروع.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/issues/digital-waqf",
    published_at: "2026-07-03T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-quran-memorize",
    title: "إعلان: برنامج حفظ القرآن الصيفي 1448هـ",
    summary: "انطلاق برنامج الحفظ الصيفي للقرآن الكريم للناشئة والكبار.",
    update_type: "إعلان",
    source_url: "/scientific-announcements/sci-quran-memorization-program",
    published_at: "2026-07-01T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-new-categories",
    title: "تحديث: إضافة فئات جديدة للإعجاز العلمي",
    summary: "إضافة 5 فئات جديدة من الإعجاز القرآني: الضوء، الجلد، العظام، النجوم، والدم.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-08T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-scholars-expanded",
    title: "تحديث: توسعة قاعدة بيانات العلماء",
    summary: "إضافة 6 علماء جدد من كبار أئمة الإسلام: ابن تيمية، النووي، ابن كثير، الشنقيطي، وآخرين.",
    update_type: "إعلان",
    source_url: "/tarikh-islami",
    published_at: "2026-07-08T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-adhkar-enriched",
    title: "تحديث: إثراء قسم الأذكار",
    summary: "إضافة 10 أذكار جديدة في فئات الخروج من المنزل، السوق، اللباس، وركوب السيارة.",
    update_type: "إعلان",
    source_url: "/adhkar",
    published_at: "2026-07-08T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-occasions-expanded",
    title: "تحديث: إضافة مناسبات إسلامية جديدة",
    summary: "إضافة عشر ذي الحجة، عيد الأضحى، عيد الفطر، وليلة النصف من شعبان في تقويم المناسبات.",
    update_type: "إعلان",
    source_url: "/occasions",
    published_at: "2026-07-08T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-islamic-stories-expanded",
    title: "تحديث: إضافة قصص إسلامية جديدة",
    summary: "إضافة 5 قصص إسلامية جديدة: عثمان بن عفان، علي بن أبي طالب، بلال الحبشي، فتح الأندلس، وعائشة أم المؤمنين.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-08T12:00:00Z",
    status: "approved",
  },
  {
    id: "update-sharia-rulings-expanded",
    title: "تحديث: توسعة موسوعة الأحكام الشرعية",
    summary: "إضافة 5 أحكام شرعية جديدة: موجبات الغسل، التيمم، أركان الحج، أنواع الطلاق، وشروط البيع.",
    update_type: "إعلان",
    source_url: "/rulings",
    published_at: "2026-07-08T11:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-expanded",
    title: "تحديث: إثراء الطب النبوي",
    summary: "إضافة 4 مواد جديدة في قسم الطب النبوي: الخل، العدس، النوم على الجنب الأيمن، والسواك.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-08T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-rulings-5-new",
    title: "تحديث: 5 أحكام شرعية جديدة",
    summary: "إضافة أحكام جديدة تشمل: القروض العقارية البنكية، زكاة الراتب، شروط الجمعة، أنواع العِدَّة، وأحكام التعصيب في الميراث.",
    update_type: "إعلان",
    source_url: "/rulings",
    published_at: "2026-07-08T15:00:00Z",
    status: "approved",
  },
  {
    id: "update-fawaid-curated-14",
    title: "تحديث: 14 فائدة علمية جديدة",
    summary: "إضافة فوائد منتقاة في العقيدة، الحديث، السيرة، اللغة، طلب العلم، والدعوة من كتب الأئمة والمحدثين.",
    update_type: "إعلان",
    source_url: "/fawaid",
    published_at: "2026-07-08T17:00:00Z",
    status: "approved",
  },
  {
    id: "update-scholars-65",
    title: "تحديث: الموسوعة العلمية تضم 65 عالماً",
    summary: "إضافة 10 علماء جدد منهم: الإمام الذهبي، ابن حجر، القرطبي، الشاطبي، ابن باز، ابن عثيمين، الألباني، والرازي.",
    update_type: "إعلان",
    source_url: "/tarikh-islami",
    published_at: "2026-07-06T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-v2",
    title: "تحديث: الطب النبوي — 5 عناصر جديدة وإصلاح تكرار",
    summary: "إضافة عناصر جديدة للطب النبوي: صلاة الفجر والضوء الصباحي، الزبيب، الوضوء بالماء البارد، الصدقة وأثرها النفسي، الشعير والتلبينة. مع إصلاح مُعرّفات مكررة.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-08T18:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-issues-5-new",
    title: "تحديث: 5 مسائل فقهية معاصرة جديدة",
    summary: "إضافة 5 مسائل فقهية: زراعة الشعر والتجميل، التمويل الجماعي، الصيام في البلاد القطبية، فسخ النكاح بسبب التدليس، وحكم CBD الطبي.",
    update_type: "إعلان",
    source_url: "/fiqh-council/issues",
    published_at: "2026-07-08T19:00:00Z",
    status: "approved",
  },
  {
    id: "update-scientific-announcements-5-new",
    title: "تحديث: 5 إعلانات علمية جديدة",
    summary: "إضافة إعلانات: دورة الفرائض، الفقه المقارن، مكثف مصطلح الحديث، السيرة المدنية، وندوة النوازل والفتاوى المعاصرة.",
    update_type: "إعلان",
    source_url: "/lessons",
    published_at: "2026-07-08T20:00:00Z",
    status: "approved",
  },
  {
    id: "update-library-108-books",
    title: "تحديث: المكتبة الشرعية تضم 108 كتاباً",
    summary: "إضافة 8 كتب جديدة: البداية والنهاية، مقدمة ابن خلدون، جامع العلوم والحكم لابن رجب، اقتضاء الصراط المستقيم، شرح الأربعين النووية، أسرار البلاغة، تلقيح فهوم أهل الأثر لابن الجوزي، أدب الدنيا والدين للماوردي.",
    update_type: "إعلان",
    source_url: "/library",
    published_at: "2026-07-08T21:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-660",
    title: "تحديث: بنك الأسئلة يتجاوز 660 سؤالاً",
    summary: "إضافة 15 سؤالاً جديداً (646-660) في الفقه والعقيدة والسيرة والقرآن والتاريخ الإسلامي.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-08T22:00:00Z",
    status: "approved",
  },
  {
    id: "update-rulings-43",
    title: "تحديث: الأحكام الشرعية تبلغ 43 حكماً",
    summary: "إضافة 4 أحكام: صلاة الجماعة، حكم الغيبة والنميمة، قضاء الصلاة الفائتة، شروط الاستطاعة في الحج.",
    update_type: "إعلان",
    source_url: "/rulings",
    published_at: "2026-07-09T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-49",
    title: "تحديث: قسم الإشارات الكونية — 49 موضوعًا",
    summary: "إضافة 3 معجزات علمية: مستقبلات الألم في الجلد، الحديد مُنزَّل من الكون، والماء أصل كل حياة.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-09T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-16",
    title: "تحديث: القصص الإسلامية — 16 قصة",
    summary: "إضافة 3 قصص: خالد بن الوليد سيف الله، فتح القدس وعدالة الفاروق، ابن بطوطة جوّال الإسلام الأعظم.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-09T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-qa-303",
    title: "تحديث: الأسئلة والأجوبة تبلغ 303 مسألة",
    summary: "إضافة 10 مسائل في الأذكار والأنبياء والآداب والقرآن والحديث والطهارة.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-08T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-courses-44",
    title: "تحديث: الدورات العلمية السنوية — 44 دورة",
    summary: "إضافة 5 دورات: مصطلح الحديث، الفقه الحنبلي (عمدة الفقه)، التفسير الموضوعي، السيرة النبوية التحليلية، علم الفرائض والمواريث.",
    update_type: "دورة",
    source_url: "/annual-courses",
    published_at: "2026-07-08T11:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-52",
    title: "تحديث: قسم الإشارات الكونية — 52 موضوعًا",
    summary: "إضافة 3 معجزات: بصمة الأصابع وفردانية الخلق، نظام التواصل لدى النحل، ودوران الليل والنهار آيةً في الأرض.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-08T12:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-19",
    title: "تحديث: القصص الإسلامية — 19 قصة",
    summary: "إضافة 3 قصص: صلاح الدين الأيوبي وفتح القدس، عمر بن الخطاب الفاروق العادل، الخوارزمي أبو الجبر والخوارزميات.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-08T13:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-670",
    title: "تحديث: بنك الأسئلة يتجاوز 670 سؤالاً",
    summary: "إضافة 10 أسئلة (661-670) في العقيدة والفقه والقرآن والسيرة والحديث والتاريخ والرقائق.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-08T14:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-680",
    title: "تحديث: بنك الأسئلة يبلغ 680 سؤالاً",
    summary: "إضافة 10 أسئلة جديدة (671-680) في مصطلح الحديث والصلاة والغزوات وعلوم القرآن والعقيدة والتاريخ والأخلاق والصيام والسيرة.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-08T15:00:00Z",
    status: "approved",
  },
  {
    id: "update-qa-313",
    title: "تحديث: الأسئلة الفقهية تبلغ 313 مسألة",
    summary: "إضافة 10 مسائل جديدة (304-313) في الصلاة والزكاة والحج والأذكار والأنبياء والصيام والعقيدة.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-08T16:00:00Z",
    status: "approved",
  },
  {
    id: "update-sheikhs-76",
    title: "تحديث: قاعدة العلماء تضم 76 عالماً",
    summary: "إضافة 5 علماء: البخاري ومسلم وابن تيمية وابن القيم والنووي إلى قائمة أئمة الأمة الكبار.",
    update_type: "إعلان",
    source_url: "/tarikh-islami",
    published_at: "2026-07-08T17:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-46",
    title: "تحديث: الطب النبوي — 46 مادة طبية",
    summary: "إضافة 6 مداخل: زيت الزيتون والتمر والحجامة والقرآن شفاء والصيام ونظرية الـ Autophagy.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-08T18:00:00Z",
    status: "approved",
  },
  {
    id: "update-courses-49",
    title: "تحديث: الدورات العلمية — 49 دورة",
    summary: "إضافة 5 دورات: شرح الطحاوية والبلاغة القرآنية وفقه المعاملات المالية والأذكار والنحو العربي.",
    update_type: "دورة",
    source_url: "/annual-courses",
    published_at: "2026-07-08T19:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-55",
    title: "تحديث: قسم الإشارات الكونية — 55 موضوعًا",
    summary: "إضافة 3 معجزات: تواصل النمل وظلمات البحار العميقة ودور النوم في تجديد الجسم (نظرية الـ Glymphatic).",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-08T20:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-21",
    title: "تحديث: القصص الإسلامية — 21 قصة",
    summary: "إضافة قصتين: طارق بن زياد فاتح الأندلس وجبل طارق، وابن بطوطة الرحّالة الأكبر في التاريخ الوسيط.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-08T21:00:00Z",
    status: "approved",
  },
  {
    id: "update-fawaid-330",
    title: "تحديث: الفوائد العلمية — 330 فائدة",
    summary: "إضافة 10 فوائد جديدة في الأخلاق والزهد والفقه والأذكار والقرآن والصبر والرحمة.",
    update_type: "إعلان",
    source_url: "/fawaid",
    published_at: "2026-07-08T22:00:00Z",
    status: "approved",
  },
  {
    id: "update-sheikhs-81",
    title: "تحديث: العلماء والمشايخ — 81 عالماً",
    summary: "إضافة 8 علماء جدد: أبو داود السجستاني والترمذي وابن ماجه والبيهقي والليث بن سعد وابن قدامة وعبد الرزاق الصنعاني وابن الجوزي.",
    update_type: "إعلان",
    source_url: "/tarikh-islami",
    published_at: "2026-07-11T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-library-148",
    title: "تحديث: المكتبة الإسلامية — 6 كتب جديدة",
    summary: "إضافة 6 كتب: فتح الباري وإعلام الموقعين والأذكار النووية والمبسوط والأم والتحرير والتنوير.",
    update_type: "إعلان",
    source_url: "/library",
    published_at: "2026-07-11T11:00:00Z",
    status: "approved",
  },
  {
    id: "update-courses-55",
    title: "تحديث: الدورات العلمية — 55+ دورة",
    summary: "إضافة 3 دورات: أحكام الحج والعمرة، والألفية للمتقدمين، والعقيدة أمام الشبهات المعاصرة.",
    update_type: "دورة",
    source_url: "/annual-courses",
    published_at: "2026-07-11T13:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-issues-53",
    title: "تحديث: المسائل الفقهية — 53 مسألة",
    summary: "إضافة 5 مسائل معاصرة: NFT والوقف الرقمي والجمعة للعامل عن بُعد وDNA وحكم منصات الترفيه.",
    update_type: "إعلان",
    source_url: "/fiqh-council/issues",
    published_at: "2026-07-11T14:00:00Z",
    status: "approved",
  },
  {
    id: "update-rulings-55",
    title: "تحديث: الأحكام الشرعية — 55 حكماً",
    summary: "إضافة 3 أحكام: التأمين الصحي والتجاري، والأعياد الوطنية، والاقتداء عبر البث المباشر.",
    update_type: "إعلان",
    source_url: "/rulings",
    published_at: "2026-07-11T15:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-68",
    title: "تحديث: إشارات كونية — 3 موضوعات",
    summary: "إضافة 3 معجزات: الثقب الأسود (الخنّس الكنّس)، الحاجز بين البحرين، وعلقة الجنين الجنينية.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-11T16:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-50",
    title: "تحديث: القصص الإسلامية — 50 قصة",
    summary: "الوصول إلى 50 قصة مفصّلة بإضافة جعفر بن أبي طالب وأم سلمة ونور الدين زنكي وفاطمة الفهري وسليمان القانوني والإمام النووي.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-11T18:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-72",
    title: "تحديث: الطب النبوي — 4 موضوعات جديدة",
    summary: "إضافة 4 موضوعات: ماء زمزم والتلبينة والسواك واليانسون.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-11T19:00:00Z",
    status: "approved",
  },
  {
    id: "update-tawhid-asma-husna-58",
    title: "تحديث: الأسماء الحسنى في صفحة التوحيد — 57 اسماً",
    summary: "توسعة قسم الأسماء الحسنى بإضافة 25 اسماً جديداً: الأول والآخر والظاهر والباطن والنور والهادي والبديع والصبور وغيرها.",
    update_type: "إعلان",
    source_url: "/tawhid",
    published_at: "2026-07-11T20:00:00Z",
    status: "approved",
  },
  {
    id: "update-rulings-58",
    title: "تحديث: الأحكام الشرعية — 58 حكماً",
    summary: "إضافة 3 أحكام: حكم الحج على المديون، وصيام مريض السكري، وميراث المفقود.",
    update_type: "فتوى",
    source_url: "/rulings",
    published_at: "2026-07-11T21:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-72",
    title: "تحديث: إشارات كونية — 4 موضوعات",
    summary: "إضافة 4 معجزات: نزول الحديد من الفضاء، مستقبلات الألم في الجلد، النجوم علامات للملاحة، الماء أساس الحياة.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-11T22:00:00Z",
    status: "approved",
  },
  {
    id: "update-sheikhs-86",
    title: "تحديث: قاعدة العلماء — 86 عالماً",
    summary: "إضافة 4 علماء: الإمام الذهبي، الإمام السيوطي، ابن حجر العسقلاني، الشوكاني.",
    update_type: "إعلان",
    source_url: "/tarikh-islami",
    published_at: "2026-07-11T23:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-77",
    title: "تحديث: إشارات كونية — 5 موضوعات",
    summary: "إضافة 5 معجزات: إعجاز النحل والعسل، الناصية مركز القرار، الدخان وتكوّن الكون، الأزواج في كل شيء، بصمات الأصابع.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-11T23:30:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-80",
    title: "تحديث: الطب النبوي — إضافة الرمان",
    summary: "إضافة موضوع الرمان وفوائده الغذائية ووروده في القرآن الكريم إلى مواد الطب النبوي.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-12T00:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-issues-56",
    title: "تحديث: مجمع الفقه — 56 مسألة معاصرة",
    summary: "إضافة 3 مسائل: حكم الاستفتاء من الذكاء الاصطناعي، عقد النكاح عبر الإنترنت، زكاة أسهم التقنية والسيارات الكهربائية.",
    update_type: "فتوى",
    source_url: "/fiqh-council/issues",
    published_at: "2026-07-12T01:00:00Z",
    status: "approved",
  },
  {
    id: "update-sheikhs-91",
    title: "تحديث: قاعدة العلماء — 91 عالماً",
    summary: "إضافة 4 علماء معاصرين: ابن باز، ابن عثيمين، الألباني، ابن جبرين.",
    update_type: "إعلان",
    source_url: "/tarikh-islami",
    published_at: "2026-07-12T02:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-52",
    title: "تحديث: القصص الإسلامية — 52 قصة",
    summary: "إضافة قصتين: خالد بن الوليد (سيف الله المسلول)، وعمر بن الخطاب (الفاروق).",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-12T04:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-822",
    title: "تحديث: مسابقة الاختبار الإسلامي — 822+ سؤال",
    summary: "إضافة 20 سؤالاً في: الصحابة الكرام، العلماء والأئمة، التاريخ الإسلامي، الفقه، القرآن، العقيدة، الفتوحات، الأنبياء، الأذكار.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-12T05:00:00Z",
    status: "approved",
  },
  {
    id: "update-fawaid-377",
    title: "تحديث: الفوائد العلمية — 377+ فائدة",
    summary: "إضافة 15 فائدة في: الصبر والتوكل، الدعاء للأخ، فضل التواضع، العلم والخشية، الرحمة، الصحبة الصالحة، ليلة القدر، الاستغفار، شكر الناس.",
    update_type: "إعلان",
    source_url: "/fawaid",
    published_at: "2026-07-12T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-courses-61",
    title: "تحديث: الدورات العلمية — 61+ دورة",
    summary: "إضافة 3 دورات: علم الفرائض والمواريث، البلاغة القرآنية والإعجاز البياني، شرح العقيدة الواسطية.",
    update_type: "دورة",
    source_url: "/annual-courses",
    published_at: "2026-07-12T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-adhkar-332",
    title: "تحديث: توسعة قسم الأذكار",
    summary: "إضافة 10 أذكار في: الصلاة الإبراهيمية، أذكار الوضوء، أذكار النوم، الصباح، الاستغفار.",
    update_type: "إعلان",
    source_url: "/adhkar",
    published_at: "2026-07-12T07:30:00Z",
    status: "approved",
  },
  {
    id: "update-perf-bundle-split",
    title: "تحسين: تقليل حجم حزمة خدمات المنصة",
    summary: "تقليل حجم حزمة خدمات المنصة (platform-services) من 103 كيلوبايت إلى 20 كيلوبايت بعد تحسين تقسيم الـ chunks، وتسريع التحميل الأولي.",
    update_type: "إعلان",
    source_url: "/updates",
    published_at: "2026-07-11T15:00:00Z",
    status: "approved",
  },
  {
    id: "update-seo-scholar-library-pages",
    title: "جديد: 99 صفحة عالم و50+ صفحة كتاب مُحسَّنة لمحركات البحث",
    summary: "أُضيف محتوى SEO مُفصَّل لصفحات 99 عالماً (منهم البخاري، الغزالي، ابن تيمية، ابن القيم، الألباني) و50+ كتاب في المكتبة، مع بيانات JSON-LD وعناوين دقيقة.",
    update_type: "إعلان",
    source_url: "/tarikh-islami",
    published_at: "2026-07-11T14:00:00Z",
    status: "approved",
  },
  {
    id: "update-sheikhs-101",
    title: "تحديث: قاعدة العلماء — إضافة 7 علماء",
    summary: "إضافة 7 علماء: القرضاوي، الزرقا، الزحيلي، الفوزان، الطنطاوي، بكر أبو زيد، ومحمد الغزالي.",
    update_type: "إعلان",
    source_url: "/tarikh-islami",
    published_at: "2026-07-12T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-qa-330",
    title: "تحديث: الأسئلة والأجوبة، 330+ سؤال",
    summary: "إضافة 10 أسئلة في: الصلاة، الصيام في السفر، الاجتهاد والتقليد، علم الإسناد، الزكاة، حج المرأة، أركان الإيمان.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-12T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-amr-bil-maruf-section",
    title: "قسم جديد: الأمر بالمعروف والنهي عن المنكر",
    summary: "أُضيف قسم شامل للأمر بالمعروف والنهي عن المنكر يتضمن المراتب الثلاث وشروطها وأحكامها وأقوال العلماء.",
    update_type: "إعلان",
    source_url: "/amr-bil-maruf",
    published_at: "2026-07-11T12:00:00Z",
    status: "approved",
  },
  {
    id: "update-islamic-orgs-expanded",
    title: "توسعة: الهيئات والمنظمات الإسلامية",
    summary: "تحوّل قسم المجمع الفقهي ليشمل: هيئة كبار العلماء، اللجنة الدائمة، رابطة العالم الإسلامي، إدارة الإفتاء الكويتية، المجلس الأوروبي للإفتاء.",
    update_type: "إعلان",
    source_url: "/fiqh-council",
    published_at: "2026-07-11T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-57",
    title: "تحديث: القصص الإسلامية — إضافة 5 قصص كاملة",
    summary: "إضافة 5 قصص تفصيلية: صلاح الدين الأيوبي وفتح القدس، خديجة بنت خويلد، طارق بن زياد، الإمام مالك، وغزوة بدر الكبرى.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-11T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-library-156",
    title: "توسعة: المكتبة الشرعية — إضافة 4 كتب موثقة",
    summary: "إضافة 4 كتب موثقة: الموافقات للشاطبي، منهاج الطالبين للنووي، الأدب المفرد للبخاري، والفقه على المذاهب الأربعة للجزيري.",
    update_type: "كتاب",
    source_url: "/library",
    published_at: "2026-07-11T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-89",
    title: "تحديث: الطب النبوي — إضافة 5 عناصر",
    summary: "إضافة 5 عناصر: العجوة، الحبة السوداء، الحجامة، الصيام الطوعي وفوائده العلمية، ماء زمزم.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-11T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-872",
    title: "تحديث: بنك الأسئلة يبلغ 872 سؤالاً",
    summary: "إضافة 16 سؤالاً تاريخياً وجغرافياً في فئات الأندلس (5 أسئلة)، الخلفاء، العلماء، المعارك، والفتوحات.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T12:00:00Z",
    status: "approved",
  },
  {
    id: "update-topics-12",
    title: "تحديث: شبكة المواضيع المشوقة — 12 موضوعاً",
    summary: "إضافة 4 مواضيع جديدة للصفحة الرئيسية: الشمائل المحمدية، الجنة والنار، فضائل الأعمال، وآداب طالب العلم.",
    update_type: "إعلان",
    source_url: "/",
    published_at: "2026-07-11T11:00:00Z",
    status: "approved",
  },
  {
    id: "update-sunnah-time-enriched",
    title: "تحديث: سنة اليوم — اقتراحات أكثر ثراءً",
    summary: "توسيع مقترحات سنة اليوم من 3 إلى 4-5 اقتراحات لكل وقت صلاة، تشمل: الفوائد، الرقائق، حكم السلف، الوصايا، والدروس.",
    update_type: "إعلان",
    source_url: "/",
    published_at: "2026-07-11T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-886",
    title: "بنك الأسئلة يبلغ 886 سؤالاً",
    summary: "إضافة 14 سؤالاً تاريخياً وعلمياً: 8 أسئلة في العلماء والأئمة (البخاري، النووي، الغزالي، ابن تيمية، الشافعي، ابن حجر، الأئمة الأربعة، ابن القيم)، و6 أسئلة في الأسماء الحسنى.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T14:00:00Z",
    status: "approved",
  },
  {
    id: "update-sitemap-amr",
    title: "تحديث خريطة الموقع",
    summary: "إضافة صفحة «الأمر بالمعروف والنهي عن المنكر» لخريطة الموقع، وإضافة موسمَي محرم 1448 وربيع الأول 1448 لويدجت مواسم التعلم.",
    update_type: "إعلان",
    source_url: "/sitemap",
    published_at: "2026-07-11T13:00:00Z",
    status: "approved",
  },
  {
    id: "update-daily-hadith-pool",
    title: "تحديث الركن اليومي — أحاديث الأربعين النووية",
    summary: "توسيع مجموعة «حديث اليوم» من 7 أحاديث إلى 44 حديثاً بإضافة الأربعين النووية الكاملة (42 حديثاً، منها 5 لها مدخل مستقل في البنك)، مما يوفر تنوعاً أسبوعياً أكبر.",
    update_type: "إعلان",
    source_url: "/arbaeen-nawawi",
    published_at: "2026-07-11T15:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-seed-896",
    title: "بنك الأسئلة يبلغ 896 سؤالاً",
    summary: "إضافة 10 أسئلة لقسم «الحديث» في بنك الأسئلة: الضعيف والموضوع والقدسي والمتواتر، ومسند أحمد، والجرح والتعديل، ومنهج البخاري.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T19:30:00Z",
    status: "approved",
  },
  {
    id: "update-aqeeda-37",
    title: "تعزيز قسم العقيدة — 37 سؤالاً",
    summary: "إضافة 7 أسئلة عقدية: صحف إبراهيم وموسى، تواتر القرآن، عذاب القبر ونعيمه، كرامات الأولياء، قاعدة التكفير عند أهل السنة.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T19:00:00Z",
    status: "approved",
  },
  {
    id: "update-hadith-seerah",
    title: "تعزيز الحديث (38 سؤالاً) والسيرة (38 سؤالاً)",
    summary: "إضافة 9 أسئلة حديثية: عدد البخاري، رياض الصالحين، الفرق بين السنة والحديث، الكتب الستة بالترتيب، علو الإسناد، منهج النووي. و9 أسئلة سيرة: أبو طالب، ربيع الأول، ثويبة وحليمة، غزوة تبوك، سرية مؤتة، رسائل الملوك، هجرة الحبشة.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T18:30:00Z",
    status: "approved",
  },
  {
    id: "update-anbiya-37",
    title: "تعزيز قسم قصص الأنبياء — 37 سؤالاً",
    summary: "إضافة 8 أسئلة جديدة: الأنبياء هود وصالح وشعيب ورسالتهم، اختصاص الله موسى عليه السلام بأن كلّمه تكليمًا، قصة الخضر، لماذا ألقى موسى الألواح عند رجوعه إلى قومه، قصص الكهف الثلاث.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T18:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-34",
    title: "تعزيز قسم الفقه — 34 سؤالاً",
    summary: "إضافة 7 أسئلة فقهية: نصاب الفضة، أسباب الإفطار، مبطلات الوضوء، شروط الصوم، أنواع الطلاق، زكاة الأموال.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T17:30:00Z",
    status: "approved",
  },
  {
    id: "update-tarikh-aqeeda",
    title: "تعزيز قسمَي التاريخ والعقيدة في لعبة المعرفة",
    summary: "إضافة 13 سؤالاً جديداً: 9 للتاريخ الإسلامي (الدولة الأموية، بغداد، اليرموك، الدولة العثمانية، سقوط الأندلس، المغول) و4 للعقيدة (النبي والرسول، الكفر، الخوارج والمرجئة، البدعة).",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T17:00:00Z",
    status: "approved",
  },
  {
    id: "update-akhlaq-37",
    title: "تحديث قسم الأخلاق والصحابة — 37 سؤالاً",
    summary: "إضافة 15 سؤالاً جديداً في قسم «الأخلاق والصحابة»: صفات الصحابة وسيرهم (أبو هريرة، فاطمة الزهراء، عبد الرحمن بن عوف، أبو عبيدة، ابن مسعود)، والأخلاق النبوية (الصدق، الحياء، الورع، الكبر، الرضا).",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T16:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-926",
    title: "الموسوعة التفاعلية — 926 سؤالاً وتصحيح مسارات التصنيف",
    summary: "إضافة 30 سؤالاً جديداً: 10 في الأذكار والأدعية (التسبيح، سيد الاستغفار، الباقيات الصالحات، الصلاة الإبراهيمية)، 10 في الرقائق والزهد (التوبة، الورع، الصبر، التوكل، أمراض القلب)، 10 في الحج (واجبات الحج، العمرة، المحظورات، أنواع الحج، حجة الوداع). كذلك تصحيح تصنيف أقسام الأذكار والرقائق والحج والعمرة والألغاز الشرعية.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T20:00:00Z",
    status: "approved",
  },
  {
    id: "update-daily-ayah",
    title: "توسيع حوض آيات اليوم إلى 30 آية",
    summary: "توسيع حوض الآيات اليومية من 7 إلى 30 آية قرآنية تشمل: آيات الصبر والتوكل والرحمة والذكر والتقوى والإيمان والتوبة.",
    update_type: "إعلان",
    source_url: "/",
    published_at: "2026-07-11T21:00:00Z",
    status: "approved",
  },
  {
    id: "update-glossary-130",
    title: "موسوعة المصطلحات — 130 مصطلحاً إسلامياً",
    summary: "إضافة 15 مصطلحاً جديداً في موسوعة المصطلحات الإسلامية: الفتوى، الكفارة، الغيبة والنميمة، الرقية الشرعية، التواضع والكِبْر، الجهاد وأقسامه، الصحيح لغيره والحسن لغيره، هجرة الحبشة، الشريعة والفقه، الحسد والغِبطة، الجماعة وإمامة الصلاة، الأضحية، الصحابي والتابعي، الإجازة العلمية، الذكاء الاصطناعي والفقه.",
    update_type: "إعلان",
    source_url: "/islamic-glossary",
    published_at: "2026-07-11T21:30:00Z",
    status: "approved",
  },
  {
    id: "update-stories-64",
    title: "القصص الإسلامية — إضافة 3 قصص تاريخية مهمة",
    summary: "إضافة 3 قصص: عمر بن عبد العزيز (الخليفة الزاهد)، فتح الأندلس (طارق بن زياد)، فتح القسطنطينية (محمد الفاتح). كل قصة تتضمن المحتوى الكامل والدروس والمراجع.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-11T22:00:00Z",
    status: "approved",
  },
  {
    id: "update-glossary-150",
    title: "موسوعة المصطلحات الإسلامية — 150 مصطلحاً",
    summary: "توسيع الموسوعة من 130 إلى 150 مصطلحاً بإضافة 20 مصطلحاً جديداً تشمل: الولاء والبراء، الرخصة والعزيمة، الحديث القدسي، المكي والمدني، الناسخ والمنسوخ، الوقف والابتداء، غزوة بدر، صلح الحديبية، غزوة أُحد، الإسراء والمعراج، التوبة النصوح، الورع، المراقبة، الزهد، الإجماع، القياس، النية في العبادة، المعجزة والكرامة، الإجارة والأجرة، الشاهد والمتابع.",
    update_type: "إعلان",
    source_url: "/islamic-glossary",
    published_at: "2026-07-11T23:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-950",
    title: "موسوعة الاختبارات — 950 سؤالاً وثلاثة أقسام جديدة",
    summary: "إضافة 24 سؤالاً جديداً: 10 في الفرائض والمواريث (أسباب الإرث وموانعه، الفروض، الحجب، التعصيب، العول والرد)، 7 في الأسماء الحسنى (المعنى والفضل والإحصاء)، 7 في العلماء والأئمة (الأئمة الأربعة، البخاري، الطبري، الشافعي، ابن تيمية، ابن حزم). المجموع الكلي: 950 سؤالاً.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T23:30:00Z",
    status: "approved",
  },
  {
    id: "update-duas-74",
    title: "مكتبة الأدعية الشرعية — 74 دعاءً موثقاً",
    summary: "توسيع مكتبة الأدعية من 61 إلى 74 دعاءً بإضافة: 4 أدعية الصلاة (الاستفتاح، القنوت، بين السجدتين، التسبيح بعد الصلاة)، 3 أدعية النوم (الاستخارة، الرؤيا الحسنة، الرؤيا المزعجة)، 3 أدعية الكرب (الغضب، قضاء الدين، فرج الكرب بالتوحيد)، 3 أدعية عامة (الثبات، التوكل، الاستعاذة الجامعة). كل دعاء مع النص العربي والمصدر الصحيح.",
    update_type: "إعلان",
    source_url: "/duas",
    published_at: "2026-07-11T23:45:00Z",
    status: "approved",
  },
];

export function getSortedUpdates(limit?: number) {
  const sorted = [...UPDATES_SEED].sort(
    (a, b) => (b.published_at || "").localeCompare(a.published_at || ""),
  );
  return limit ? sorted.slice(0, limit) : sorted;
}
