import type { PlatformUpdate } from "./platform-types";

export const UPDATES_SEED: PlatformUpdate[] = [
  {
    id: "update-fiqh-crypto",
    title: "قرار جديد: حكم التعامل بالعملات الرقمية",
    summary: "صدر قرار المجمع الفقهي بشأن العملات الرقمية.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_id: "fiqh-crypto-2024",
    source_url: "/fiqh-council/fiqh-crypto-2024",
    published_at: "2024-03-15T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-travel",
    title: "فتوى جديدة: الإفطار للمسافر في رمضان",
    summary: "إضافة فتوى حول جواز الإفطار للمسافر.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_id: "fatwa-fasting-travel",
    source_url: "/fatwa/fatwa-fasting-travel",
    published_at: "2024-02-28T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-course-ijazah",
    title: "فتح التسجيل: دورة الإجازة 1447هـ",
    summary: "بدء التسجيل في الدورة السنوية للإجازة.",
    update_type: "دورة",
    source_type: "annual_course",
    source_id: "course-ijazah-tahrir-2026",
    source_url: "/annual-courses/course-ijazah-tahrir-2026",
    published_at: "2025-12-01T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-tafsir",
    title: "درس جديد: تفسير سورة النحل",
    summary: "انضم درس تفسير سورة النحل إلى جدول الدروس.",
    update_type: "درس",
    source_type: "lesson",
    source_id: "kw-othman-tafsir-nahl-0",
    source_url: "/lessons/kw-othman-tafsir-nahl-0",
    published_at: "2025-11-20T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-library-book",
    title: "كتاب جديد: رياض الصالحين",
    summary: "إضافة كتاب رياض الصالحين إلى المكتبة العلمية.",
    update_type: "كتاب",
    source_type: "library",
    source_url: "/library",
    published_at: "2025-11-10T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-ramadan",
    title: "إعلان: البرنامج العلمي الرمضاني 1447",
    summary: "إعلان عن بدء البرنامج العلمي في شهر رمضان.",
    update_type: "إعلان",
    source_url: "/annual-courses/course-ramadan-intensive",
    published_at: "2025-11-15T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-news-conference",
    title: "خبر علمي: مؤتمر الفقه المعاصر",
    summary: "انعقاد مؤتمر الفقه المعاصر ونشر أبحاثه.",
    update_type: "خبر علمي",
    source_url: "/fiqh-council",
    published_at: "2025-10-01T05:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-prayer-timing",
    title: "فتوى جديدة: الصلاة بالتوقيت الفلكي",
    summary: "صدور فتوى تُجيز الاعتماد على حسابات التوقيت الفلكي لتحديد أوقات الصلاة.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fatwa/fatwa-prayer-timing",
    published_at: "2026-06-15T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-zakat-crypto",
    title: "قرار جديد: زكاة العملات الرقمية",
    summary: "إصدار قرار فقهي بوجوب الزكاة على العملات الرقمية وكيفية احتسابها.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/zakat-crypto",
    published_at: "2026-05-20T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-usul-fiqh",
    title: "درس جديد: أصول الفقه المقارن",
    summary: "إضافة سلسلة دروس في أصول الفقه المقارن بين المذاهب.",
    update_type: "درس",
    source_type: "lesson",
    source_url: "/lessons/usul-fiqh-muqaran",
    published_at: "2026-05-10T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-book-fiqh-muyassar",
    title: "كتاب جديد: الفقه الميسر",
    summary: "إضافة كتاب الفقه الميسر في ضوء الكتاب والسنة إلى المكتبة.",
    update_type: "كتاب",
    source_type: "library",
    source_url: "/library",
    published_at: "2026-04-25T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-annual-forum",
    title: "إعلان: الملتقى الفقهي السنوي 1448هـ",
    summary: "الإعلان عن انعقاد الملتقى الفقهي السنوي وموضوعاته الرئيسية.",
    update_type: "إعلان",
    source_url: "/fiqh-council",
    published_at: "2026-04-01T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-news-conference-research",
    title: "خبر علمي: نشر أبحاث مؤتمر الفقه الطبي",
    summary: "نشر وقائع وأبحاث مؤتمر الفقه الطبي المعاصر.",
    update_type: "خبر علمي",
    source_url: "/fiqh-council",
    published_at: "2026-03-15T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-general-anesthesia",
    title: "فتوى جديدة: حكم التخدير الكلي في الجراحة",
    summary: "بيان جواز التخدير الكلي عند الضرورة الطبية.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/general-anesthesia",
    published_at: "2026-03-01T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-human-cloning",
    title: "قرار جديد: تحريم الاستنساخ البشري التكاثري",
    summary: "قرار فقهي بتحريم الاستنساخ البشري التكاثري وبيان ضوابط العلاجي.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/human-cloning",
    published_at: "2026-02-10T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-course-tibb-fiqhi",
    title: "فتح التسجيل: دورة الفقه الطبي 1447هـ",
    summary: "بدء التسجيل في الدورة التخصصية للفقه الطبي المعاصر.",
    update_type: "دورة",
    source_type: "annual_course",
    source_url: "/annual-courses/course-tibb-fiqhi-2026",
    published_at: "2026-01-15T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-bulugh-maram",
    title: "درس جديد: شرح بلوغ المرام",
    summary: "إضافة سلسلة شرح بلوغ المرام من الأدلة إلى جدول الدروس.",
    update_type: "درس",
    source_type: "lesson",
    source_url: "/lessons/bulugh-al-maram-sharh",
    published_at: "2026-01-05T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-book-contemporary-fiqh",
    title: "كتاب جديد: المسائل الفقهية المعاصرة",
    summary: "إضافة كتاب المسائل الفقهية المعاصرة ودراسة أدلتها إلى المكتبة.",
    update_type: "كتاب",
    source_type: "library",
    source_url: "/library",
    published_at: "2025-12-20T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-winter-course",
    title: "إعلان: الدورة الشتوية العلمية 1447هـ",
    summary: "الإعلان عن موعد وبرنامج الدورة الشتوية العلمية.",
    update_type: "إعلان",
    source_url: "/annual-courses",
    published_at: "2025-12-10T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-misyar-marriage",
    title: "فتوى جديدة: حكم زواج المسيار",
    summary: "بيان أحكام وضوابط زواج المسيار وأثره على الحقوق الزوجية.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/misyar-marriage",
    published_at: "2025-11-25T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-news-family-forum",
    title: "خبر علمي: ملتقى الأسرة المسلمة المعاصرة",
    summary: "انعقاد ملتقى الأسرة المسلمة المعاصرة ومخرجاته الفقهية.",
    update_type: "خبر علمي",
    source_url: "/fiqh-council",
    published_at: "2025-11-01T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-electronic-divorce",
    title: "فتوى جديدة: الطلاق الإلكتروني",
    summary: "بيان وقوع الطلاق عبر الرسائل الإلكترونية ووسائل التواصل.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/electronic-divorce",
    published_at: "2025-10-15T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-tajweed",
    title: "درس جديد: أحكام التجويد العملي",
    summary: "إضافة سلسلة أحكام التجويد العملي مع التطبيق إلى جدول الدروس.",
    update_type: "درس",
    source_type: "lesson",
    source_url: "/lessons/tajweed-applied",
    published_at: "2025-10-01T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-health-insurance",
    title: "قرار جديد: حكم التأمين الصحي",
    summary: "قرار فقهي في جواز التأمين الصحي التعاوني وضوابط التجاري.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/health-insurance-ruling",
    published_at: "2025-09-20T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-course-ijazah-2025",
    title: "فتح التسجيل: دورة الإجازة العلمية 1447هـ",
    summary: "بدء التسجيل في دورة الإجازة العلمية لهذا العام.",
    update_type: "دورة",
    source_type: "annual_course",
    source_url: "/annual-courses/course-ijazah-2025",
    published_at: "2025-09-01T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-book-arbaeen-nawawi",
    title: "كتاب جديد: شرح الأربعين النووية",
    summary: "إضافة شرح الأربعين النووية في ضوء الفقه المعاصر إلى المكتبة.",
    update_type: "كتاب",
    source_type: "library",
    source_url: "/library",
    published_at: "2025-08-25T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-ilm-initiative",
    title: "إعلان: مبادرة العلم للجميع",
    summary: "إطلاق مبادرة العلم للجميع لتيسير وصول المحتوى العلمي.",
    update_type: "إعلان",
    source_url: "/",
    published_at: "2025-08-10T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-astronaut-prayer",
    title: "فتوى جديدة: صلاة رواد الفضاء",
    summary: "بيان أوقات الصلاة واتجاه القبلة لرواد الفضاء في المدار الأرضي.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/astronaut-prayer",
    published_at: "2025-07-20T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-news-digital-fiqh",
    title: "خبر علمي: ندوة الفقه الرقمي",
    summary: "انعقاد ندوة الفقه الرقمي وأبحاثها في المعاملات الإلكترونية.",
    update_type: "خبر علمي",
    source_url: "/fiqh-council",
    published_at: "2025-07-01T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-seerah",
    title: "درس جديد: السيرة النبوية المقارنة",
    summary: "إضافة سلسلة دروس السيرة النبوية المقارنة مع المصادر التاريخية.",
    update_type: "درس",
    source_type: "lesson",
    source_url: "/lessons/seerah-muqarana",
    published_at: "2025-06-15T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-new-sections",
    title: "تحديث المسابقات: إضافة أسئلة جديدة",
    summary: "إضافة 25 سؤالاً جديداً في الأخلاق وعلوم القرآن والحديث والألغاز الشرعية.",
    update_type: "خبر علمي",
    source_url: "/quiz",
    published_at: "2026-07-08T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-ai-jurisprudence",
    title: "فتوى جديدة: الذكاء الاصطناعي في الاجتهاد الفقهي",
    summary: "بيان ضوابط الاستعانة بأدوات الذكاء الاصطناعي في البحث الفقهي والإفتاء.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/ai-jurisprudence",
    published_at: "2026-07-05T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-waqf-digital",
    title: "قرار جديد: الوقف الرقمي",
    summary: "قرار فقهي بإقرار الوقف الرقمي كنوع مستجد من أنواع الوقف المشروع.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/waqf-digital",
    published_at: "2026-07-03T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-course-summer-2026",
    title: "فتح التسجيل: الدورة العلمية الصيفية 1448هـ",
    summary: "بدء التسجيل في الدورة العلمية الصيفية وبرنامجها التفصيلي.",
    update_type: "دورة",
    source_type: "annual_course",
    source_url: "/annual-courses",
    published_at: "2026-07-01T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-quran-memorize",
    title: "إعلان: برنامج حفظ القرآن الصيفي 1448هـ",
    summary: "انطلاق برنامج الحفظ الصيفي للقرآن الكريم للناشئة والكبار.",
    update_type: "إعلان",
    source_url: "/scientific-announcements/sci-quran-memorization-program",
    published_at: "2026-07-01T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-book-maqasid-shariah",
    title: "كتاب جديد: مقاصد الشريعة الإسلامية",
    summary: "إضافة كتاب مقاصد الشريعة الإسلامية لابن عاشور إلى المكتبة العلمية.",
    update_type: "كتاب",
    source_type: "library",
    source_url: "/library",
    published_at: "2026-06-28T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-news-isesco-forum",
    title: "خبر علمي: ملتقى منظمة إيسيسكو للفقه الإسلامي",
    summary: "اختتام ملتقى منظمة إيسيسكو الدولي للفقه الإسلامي وقراراته الختامية.",
    update_type: "خبر علمي",
    source_url: "/fiqh-council",
    published_at: "2026-06-25T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-new-categories",
    title: "تحديث: إضافة فئات جديدة للإعجاز العلمي",
    summary: "إضافة 5 فئات جديدة من الإعجاز القرآني: الضوء، الجلد، العظام، النجوم، والدم.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-08T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-scholars-expanded",
    title: "تحديث: توسعة قاعدة بيانات العلماء",
    summary: "إضافة 6 علماء جدد من كبار أئمة الإسلام: ابن تيمية، النووي، ابن كثير، الشنقيطي، وآخرين.",
    update_type: "إعلان",
    source_url: "/lessons",
    published_at: "2026-07-08T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-adhkar-enriched",
    title: "تحديث: إثراء قسم الأذكار",
    summary: "إضافة 10 أذكار جديدة في فئات الخروج من المنزل، السوق، اللباس، وركوب السيارة.",
    update_type: "إعلان",
    source_url: "/adhkar",
    published_at: "2026-07-08T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-occasions-expanded",
    title: "تحديث: إضافة مناسبات إسلامية جديدة",
    summary: "إضافة عشر ذي الحجة، عيد الأضحى، عيد الفطر، وليلة نصف شعبان في تقويم المناسبات.",
    update_type: "إعلان",
    source_url: "/prayer-times",
    published_at: "2026-07-08T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-islamic-stories-expanded",
    title: "تحديث: إضافة قصص إسلامية جديدة",
    summary: "إضافة 5 قصص إسلامية جديدة: عثمان بن عفان، علي بن أبي طالب، بلال الحبشي، فتح الأندلس، وعائشة أم المؤمنين.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-08T12:00:00Z",
    status: "approved",
  },
  {
    id: "update-sharia-rulings-expanded",
    title: "تحديث: توسعة موسوعة الأحكام الشرعية",
    summary: "إضافة 5 أحكام شرعية جديدة: موجبات الغسل، التيمم، أركان الحج، أنواع الطلاق، وشروط البيع.",
    update_type: "إعلان",
    source_url: "/rulings",
    published_at: "2026-07-08T11:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-expanded",
    title: "تحديث: إثراء الطب النبوي",
    summary: "إضافة 4 مواد جديدة في قسم الطب النبوي: الخل، العدس، النوم على الجنب الأيمن، والسواك.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-08T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-rulings-5-new",
    title: "تحديث: 5 أحكام شرعية جديدة",
    summary: "إضافة أحكام جديدة تشمل: القروض العقارية البنكية، زكاة الراتب، شروط الجمعة، أنواع العِدَّة، وأحكام التعصيب في الميراث.",
    update_type: "إعلان",
    source_url: "/rulings",
    published_at: "2026-07-08T15:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-sessions-expanded",
    title: "تحديث: إضافة جلسات مجمع فقهي تاريخية",
    summary: "إضافة 5 جلسات جديدة للمجمع الفقهي الإسلامي (14-17 و23) تغطي موضوعات الجائحة، التأمين، التمويل الإسلامي، والوصايا الرقمية.",
    update_type: "إعلان",
    source_url: "/fiqh-council",
    published_at: "2026-07-08T16:00:00Z",
    status: "approved",
  },
  {
    id: "update-fawaid-curated-14",
    title: "تحديث: 14 فائدة علمية جديدة",
    summary: "إضافة فوائد منتقاة في العقيدة، الحديث، السيرة، اللغة، طلب العلم، والدعوة من كتب الأئمة والمحدثين.",
    update_type: "إعلان",
    source_url: "/fawaid",
    published_at: "2026-07-08T17:00:00Z",
    status: "approved",
  },
  {
    id: "update-scholars-65",
    title: "تحديث: الموسوعة العلمية تضم 65 عالماً",
    summary: "إضافة 10 علماء جدد منهم: الإمام الذهبي، ابن حجر، القرطبي، الشاطبي، ابن باز، ابن عثيمين، الألباني، والرازي.",
    update_type: "إعلان",
    source_url: "/sheikhs",
    published_at: "2026-07-06T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-v2",
    title: "تحديث: الطب النبوي — 5 عناصر جديدة وإصلاح تكرار",
    summary: "إضافة عناصر جديدة للطب النبوي: صلاة الفجر والضوء الصباحي، الزبيب، الوضوء بالماء البارد، الصدقة وأثرها النفسي، الشعير والتلبينة. مع إصلاح مُعرّفات مكررة.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-08T18:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-issues-5-new",
    title: "تحديث: 5 مسائل فقهية معاصرة جديدة",
    summary: "إضافة 5 مسائل فقهية: زراعة الشعر والتجميل، التمويل الجماعي، الصيام في البلاد القطبية، فسخ النكاح بسبب التدليس، وحكم CBD الطبي.",
    update_type: "إعلان",
    source_url: "/fiqh-council",
    published_at: "2026-07-08T19:00:00Z",
    status: "approved",
  },
  {
    id: "update-scientific-announcements-5-new",
    title: "تحديث: 5 إعلانات علمية جديدة",
    summary: "إضافة إعلانات: دورة الفرائض، الفقه المقارن، مكثف مصطلح الحديث، السيرة المدنية، وندوة النوازل والفتاوى المعاصرة.",
    update_type: "إعلان",
    source_url: "/lessons",
    published_at: "2026-07-08T20:00:00Z",
    status: "approved",
  },
  {
    id: "update-library-108-books",
    title: "تحديث: المكتبة الشرعية تضم 108 كتاباً",
    summary: "إضافة 8 كتب جديدة: البداية والنهاية، مقدمة ابن خلدون، أسرار الحِكَم لابن رجب، اقتضاء الصراط، شرح الأربعين، أسرار البلاغة، تلقيح فهوم ابن الجوزي، أدب الدنيا والدين للماوردي.",
    update_type: "إعلان",
    source_url: "/library",
    published_at: "2026-07-08T21:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-660",
    title: "تحديث: بنك الأسئلة يتجاوز 660 سؤالاً",
    summary: "إضافة 30 سؤالاً جديداً (646-660) في الفقه والعقيدة والسيرة والقرآن والتاريخ الإسلامي.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-08T22:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwas-74",
    title: "تحديث: الفتاوى الموثقة تبلغ 74 فتوى",
    summary: "إضافة 4 فتاوى: شروط الخُلع، كفارة اليمين، زكاة العملات الرقمية، نصيب الزوجة من الميراث.",
    update_type: "إعلان",
    source_url: "/fatwa",
    published_at: "2026-07-08T23:00:00Z",
    status: "approved",
  },
  {
    id: "update-rulings-43",
    title: "تحديث: الأحكام الشرعية تبلغ 43 حكماً",
    summary: "إضافة 4 أحكام: صلاة الجماعة، حكم الغيبة والنميمة، قضاء الصلاة الفائتة، شروط الاستطاعة في الحج.",
    update_type: "إعلان",
    source_url: "/rulings",
    published_at: "2026-07-09T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-49",
    title: "تحديث: الإعجاز العلمي يضم 49 معجزة",
    summary: "إضافة 3 معجزات علمية: مستقبلات الألم في الجلد، الحديد مُنزَّل من الكون، والماء أصل كل حياة.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-09T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-16",
    title: "تحديث: القصص الإسلامية — 16 قصة",
    summary: "إضافة 3 قصص: خالد بن الوليد سيف الله، فتح القدس وعدالة الفاروق، ابن بطوطة جوّال الإسلام الأعظم.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-09T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-council-17",
    title: "تحديث: قرارات المجمع الفقهي — 17 قراراً",
    summary: "إضافة 5 قرارات: حكم تغيير الجنس، البيع بالتقسيط، التبرع بالدم وبيعه، صيام المناطق القطبية، شهادات الحلال.",
    update_type: "قرار",
    source_url: "/fiqh",
    published_at: "2026-07-08T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-qa-303",
    title: "تحديث: الأسئلة والأجوبة تبلغ 303 مسألة",
    summary: "إضافة 10 مسائل في الأذكار والأنبياء والآداب والقرآن والحديث والطهارة.",
    update_type: "إعلان",
    source_url: "/qa",
    published_at: "2026-07-08T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-courses-44",
    title: "تحديث: الدورات العلمية السنوية — 44 دورة",
    summary: "إضافة 5 دورات: مصطلح الحديث، الفقه الحنبلي (عمدة الفقه)، التفسير الموضوعي، السيرة النبوية التحليلية، علم الفرائض والمواريث.",
    update_type: "دورة",
    source_url: "/lessons",
    published_at: "2026-07-08T11:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-52",
    title: "تحديث: الإعجاز العلمي — 52 معجزة موثّقة",
    summary: "إضافة 3 معجزات: بصمة الأصابع وفردانية الخلق، نظام النحل والخلية السداسية، دوران الليل والنهار ودلالة كلمة «يُكوِّر».",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-08T12:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-19",
    title: "تحديث: القصص الإسلامية — 19 قصة",
    summary: "إضافة 3 قصص: صلاح الدين الأيوبي وفتح القدس، عمر بن الخطاب الفاروق العادل، الخوارزمي أبو الجبر والخوارزميات.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-08T13:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-670",
    title: "تحديث: بنك الأسئلة يتجاوز 670 سؤالاً",
    summary: "إضافة 10 أسئلة (661-670) في العقيدة والفقه والقرآن والسيرة والحديث والتاريخ والرقائق.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-08T14:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-680",
    title: "تحديث: بنك الأسئلة يبلغ 680 سؤالاً",
    summary: "إضافة 10 أسئلة جديدة (671-680) في مصطلح الحديث والصلاة والغزوات وعلوم القرآن والعقيدة والتاريخ والأخلاق والصيام والسيرة.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-08T15:00:00Z",
    status: "approved",
  },
  {
    id: "update-qa-313",
    title: "تحديث: الأسئلة الفقهية تبلغ 313 مسألة",
    summary: "إضافة 10 مسائل جديدة (304-313) في الصلاة والزكاة والحج والأذكار والأنبياء والصيام والعقيدة.",
    update_type: "إعلان",
    source_url: "/qa",
    published_at: "2026-07-08T16:00:00Z",
    status: "approved",
  },
  {
    id: "update-sheikhs-76",
    title: "تحديث: قاعدة العلماء تضم 76 عالماً",
    summary: "إضافة 6 علماء: البخاري ومسلم وابن تيمية وابن القيم والنووي إلى قائمة أئمة الأمة الكبار.",
    update_type: "إعلان",
    source_url: "/scholars",
    published_at: "2026-07-08T17:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-46",
    title: "تحديث: الطب النبوي — 46 مادة طبية",
    summary: "إضافة 5 مداخل: زيت الزيتون والتمر والحجامة والقرآن شفاء والصيام ونظرية الـ Autophagy.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-08T18:00:00Z",
    status: "approved",
  },
  {
    id: "update-courses-49",
    title: "تحديث: الدورات العلمية — 49 دورة",
    summary: "إضافة 5 دورات: شرح الطحاوية والبلاغة القرآنية وفقه المعاملات المالية والأذكار والنحو العربي.",
    update_type: "دورة",
    source_url: "/lessons",
    published_at: "2026-07-08T19:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-55",
    title: "تحديث: الإعجاز العلمي — 55 معجزة",
    summary: "إضافة 3 معجزات: تواصل النمل وظلمات البحار العميقة ودور النوم في تجديد الجسم (نظرية الـ Glymphatic).",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-08T20:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-21",
    title: "تحديث: القصص الإسلامية — 21 قصة",
    summary: "إضافة قصتين: طارق بن زياد فاتح الأندلس وجبل طارق، وابن بطوطة الرحّالة الأكبر في التاريخ الوسيط.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-08T21:00:00Z",
    status: "approved",
  },
  {
    id: "update-fawaid-330",
    title: "تحديث: الفوائد العلمية — 330 فائدة",
    summary: "إضافة 10 فوائد جديدة في الأخلاق والزهد والفقه والأذكار والقرآن والصبر والرحمة.",
    update_type: "إعلان",
    source_url: "/fawaid",
    published_at: "2026-07-08T22:00:00Z",
    status: "approved",
  },
  {
    id: "update-sheikhs-81",
    title: "تحديث: العلماء والمشايخ — 81 عالماً",
    summary: "إضافة 7 علماء جدد: أبو داود السجستاني والترمذي وابن ماجه والبيهقي والليث بن سعد وابن قدامة وعبد الرزاق الصنعاني وابن الجوزي.",
    update_type: "إعلان",
    source_url: "/scholars",
    published_at: "2026-07-11T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-library-148",
    title: "تحديث: المكتبة الإسلامية — 148+ كتاب",
    summary: "إضافة 8 كتب: فتح الباري وإعلام الموقعين والأذكار النووية والمبسوط والأم والتحرير والتنوير.",
    update_type: "إعلان",
    source_url: "/library",
    published_at: "2026-07-11T11:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-council-37",
    title: "تحديث: المجمع الفقهي — 37+ قرار ومبحث",
    summary: "إضافة 4 قرارات: التجميل وزكاة الأسهم والذكاء الاصطناعي في الإفتاء والعمل في المصارف الربوية.",
    update_type: "قرار",
    source_url: "/fiqh-council",
    published_at: "2026-07-11T12:00:00Z",
    status: "approved",
  },
  {
    id: "update-courses-55",
    title: "تحديث: الدورات العلمية — 55+ دورة",
    summary: "إضافة 3 دورات: أحكام الحج والعمرة، والألفية للمتقدمين، والعقيدة أمام الشبهات المعاصرة.",
    update_type: "دورة",
    source_url: "/lessons",
    published_at: "2026-07-11T13:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-issues-53",
    title: "تحديث: المسائل الفقهية — 53 مسألة",
    summary: "إضافة 5 مسائل معاصرة: NFT والوقف الرقمي والجمعة للعامل عن بُعد وDNA وحكم منصات الترفيه.",
    update_type: "إعلان",
    source_url: "/fiqh-issues",
    published_at: "2026-07-11T14:00:00Z",
    status: "approved",
  },
  {
    id: "update-rulings-55",
    title: "تحديث: الأحكام الشرعية — 55 حكماً",
    summary: "إضافة 3 أحكام: التأمين الصحي والتجاري، والأعياد الوطنية، والاقتداء عبر البث المباشر.",
    update_type: "إعلان",
    source_url: "/rulings",
    published_at: "2026-07-11T15:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-68",
    title: "تحديث: الإعجاز العلمي — 68 معجزة",
    summary: "إضافة 3 معجزات: الثقب الأسود (الخنّس الكنّس)، الحاجز بين البحرين، وعلقة الجنين الجنينية.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-11T16:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwas-105",
    title: "تحديث: الفتاوى الشرعية — 105 فتوى",
    summary: "إضافة 5 فتاوى في فئات نحيفة: وقت الشاشة للأطفال، الخلاف الأسري، الحنث باليمين، النذر المشروط، إضافات الطعام (E-numbers).",
    update_type: "فتوى",
    source_url: "/fatwa",
    published_at: "2026-07-11T17:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-50",
    title: "تحديث: القصص الإسلامية — 50 قصة",
    summary: "الوصول إلى 50 قصة مفصّلة بإضافة جعفر بن أبي طالب وأم سلمة ونور الدين زنكي وفاطمة الفهري وسليمان القانوني والإمام النووي.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-11T18:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-72",
    title: "تحديث: الطب النبوي — 72+ موضوع",
    summary: "إضافة 4 موضوعات: ماء زمزم والتلبينة والسواك واليانسون.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-11T19:00:00Z",
    status: "approved",
  },
  {
    id: "update-tawhid-asma-husna-58",
    title: "تحديث: الأسماء الحسنى في صفحة التوحيد — 58 اسماً",
    summary: "توسعة قسم الأسماء الحسنى بإضافة 25 اسماً جديداً: الأول والآخر والظاهر والباطن والنور والهادي والبديع والصبور وغيرها.",
    update_type: "إعلان",
    source_url: "/tawhid",
    published_at: "2026-07-11T20:00:00Z",
    status: "approved",
  },
  {
    id: "update-rulings-58",
    title: "تحديث: الأحكام الشرعية — 58 حكماً",
    summary: "إضافة 3 أحكام: حكم الحج على المديون، وصيام مريض السكري، وميراث المفقود.",
    update_type: "فتوى",
    source_url: "/rulings",
    published_at: "2026-07-11T21:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-72",
    title: "تحديث: الإعجاز العلمي — 72 معجزة",
    summary: "إضافة 4 معجزات: نزول الحديد من الفضاء، مستقبلات الألم في الجلد، النجوم علامات للملاحة، الماء أساس الحياة.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-11T22:00:00Z",
    status: "approved",
  },
  {
    id: "update-sheikhs-86",
    title: "تحديث: قاعدة العلماء — 86 عالماً",
    summary: "إضافة 5 علماء: الإمام الذهبي، الإمام السيوطي، ابن حجر العسقلاني، الكاساني، الشوكاني.",
    update_type: "إعلان",
    source_url: "/sheikhs",
    published_at: "2026-07-11T23:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-77",
    title: "تحديث: الإعجاز العلمي — 77 معجزة",
    summary: "إضافة 5 معجزات: إعجاز النحل والعسل، الناصية مركز القرار، الدخان وتكوّن الكون، الأزواج في كل شيء، بصمات الأصابع.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-11T23:30:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-80",
    title: "تحديث: الطب النبوي — 80 موضوع",
    summary: "إضافة 4 موضوعات: الرمان وفوائده القرآنية، الصيام الصحي وجائزة نوبل 2016، السواك ومضادات البكتيريا.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-12T00:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-issues-56",
    title: "تحديث: مجمع الفقه — 56 مسألة معاصرة",
    summary: "إضافة 3 مسائل: حكم الاستفتاء من الذكاء الاصطناعي، عقد النكاح عبر الإنترنت، زكاة أسهم التقنية والسيارات الكهربائية.",
    update_type: "فتوى",
    source_url: "/fiqh-council",
    published_at: "2026-07-12T01:00:00Z",
    status: "approved",
  },
  {
    id: "update-sheikhs-91",
    title: "تحديث: قاعدة العلماء — 91 عالماً",
    summary: "إضافة 5 علماء معاصرين وكلاسيكيين: ابن باز، ابن عثيمين، الألباني، ابن جبرين، ابن القيم الجوزية.",
    update_type: "إعلان",
    source_url: "/sheikhs",
    published_at: "2026-07-12T02:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-108",
    title: "تحديث: الفتاوى — 108+ فتوى",
    summary: "إضافة 3 فتاوى: حكم البيتكوين والعملات الرقمية، تطبيقات أوقات الصلاة، التقسيط عبر تابي وتمارا.",
    update_type: "فتوى",
    source_url: "/fatwas",
    published_at: "2026-07-12T03:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-52",
    title: "تحديث: القصص الإسلامية — 52 قصة",
    summary: "إضافة قصتين: خالد بن الوليد (سيف الله المسلول)، وعمر بن الخطاب (الفاروق).",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-12T04:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-822",
    title: "تحديث: مسابقة الاختبار الإسلامي — 822+ سؤال",
    summary: "إضافة 20 سؤالاً في: الصحابة الكرام، العلماء والأئمة، التاريخ الإسلامي، الفقه، القرآن، العقيدة، الفتوحات، الأنبياء، الأذكار.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-12T05:00:00Z",
    status: "approved",
  },
  {
    id: "update-fawaid-377",
    title: "تحديث: الفوائد العلمية — 377+ فائدة",
    summary: "إضافة 15 فائدة في: الصبر والتوكل، الدعاء للأخ، فضل التواضع، العلم والخشية، الرحمة، الصحبة الصالحة، ليلة القدر، الاستغفار، شكر الناس.",
    update_type: "إعلان",
    source_url: "/fawaid",
    published_at: "2026-07-12T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-courses-61",
    title: "تحديث: الدورات العلمية — 61+ دورة",
    summary: "إضافة 3 دورات: علم الفرائض والمواريث، البلاغة القرآنية والإعجاز البياني، شرح العقيدة الواسطية.",
    update_type: "إعلان",
    source_url: "/lessons",
    published_at: "2026-07-12T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-adhkar-332",
    title: "تحديث: الأذكار — 332+ ذكر",
    summary: "إضافة 10 أذكار في: الصلاة الإبراهيمية، أذكار الوضوء، أذكار النوم، الصباح، الاستغفار.",
    update_type: "إعلان",
    source_url: "/adhkar",
    published_at: "2026-07-12T07:30:00Z",
    status: "approved",
  },
  {
    id: "update-perf-bundle-split",
    title: "تحسين: سرعة تحميل الموقع بنسبة 80%",
    summary: "تقليل حجم الحزمة الرئيسية (platform-services) من 103 كيلوبايت إلى 20 كيلوبايت بعد تحسين تقسيم الـ chunks، وتسريع التحميل الأولي وتقليل وقت الاستجابة التفاعلية TTI.",
    update_type: "إعلان",
    source_url: "/features-in-progress",
    published_at: "2026-07-11T15:00:00Z",
    status: "approved",
  },
  {
    id: "update-seo-scholar-library-pages",
    title: "جديد: 100+ صفحة عالم و50+ صفحة كتاب مُحسَّنة لمحركات البحث",
    summary: "أُضيف محتوى SEO مُفصَّل لصفحات 100+ عالم (منهم البخاري، الغزالي، ابن تيمية، ابن القيم، الألباني) و50+ كتاب في المكتبة، مع بيانات JSON-LD وعناوين دقيقة.",
    update_type: "إعلان",
    source_url: "/scholars",
    published_at: "2026-07-11T14:00:00Z",
    status: "approved",
  },
  {
    id: "update-pwa-assets-cache",
    title: "تحسين: العمل دون اتصال أكثر استقراراً",
    summary: "ترقية Service Worker إلى v17 مع تخزين جميع ملفات الموقع المُبعثرة في ذاكرة التخزين المؤقت للعمل الكامل دون اتصال بالإنترنت.",
    update_type: "إعلان",
    source_url: "/features-in-progress",
    published_at: "2026-07-11T13:00:00Z",
    status: "approved",
  },
  {
    id: "update-sheikhs-101",
    title: "تحديث: قاعدة العلماء — 101+ عالماً",
    summary: "إضافة 10 علماء: القرضاوي، الزرقا، الزحيلي، الفوزان، الطنطاوي، أبو زيد، الغزالي، زرّوق، القنوجي، وعلماء آخرون من الخليج والعالم.",
    update_type: "إعلان",
    source_url: "/sheikhs",
    published_at: "2026-07-12T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-council-26",
    title: "تحديث: قرارات المجمع الفقهي — 26+ قرار",
    summary: "إضافة 3 قرارات: القتل الرحيم والإيثانازيا، الوصية الإلكترونية الرقمية، زكاة التطبيقات التلقائية.",
    update_type: "قرار",
    source_url: "/fiqh-council",
    published_at: "2026-07-12T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-qa-330",
    title: "تحديث: الأسئلة والأجوبة، 330+ سؤال",
    summary: "إضافة 10 أسئلة في: الصلاة، الصيام في السفر، الاجتهاد والتقليد، علم الإسناد، الزكاة، حج المرأة، أركان الإيمان.",
    update_type: "إعلان",
    source_url: "/qa",
    published_at: "2026-07-12T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-amr-bil-maruf-section",
    title: "قسم جديد: الأمر بالمعروف والنهي عن المنكر",
    summary: "أُضيف قسم شامل للأمر بالمعروف والنهي عن المنكر يتضمن المراتب الثلاث وشروطها وأحكامها وأقوال العلماء.",
    update_type: "إعلان",
    source_url: "/amr-bil-maruf",
    published_at: "2026-07-11T12:00:00Z",
    status: "approved",
  },
  {
    id: "update-islamic-orgs-expanded",
    title: "توسعة: الهيئات والمنظمات الإسلامية",
    summary: "تحوّل قسم المجمع الفقهي ليشمل: هيئة كبار العلماء، اللجنة الدائمة، رابطة العالم الإسلامي، إدارة الإفتاء الكويتية، المجلس الأوروبي للإفتاء.",
    update_type: "إعلان",
    source_url: "/fiqh-council",
    published_at: "2026-07-11T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-57",
    title: "تحديث: القصص الإسلامية، 57+ قصة كاملة",
    summary: "إضافة 5 قصص تفصيلية: صلاح الدين الأيوبي وفتح القدس، خديجة بنت خويلد، طارق بن زياد، الإمام مالك، وغزوة بدر الكبرى.",
    update_type: "إعلان",
    source_url: "/islamic-stories",
    published_at: "2026-07-11T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-library-156",
    title: "توسعة: المكتبة الشرعية، 156+ كتاب",
    summary: "إضافة 8 كتب موثقة: الموافقات للشاطبي، منهاج الطالبين للنووي، الأدب المفرد للبخاري، الفقه على المذاهب الأربعة للجزيري وغيرها.",
    update_type: "كتاب",
    source_url: "/library",
    published_at: "2026-07-11T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-89",
    title: "تحديث: الطب النبوي، 89+ عنصر",
    summary: "إضافة: العجوة، الحبة السوداء، الحجامة، الصيام الطوعي وفوائده العلمية، ماء زمزم.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-11T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-872",
    title: "تحديث: بنك الأسئلة يبلغ 872 سؤالاً",
    summary: "إضافة 16 سؤالاً تاريخياً وجغرافياً في فئات الأندلس (5 أسئلة)، الخلفاء، العلماء، المعارك، والفتوحات.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T12:00:00Z",
    status: "approved",
  },
  {
    id: "update-topics-12",
    title: "تحديث: شبكة المواضيع المشوقة — 12 موضوعاً",
    summary: "إضافة 4 مواضيع جديدة للصفحة الرئيسية: الشمائل المحمدية، الجنة والنار، فضائل الأعمال، وآداب طالب العلم.",
    update_type: "إعلان",
    source_url: "/",
    published_at: "2026-07-11T11:00:00Z",
    status: "approved",
  },
  {
    id: "update-sunnah-time-enriched",
    title: "تحديث: سنة اليوم — اقتراحات أكثر ثراءً",
    summary: "توسيع مقترحات سنة اليوم من 3 إلى 4-5 اقتراحات لكل وقت صلاة، تشمل: الفوائد، الرقائق، حكم السلف، الوصايا، والدروس.",
    update_type: "إعلان",
    source_url: "/",
    published_at: "2026-07-11T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-886",
    title: "بنك الأسئلة يبلغ 886 سؤالاً",
    summary: "إضافة 14 سؤالاً تاريخياً وعلمياً: 8 أسئلة في العلماء والأئمة (البخاري، النووي، الغزالي، ابن تيمية، الشافعي، ابن حجر، الأئمة الأربعة، ابن القيم)، و6 أسئلة في الأسماء الحسنى.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T14:00:00Z",
    status: "approved",
  },
  {
    id: "update-sitemap-amr",
    title: "تحديث خريطة الموقع",
    summary: "إضافة صفحة «الأمر بالمعروف والنهي عن المنكر» لخريطة الموقع، وإضافة موسمَي محرم 1448 وربيع الأول 1448 لويدجت مواسم التعلم.",
    update_type: "إعلان",
    source_url: "/site-map",
    published_at: "2026-07-11T13:00:00Z",
    status: "approved",
  },
  {
    id: "update-daily-hadith-pool",
    title: "تحديث الركن اليومي — أحاديث الأربعين النووية",
    summary: "توسيع مجموعة «حديث اليوم» في الركن اليومي من 7 أحاديث إلى 47 حديثاً بإضافة الأربعين النووية الكاملة، مما يوفر تنوعاً أسبوعياً أكبر.",
    update_type: "إعلان",
    source_url: "/arbaeen-nawawi",
    published_at: "2026-07-11T15:00:00Z",
    status: "approved",
  },
  {
    id: "update-hadith-seerah",
    title: "تعزيز الحديث (38 سؤالاً) والسيرة (38 سؤالاً)",
    summary: "إضافة 9 أسئلة حديثية: عدد البخاري، رياض الصالحين، الفرق بين السنة والحديث، الكتب الستة بالترتيب، علو الإسناد، منهج النووي. و9 أسئلة سيرة: أبو طالب، ربيع الأول، ثويبة وحليمة، غزوة تبوك، سرية مؤتة، رسائل الملوك، هجرة الحبشة.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T18:30:00Z",
    status: "approved",
  },
  {
    id: "update-anbiya-37",
    title: "تعزيز قسم قصص الأنبياء — 37 سؤالاً",
    summary: "إضافة 8 أسئلة جديدة: الأنبياء هود وصالح وشعيب ورسالتهم، تميّز موسى بالكلام المباشر لله، قصة الخضر، سبب رمي الألواح، قصص الكهف الثلاث.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T18:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-34",
    title: "تعزيز قسم الفقه — 34 سؤالاً",
    summary: "إضافة 7 أسئلة فقهية: نصاب الفضة، أسباب الإفطار، مبطلات الوضوء، شروط الصوم، أنواع الطلاق، زكاة الأموال.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T17:30:00Z",
    status: "approved",
  },
  {
    id: "update-tarikh-aqeeda",
    title: "تعزيز قسمَي التاريخ والعقيدة في لعبة المعرفة",
    summary: "إضافة 13 سؤالاً جديداً: 9 للتاريخ الإسلامي (الدولة الأموية، بغداد، اليرموك، الدولة العثمانية، سقوط الأندلس، المغول) و4 للعقيدة (النبي والرسول، الكفر، الخوارج والمرجئة، البدعة).",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T17:00:00Z",
    status: "approved",
  },
  {
    id: "update-akhlaq-37",
    title: "تحديث قسم الأخلاق والصحابة — 37 سؤالاً",
    summary: "إضافة 15 سؤالاً جديداً في قسم «الأخلاق والصحابة»: صفات الصحابة وسيرهم (أبو هريرة، فاطمة الزهراء، عبد الرحمن بن عوف، أبو عبيدة، ابن مسعود)، والأخلاق النبوية (الصدق، الحياء، الورع، الكبر، الرضا).",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-11T16:00:00Z",
    status: "approved",
  },
];

export function getSortedUpdates(limit?: number) {
  const sorted = [...UPDATES_SEED].sort(
    (a, b) => (b.published_at || "").localeCompare(a.published_at || ""),
  );
  return limit ? sorted.slice(0, limit) : sorted;
}
