import type { PlatformUpdate } from "./platform-types";

export const UPDATES_SEED: PlatformUpdate[] = [
  {
    id: "update-fiqh-crypto",
    title: "قرار جديد: حكم التعامل بالعملات الرقمية",
    summary: "صدر قرار المجمع الفقهي بشأن العملات الرقمية.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_id: "fiqh-crypto-2024",
    source_url: "/fiqh-council/fiqh-crypto-2024",
    published_at: "2024-03-15T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-travel",
    title: "فتوى جديدة: الإفطار للمسافر في رمضان",
    summary: "إضافة فتوى حول جواز الإفطار للمسافر.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_id: "fatwa-fasting-travel",
    source_url: "/fatwa/fatwa-fasting-travel",
    published_at: "2024-02-28T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-course-ijazah",
    title: "فتح التسجيل: دورة الإجازة 1447هـ",
    summary: "بدء التسجيل في الدورة السنوية للإجازة.",
    update_type: "دورة",
    source_type: "annual_course",
    source_id: "course-ijazah-tahrir-2026",
    source_url: "/annual-courses/course-ijazah-tahrir-2026",
    published_at: "2025-12-01T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-tafsir",
    title: "درس جديد: تفسير سورة النحل",
    summary: "انضم درس تفسير سورة النحل إلى جدول الدروس.",
    update_type: "درس",
    source_type: "lesson",
    source_id: "kw-othman-tafsir-nahl-0",
    source_url: "/lessons/kw-othman-tafsir-nahl-0",
    published_at: "2025-11-20T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-library-book",
    title: "كتاب جديد: رياض الصالحين",
    summary: "إضافة كتاب رياض الصالحين إلى المكتبة العلمية.",
    update_type: "كتاب",
    source_type: "library",
    source_url: "/library",
    published_at: "2025-11-10T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-ramadan",
    title: "إعلان: البرنامج العلمي الرمضاني 1447",
    summary: "إعلان عن بدء البرنامج العلمي في شهر رمضان.",
    update_type: "إعلان",
    source_url: "/annual-courses/course-ramadan-intensive",
    published_at: "2025-11-15T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-news-conference",
    title: "خبر علمي: مؤتمر الفقه المعاصر",
    summary: "انعقاد مؤتمر الفقه المعاصر ونشر أبحاثه.",
    update_type: "خبر علمي",
    source_url: "/fiqh-council",
    published_at: "2025-10-01T05:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-prayer-timing",
    title: "فتوى جديدة: الصلاة بالتوقيت الفلكي",
    summary: "صدور فتوى تُجيز الاعتماد على حسابات التوقيت الفلكي لتحديد أوقات الصلاة.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fatwa/fatwa-prayer-timing",
    published_at: "2026-06-15T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-zakat-crypto",
    title: "قرار جديد: زكاة العملات الرقمية",
    summary: "إصدار قرار فقهي بوجوب الزكاة على العملات الرقمية وكيفية احتسابها.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/zakat-crypto",
    published_at: "2026-05-20T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-usul-fiqh",
    title: "درس جديد: أصول الفقه المقارن",
    summary: "إضافة سلسلة دروس في أصول الفقه المقارن بين المذاهب.",
    update_type: "درس",
    source_type: "lesson",
    source_url: "/lessons/usul-fiqh-muqaran",
    published_at: "2026-05-10T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-book-fiqh-muyassar",
    title: "كتاب جديد: الفقه الميسر",
    summary: "إضافة كتاب الفقه الميسر في ضوء الكتاب والسنة إلى المكتبة.",
    update_type: "كتاب",
    source_type: "library",
    source_url: "/library",
    published_at: "2026-04-25T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-annual-forum",
    title: "إعلان: الملتقى الفقهي السنوي 1448هـ",
    summary: "الإعلان عن انعقاد الملتقى الفقهي السنوي وموضوعاته الرئيسية.",
    update_type: "إعلان",
    source_url: "/fiqh-council",
    published_at: "2026-04-01T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-news-conference-research",
    title: "خبر علمي: نشر أبحاث مؤتمر الفقه الطبي",
    summary: "نشر وقائع وأبحاث مؤتمر الفقه الطبي المعاصر.",
    update_type: "خبر علمي",
    source_url: "/fiqh-council",
    published_at: "2026-03-15T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-general-anesthesia",
    title: "فتوى جديدة: حكم التخدير الكلي في الجراحة",
    summary: "بيان جواز التخدير الكلي عند الضرورة الطبية.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/general-anesthesia",
    published_at: "2026-03-01T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-human-cloning",
    title: "قرار جديد: تحريم الاستنساخ البشري التكاثري",
    summary: "قرار فقهي بتحريم الاستنساخ البشري التكاثري وبيان ضوابط العلاجي.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/human-cloning",
    published_at: "2026-02-10T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-course-tibb-fiqhi",
    title: "فتح التسجيل: دورة الفقه الطبي 1447هـ",
    summary: "بدء التسجيل في الدورة التخصصية للفقه الطبي المعاصر.",
    update_type: "دورة",
    source_type: "annual_course",
    source_url: "/annual-courses/course-tibb-fiqhi-2026",
    published_at: "2026-01-15T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-bulugh-maram",
    title: "درس جديد: شرح بلوغ المرام",
    summary: "إضافة سلسلة شرح بلوغ المرام من الأدلة إلى جدول الدروس.",
    update_type: "درس",
    source_type: "lesson",
    source_url: "/lessons/bulugh-al-maram-sharh",
    published_at: "2026-01-05T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-book-contemporary-fiqh",
    title: "كتاب جديد: المسائل الفقهية المعاصرة",
    summary: "إضافة كتاب المسائل الفقهية المعاصرة ودراسة أدلتها إلى المكتبة.",
    update_type: "كتاب",
    source_type: "library",
    source_url: "/library",
    published_at: "2025-12-20T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-winter-course",
    title: "إعلان: الدورة الشتوية العلمية 1447هـ",
    summary: "الإعلان عن موعد وبرنامج الدورة الشتوية العلمية.",
    update_type: "إعلان",
    source_url: "/annual-courses",
    published_at: "2025-12-10T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-misyar-marriage",
    title: "فتوى جديدة: حكم زواج المسيار",
    summary: "بيان أحكام وضوابط زواج المسيار وأثره على الحقوق الزوجية.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/misyar-marriage",
    published_at: "2025-11-25T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-news-family-forum",
    title: "خبر علمي: ملتقى الأسرة المسلمة المعاصرة",
    summary: "انعقاد ملتقى الأسرة المسلمة المعاصرة ومخرجاته الفقهية.",
    update_type: "خبر علمي",
    source_url: "/fiqh-council",
    published_at: "2025-11-01T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-electronic-divorce",
    title: "فتوى جديدة: الطلاق الإلكتروني",
    summary: "بيان وقوع الطلاق عبر الرسائل الإلكترونية ووسائل التواصل.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/electronic-divorce",
    published_at: "2025-10-15T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-tajweed",
    title: "درس جديد: أحكام التجويد العملي",
    summary: "إضافة سلسلة أحكام التجويد العملي مع التطبيق إلى جدول الدروس.",
    update_type: "درس",
    source_type: "lesson",
    source_url: "/lessons/tajweed-applied",
    published_at: "2025-10-01T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-health-insurance",
    title: "قرار جديد: حكم التأمين الصحي",
    summary: "قرار فقهي في جواز التأمين الصحي التعاوني وضوابط التجاري.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/health-insurance-ruling",
    published_at: "2025-09-20T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-course-ijazah-2025",
    title: "فتح التسجيل: دورة الإجازة العلمية 1447هـ",
    summary: "بدء التسجيل في دورة الإجازة العلمية لهذا العام.",
    update_type: "دورة",
    source_type: "annual_course",
    source_url: "/annual-courses/course-ijazah-2025",
    published_at: "2025-09-01T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-book-arbaeen-nawawi",
    title: "كتاب جديد: شرح الأربعين النووية",
    summary: "إضافة شرح الأربعين النووية في ضوء الفقه المعاصر إلى المكتبة.",
    update_type: "كتاب",
    source_type: "library",
    source_url: "/library",
    published_at: "2025-08-25T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-ilm-initiative",
    title: "إعلان: مبادرة العلم للجميع",
    summary: "إطلاق مبادرة العلم للجميع لتيسير وصول المحتوى العلمي.",
    update_type: "إعلان",
    source_url: "/",
    published_at: "2025-08-10T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-astronaut-prayer",
    title: "فتوى جديدة: صلاة رواد الفضاء",
    summary: "بيان أوقات الصلاة واتجاه القبلة لرواد الفضاء في المدار الأرضي.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/astronaut-prayer",
    published_at: "2025-07-20T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-news-digital-fiqh",
    title: "خبر علمي: ندوة الفقه الرقمي",
    summary: "انعقاد ندوة الفقه الرقمي وأبحاثها في المعاملات الإلكترونية.",
    update_type: "خبر علمي",
    source_url: "/fiqh-council",
    published_at: "2025-07-01T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-lesson-seerah",
    title: "درس جديد: السيرة النبوية المقارنة",
    summary: "إضافة سلسلة دروس السيرة النبوية المقارنة مع المصادر التاريخية.",
    update_type: "درس",
    source_type: "lesson",
    source_url: "/lessons/seerah-muqarana",
    published_at: "2025-06-15T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-new-sections",
    title: "تحديث المسابقات: إضافة أسئلة جديدة",
    summary: "إضافة 25 سؤالاً جديداً في الأخلاق وعلوم القرآن والحديث والألغاز الشرعية.",
    update_type: "خبر علمي",
    source_url: "/quiz",
    published_at: "2026-07-08T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwa-ai-jurisprudence",
    title: "فتوى جديدة: الذكاء الاصطناعي في الاجتهاد الفقهي",
    summary: "بيان ضوابط الاستعانة بأدوات الذكاء الاصطناعي في البحث الفقهي والإفتاء.",
    update_type: "فتوى",
    source_type: "fatwa",
    source_url: "/fiqh-council/ai-jurisprudence",
    published_at: "2026-07-05T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-decision-waqf-digital",
    title: "قرار جديد: الوقف الرقمي",
    summary: "قرار فقهي بإقرار الوقف الرقمي كنوع مستجد من أنواع الوقف المشروع.",
    update_type: "قرار",
    source_type: "fiqh_decision",
    source_url: "/fiqh-council/waqf-digital",
    published_at: "2026-07-03T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-course-summer-2026",
    title: "فتح التسجيل: الدورة العلمية الصيفية 1448هـ",
    summary: "بدء التسجيل في الدورة العلمية الصيفية وبرنامجها التفصيلي.",
    update_type: "دورة",
    source_type: "annual_course",
    source_url: "/annual-courses",
    published_at: "2026-07-01T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-announcement-quran-memorize",
    title: "إعلان: برنامج حفظ القرآن الصيفي 1448هـ",
    summary: "انطلاق برنامج الحفظ الصيفي للقرآن الكريم للناشئة والكبار.",
    update_type: "إعلان",
    source_url: "/scientific-announcements/sci-quran-memorization-program",
    published_at: "2026-07-01T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-book-maqasid-shariah",
    title: "كتاب جديد: مقاصد الشريعة الإسلامية",
    summary: "إضافة كتاب مقاصد الشريعة الإسلامية لابن عاشور إلى المكتبة العلمية.",
    update_type: "كتاب",
    source_type: "library",
    source_url: "/library",
    published_at: "2026-06-28T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-news-isesco-forum",
    title: "خبر علمي: ملتقى منظمة إيسيسكو للفقه الإسلامي",
    summary: "اختتام ملتقى منظمة إيسيسكو الدولي للفقه الإسلامي وقراراته الختامية.",
    update_type: "خبر علمي",
    source_url: "/fiqh-council",
    published_at: "2026-06-25T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-new-categories",
    title: "تحديث: إضافة فئات جديدة للإعجاز العلمي",
    summary: "إضافة 5 فئات جديدة من الإعجاز القرآني: الضوء، الجلد، العظام، النجوم، والدم.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-08T10:00:00Z",
    status: "approved",
  },
  {
    id: "update-scholars-expanded",
    title: "تحديث: توسعة قاعدة بيانات العلماء",
    summary: "إضافة 6 علماء جدد من كبار أئمة الإسلام: ابن تيمية، النووي، ابن كثير، الشنقيطي، وآخرين.",
    update_type: "إعلان",
    source_url: "/lessons",
    published_at: "2026-07-08T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-adhkar-enriched",
    title: "تحديث: إثراء قسم الأذكار",
    summary: "إضافة 10 أذكار جديدة في فئات الخروج من المنزل، السوق، اللباس، وركوب السيارة.",
    update_type: "إعلان",
    source_url: "/adhkar",
    published_at: "2026-07-08T08:00:00Z",
    status: "approved",
  },
  {
    id: "update-occasions-expanded",
    title: "تحديث: إضافة مناسبات إسلامية جديدة",
    summary: "إضافة عشر ذي الحجة، عيد الأضحى، عيد الفطر، وليلة نصف شعبان في تقويم المناسبات.",
    update_type: "إعلان",
    source_url: "/prayer-times",
    published_at: "2026-07-08T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-islamic-stories-expanded",
    title: "تحديث: إضافة قصص إسلامية جديدة",
    summary: "إضافة 5 قصص إسلامية جديدة: عثمان بن عفان، علي بن أبي طالب، بلال الحبشي، فتح الأندلس، وعائشة أم المؤمنين.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-08T12:00:00Z",
    status: "approved",
  },
  {
    id: "update-sharia-rulings-expanded",
    title: "تحديث: توسعة موسوعة الأحكام الشرعية",
    summary: "إضافة 5 أحكام شرعية جديدة: موجبات الغسل، التيمم، أركان الحج، أنواع الطلاق، وشروط البيع.",
    update_type: "إعلان",
    source_url: "/rulings",
    published_at: "2026-07-08T11:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-expanded",
    title: "تحديث: إثراء الطب النبوي",
    summary: "إضافة 4 مواد جديدة في قسم الطب النبوي: الخل، العدس، النوم على الجنب الأيمن، والسواك.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-08T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-rulings-5-new",
    title: "تحديث: 5 أحكام شرعية جديدة",
    summary: "إضافة أحكام جديدة تشمل: القروض العقارية البنكية، زكاة الراتب، شروط الجمعة، أنواع العِدَّة، وأحكام التعصيب في الميراث.",
    update_type: "إعلان",
    source_url: "/rulings",
    published_at: "2026-07-08T15:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-sessions-expanded",
    title: "تحديث: إضافة جلسات مجمع فقهي تاريخية",
    summary: "إضافة 5 جلسات جديدة للمجمع الفقهي الإسلامي (14-17 و23) تغطي موضوعات الجائحة، التأمين، التمويل الإسلامي، والوصايا الرقمية.",
    update_type: "إعلان",
    source_url: "/fiqh-council",
    published_at: "2026-07-08T16:00:00Z",
    status: "approved",
  },
  {
    id: "update-fawaid-curated-14",
    title: "تحديث: 14 فائدة علمية جديدة",
    summary: "إضافة فوائد منتقاة في العقيدة، الحديث، السيرة، اللغة، طلب العلم، والدعوة من كتب الأئمة والمحدثين.",
    update_type: "إعلان",
    source_url: "/fawaid",
    published_at: "2026-07-08T17:00:00Z",
    status: "approved",
  },
  {
    id: "update-scholars-65",
    title: "تحديث: الموسوعة العلمية تضم 65 عالماً",
    summary: "إضافة 10 علماء جدد منهم: الإمام الذهبي، ابن حجر، القرطبي، الشاطبي، ابن باز، ابن عثيمين، الألباني، والرازي.",
    update_type: "إعلان",
    source_url: "/sheikhs",
    published_at: "2026-07-06T09:00:00Z",
    status: "approved",
  },
  {
    id: "update-prophetic-medicine-v2",
    title: "تحديث: الطب النبوي — 5 عناصر جديدة وإصلاح تكرار",
    summary: "إضافة عناصر جديدة للطب النبوي: صلاة الفجر والضوء الصباحي، الزبيب، الوضوء بالماء البارد، الصدقة وأثرها النفسي، الشعير والتلبينة. مع إصلاح مُعرّفات مكررة.",
    update_type: "إعلان",
    source_url: "/prophetic-medicine",
    published_at: "2026-07-08T18:00:00Z",
    status: "approved",
  },
  {
    id: "update-fiqh-issues-5-new",
    title: "تحديث: 5 مسائل فقهية معاصرة جديدة",
    summary: "إضافة 5 مسائل فقهية: زراعة الشعر والتجميل، التمويل الجماعي، الصيام في البلاد القطبية، فسخ النكاح بسبب التدليس، وحكم CBD الطبي.",
    update_type: "إعلان",
    source_url: "/fiqh-council",
    published_at: "2026-07-08T19:00:00Z",
    status: "approved",
  },
  {
    id: "update-scientific-announcements-5-new",
    title: "تحديث: 5 إعلانات علمية جديدة",
    summary: "إضافة إعلانات: دورة الفرائض، الفقه المقارن، مكثف مصطلح الحديث، السيرة المدنية، وندوة النوازل والفتاوى المعاصرة.",
    update_type: "إعلان",
    source_url: "/lessons",
    published_at: "2026-07-08T20:00:00Z",
    status: "approved",
  },
  {
    id: "update-library-108-books",
    title: "تحديث: المكتبة الشرعية تضم 108 كتاباً",
    summary: "إضافة 8 كتب جديدة: البداية والنهاية، مقدمة ابن خلدون، أسرار الحِكَم لابن رجب، اقتضاء الصراط، شرح الأربعين، أسرار البلاغة، تلقيح فهوم ابن الجوزي، أدب الدنيا والدين للماوردي.",
    update_type: "إعلان",
    source_url: "/library",
    published_at: "2026-07-08T21:00:00Z",
    status: "approved",
  },
  {
    id: "update-quiz-660",
    title: "تحديث: بنك الأسئلة يتجاوز 660 سؤالاً",
    summary: "إضافة 30 سؤالاً جديداً (646-660) في الفقه والعقيدة والسيرة والقرآن والتاريخ الإسلامي.",
    update_type: "إعلان",
    source_url: "/quiz",
    published_at: "2026-07-08T22:00:00Z",
    status: "approved",
  },
  {
    id: "update-fatwas-74",
    title: "تحديث: الفتاوى الموثقة تبلغ 74 فتوى",
    summary: "إضافة 4 فتاوى: شروط الخُلع، كفارة اليمين، زكاة العملات الرقمية، نصيب الزوجة من الميراث.",
    update_type: "إعلان",
    source_url: "/fatwa",
    published_at: "2026-07-08T23:00:00Z",
    status: "approved",
  },
  {
    id: "update-rulings-43",
    title: "تحديث: الأحكام الشرعية تبلغ 43 حكماً",
    summary: "إضافة 4 أحكام: صلاة الجماعة، حكم الغيبة والنميمة، قضاء الصلاة الفائتة، شروط الاستطاعة في الحج.",
    update_type: "إعلان",
    source_url: "/rulings",
    published_at: "2026-07-09T06:00:00Z",
    status: "approved",
  },
  {
    id: "update-miracles-49",
    title: "تحديث: الإعجاز العلمي يضم 49 معجزة",
    summary: "إضافة 3 معجزات علمية: مستقبلات الألم في الجلد، الحديد مُنزَّل من الكون، والماء أصل كل حياة.",
    update_type: "إعلان",
    source_url: "/miracles",
    published_at: "2026-07-09T07:00:00Z",
    status: "approved",
  },
  {
    id: "update-stories-16",
    title: "تحديث: القصص الإسلامية — 16 قصة",
    summary: "إضافة 3 قصص: خالد بن الوليد سيف الله، فتح القدس وعدالة الفاروق، ابن بطوطة جوّال الإسلام الأعظم.",
    update_type: "إعلان",
    source_url: "/stories",
    published_at: "2026-07-09T08:00:00Z",
    status: "approved",
  },
];

export function getSortedUpdates(limit?: number) {
  const sorted = [...UPDATES_SEED].sort(
    (a, b) => (b.published_at || "").localeCompare(a.published_at || ""),
  );
  return limit ? sorted.slice(0, limit) : sorted;
}
