/**
 * سجل المسارات — مصدر الحقيقة (حزمة F).
 * يُشتق من مسارات App.tsx؛ الاختبار يفشل عند انحراف.
 * المكوّنات lazy تبقى في App حتى اكتمال ربط التنقّل.
 */
import type { ComponentType, LazyExoticComponent } from "react";

export type AppRouteSection =
  | "quran" | "lessons" | "hadith" | "fiqh" | "library" | "adhkar" | "prayer" | "tools" | "account" | "other";

export type AppRoute = {
  path: string;
  titleAr: string;
  descriptionAr?: string;
  section: AppRouteSection;
  icon?: string;
  component?: LazyExoticComponent<ComponentType<unknown>> | ComponentType<unknown>;
  inNav: boolean;
  inSitemap: boolean;
  related?: readonly string[];
};

function titleFromPath(path: string): string {
  const known: Record<string, string> = {
  "/": "الرئيسية",
  "/quran-hub": "القرآن الكريم",
  "/quran-knowledge": "علوم القرآن",
  "/mushaf": "المصحف",
  "/lessons": "الدروس",
  "/hadith": "الحديث",
  "/fiqh": "الفقه",
  "/library": "المكتبة",
  "/tarikh-islami": "التاريخ الإسلامي",
  "/adhkar": "الأذكار",
  "/prayer-times": "الصلاة",
  "/memorize": "الحفظ",
  "/search": "البحث",
  "/islamic-glossary": "مفاهيم شرعية",
  "/quiz": "المسابقة",
  "/competitions": "المسابقات",
  "/settings": "الإعدادات",
  "/internal/status": "حالة المنصة"
};
  if (known[path]) return known[path];
  const leaf = path.split("/").filter(Boolean).pop() ?? path;
  return leaf.replace(/[-_]/g, " ");
}

const PATHS = [
  "/",
  "/about",
  "/about-us",
  "/academic-research",
  "/academic-research/:id",
  "/academic-research/assistant",
  "/academic-research/submit",
  "/account-deletion",
  "/adab-talab-ilm",
  "/adhan-settings",
  "/adhan-help",
  "/adhkar",
  "/adhkar/:slug",
  "/admin",
  "/admin/auto-content",
  "/admin/automation",
  "/admin/automation/center",
  "/admin/automation/content-production",
  "/admin/automation/dashboard",
  "/admin/automation/platform",
  "/admin/automation/review",
  "/admin/automation/sources",
  "/admin/autonomous-platform",
  "/admin/content",
  "/admin/content-import/image",
  "/admin/content-import/url",
  "/admin/content-production",
  "/admin/dashboard",
  "/admin/feature-status",
  "/admin/fiqh-quality",
  "/admin/fiqh-review",
  "/admin/import",
  "/admin/integrations/instagram",
  "/admin/review-center",
  "/admin/review-hub",
  "/admin/sources",
  "/admin/universities",
  "/admin/users",
  "/akhlaq",
  "/alamat-saah",
  "/amr-bil-maruf",
  "/amrad-qalbiyya",
  "/anbiya",
  "/announcements",
  "/annual-courses",
  "/annual-courses/:id",
  "/arabic-language",
  "/arbaeen-nawawi",
  "/arbaeen-nawawi/:id",
  "/arkan",
  "/arkan-iman",
  "/asbab-al-nuzul",
  "/asma-husna",
  "/assistant",
  "/auth/callback",
  "/auth/register",
  "/auth/update-password",
  "/c/:slug",
  "/calendar",
  "/car-mode",
  "/cards",
  "/condolences",
  "/contact",
  "/courses",
  "/competitions",
  "/competitions/:id",
  "/daily-wird",
  "/dalail-nubuwwah",
  "/delete-account",
  "/discover-islam",
  "/discover-islam/articles/:slug",
  "/discover-islam/contact",
  "/discover-islam/doubts",
  "/discover-islam/doubts/:slug",
  "/discover-islam/how-to-convert",
  "/discover-islam/new-muslim",
  "/discover-islam/new-muslim/:day",
  "/discover-islam/questions",
  "/discover-islam/questions/:slug",
  "/duas",
  "/duas-quran",
  "/durus-imaniyya",
  "/durus-mutanawwia",
  "/events",
  "/explore",
  "/fadail-aamal",
  "/family",
  "/family-mode",
  "/fatwa",
  "/fatwa-policy",
  "/fatwa/:id",
  "/fatwas",
  "/fawaid",
  "/features-in-progress",
  "/fikr-waqia",
  "/fiqh",
  "/fiqh-council",
  "/fiqh-council/:slug",
  "/fiqh-council/archive",
  "/fiqh-council/categories",
  "/fiqh-council/compare",
  "/fiqh-council/fatwas",
  "/fiqh-council/index",
  "/fiqh-council/issues",
  "/fiqh-council/issues/:slug",
  "/fiqh-council/live",
  "/fiqh-council/nawazil",
  "/fiqh-council/recommendations",
  "/fiqh-council/research",
  "/fiqh-council/research-assistant",
  "/fiqh-council/resolutions",
  "/fiqh-council/search",
  "/fiqh-council/sessions/:slug",
  "/fiqh-council/stats",
  "/fiqh-qawaid",
  "/fiqh/books/:bookId",
  "/fiqh/books/:bookId/lessons/:lessonId",
  "/fiqh/topics/:topicId",
  "/fiqh/usul",
  "/flashcards",
  "/glossary",
  "/hadith",
  "/hadith-science",
  "/hadith/arbaeen-love-of-allah",
  "/hadith/books",
  "/hadith/books-and-rulings",
  "/hadith/daif",
  "/hadith/mawdu",
  "/hadith/sahih",
  "/hajj",
  "/hikam-salaf",
  "/iman-topics",
  "/institutions",
  "/islam-stats",
  "/islamic-directory",
  "/islamic-events",
  "/islamic-glossary",
  "/islamic-institutions",
  "/islamic-landmarks",
  "/islamic-sects",
  "/islamic-stories",
  "/internal/status",
  "/janaza",
  "/janna-naar",
  "/jumuah",
  "/kids",
  "/knowledge-graph",
  "/knowledge-map",
  "/kuwait-lessons",
  "/latest",
  "/learn",
  "/learn/:slug",
  "/learn/lesson/:id",
  "/learn/series/:slug",
  "/learning",
  "/learning-path",
  "/learning-path/:scienceSlug",
  "/learning-path/book/:bookId",
  "/learning-path/dashboard",
  "/learning-plan",
  "/learning/calendar",
  "/learning/certificates",
  "/learning/certificates/:code",
  "/lessons",
  "/lessons/:id",
  "/learning/quiz",
  "/learning/quiz/:slug",
  "/lesson-calendar",
  "/lessons",
  "/lessons/:id",
  "/lessons/archive",
  "/lessons/current",
  "/library",
  "/library/:id",
  "/licenses",
  "/login",
  "/madhahib",
  "/malaika",
  "/man-nahnu",
  "/maqasid-sharia",
  "/masajid",
  "/masarat",
  "/mawarith",
  "/mawarith/calculator",
  "/mawsuaat",
  "/memorization",
  "/memorization-plans",
  "/memorization-tests",
  "/memorize",
  "/methodology",
  "/mind-map",
  "/miracles",
  "/mosque-mode",
  "/mosques",
  "/muezzins",
  "/muezzins/:rest",
  "/mushaf",
  "/mushaf-v2-preview",
  "/mushaf/:surah",
  "/mushaf/about-edition",
  "/mushaf/page",
  "/mushaf/page/:page",
  "/mutashabihat",
  "/my-citations",
  "/my-learning",
  "/my-submissions",
  "/nations",
  "/nations/:slug",
  "/news",
  "/nikah",
  "/notification-settings",
  "/occasions",
  "/occasions-lessons",
  "/prayer-countdown",
  "/prayer-ranks",
  "/prayer-times",
  "/privacy",
  "/privacy-center",
  "/privacy-policy",
  "/profile",
  "/prophet-stories",
  "/prophet-stories/:slug",
  "/prophets-stories",
  "/prophets-stories/:slug",
  "/prophetic-medicine",
  "/prophets",
  "/prophets/:slug",
  "/prophets/tree",
  "/qibla",
  "/quiz",
  "/quran",
  "/quran-circles",
  "/quran-engine",
  "/quran-engine/viewer",
  "/quran-hub",
  "/quran-index",
  "/quran-knowledge",
  "/quran-memorization",
  "/quran-sciences",
  "/quran-stories",
  "/quran-studies",
  "/quran/makki-madani",
  "/quran/memorization-plans",
  "/quran/hifz-loop",
  "/quran/worship-hub",
  "/quran/offline-player",
  "/quran/recitation-test-ai",
  "/quran/revelation-order",
  "/quran/search",
  "/quran/surah-stories",
  "/quran/surah-stories/:number",
  "/quran/surahs",
  "/quran/tafsir",
  "/quran/tajweed",
  "/raqaiq",
  "/reading-plans",
  "/register",
  "/research",
  "/researcher",
  "/researcher-profile",
  "/researches",
  "/review-plans",
  "/reviewed-cards",
  "/riba",
  "/rulings",
  "/rulings/:id",
  "/ruqya",
  "/sadaqa",
  "/sahabah",
  "/salah-guide",
  "/sawm",
  "/scholarly-research",
  "/scientific-announcements/:id",
  "/scientific-library",
  "/search",
  "/search/:q",
  "/seerah",
  "/settings",
  "/shamael",
  "/sharia-research",
  "/sheikhs",
  "/sheikhs/:id",
  "/sins-and-rights",
  "/sins-and-rights/:slug",
  "/sitemap",
  "/sources",
  "/sources/:id",
  "/data-licenses",
  "/sources-licenses",
  "/start-here",
  "/stats",
  "/stories",
  "/study-room",
  "/submit",
  "/sujood-sahw",
  "/sunan-yawmiyya",
  "/sunnah-studies",
  "/support",
  "/surah-stories",
  "/tafsir",
  "/tahara",
  "/tajweed",
  "/talaq",
  "/tarikh-islami",
  "/tarikh-islami/:id",
  "/scholars",
  "/scholars/:id",
  "/tasbih",
  "/tawba",
  "/tawhid",
  "/tazkiya-topics",
  "/teachers",
  "/teachers/:slug",
  "/terms",
  "/topics",
  "/topics/:slug",
  "/transcribe",
  "/udhiya",
  "/ulum-quran",
  "/universities",
  "/universities/:slug",
  "/universities/compare",
  "/updates",
  "/updates/auto/:slug",
  "/upload",
  "/usra-mujtama",
  "/vault",
  "/waqf",
  "/wasaya-nabawiyya",
  "/whats-new",
  "/who-we-are",
  "/zakat",
  "/account/delete",
  "/aqidah",
  "/citations",
  "/courses/paths",
  "/demo-ayah-reader",
  "/feature-tour",
  "/hadith/:id",
  "/knowledge",
  "/knowledge/:section",
  "/knowledge/:section/:id",
  "/learning-paths",
  "/learning/paths",
  "/learning/paths/:slug",
  "/lessons/paths",
  "/more",
  "/pathways",
  "/prayer",
  "/prophets/al-yasaa",
  "/prophets/alyasa",
  "/prophets/ishaaq",
  "/prophets/ishaq",
  "/prophets/zakaria",
  "/prophets/zakariya",
  "/qa",
  "/qa/:rest*",
  "/quran-hub/numbers",
  "/quran-hub/qiraat",
  "/quran-hub/seven-ahruf",
  "/quran-hub/tajweed",
  "/quran-hub/tajweed/:chapter",
  "/quran-hub/terms",
  "/quran-hub/tilawa",
  "/quran/mushaf",
  "/quran/people",
  "/quran/people/:slug",
  "/quran/terms",
  "/sections",
  "/study-paths",
  "/tracks"
] as const;

const NAV_PATHS = new Set(["/","/quran-hub","/lessons","/hadith","/adhkar","/prayer-times","/search"]);

function inferSection(path: string): AppRouteSection {
  if (path === "/") return "other";
  if (/^\/(quran|mushaf|tilawa|tajweed|tafsir|ulum|surah)/.test(path)) return "quran";
  if (/^\/(lesson|learn|teacher|kuwait|competitions)/.test(path)) return "lessons";
  if (/^\/(hadith|sunnah|arbaeen)/.test(path)) return "hadith";
  if (/^\/(fiqh|ruling|zakat|hajj|janaza|mawarith|nikah|talaq|salah)/.test(path)) return "fiqh";
  if (/^\/(library|scholar)/.test(path)) return "library";
  if (/^\/(adhkar|dua|tasbih|wird)/.test(path)) return "adhkar";
  if (/^\/(prayer|qibla|adhan)/.test(path)) return "prayer";
  if (/^\/(login|register|settings|account|privacy|notification)/.test(path)) return "account";
  if (/^\/(search|memorize|quiz|flash|islamic-glossary|sitemap|glossary)/.test(path)) return "tools";
  return "other";
}

const SITEMAP_EXCLUDED =
  /^\/(admin|dashboard|login|register|api|search|settings|account|auth|internal)(\/|$)/;

export const ROUTE_REGISTRY: readonly AppRoute[] = PATHS.map((path) => ({
  path,
  titleAr: titleFromPath(path),
  section: inferSection(path),
  inNav: NAV_PATHS.has(path),
  inSitemap:
    !path.includes(":") &&
    !path.includes("*") &&
    !path.startsWith("/admin") &&
    !SITEMAP_EXCLUDED.test(path),
}));

export function getRouteByPath(path: string): AppRoute | undefined {
  return ROUTE_REGISTRY.find((r) => r.path === path);
}

export function routesInNav(): readonly AppRoute[] {
  return ROUTE_REGISTRY.filter((r) => r.inNav);
}

export function routesInSitemap(): readonly AppRoute[] {
  return ROUTE_REGISTRY.filter((r) => r.inSitemap);
}

export function routesBySection(section: AppRouteSection): readonly AppRoute[] {
  return ROUTE_REGISTRY.filter((r) => r.section === section);
}
